### ISSUE TITLE
same author name - different authors

### ISSUE THREAD

**Issue by jsteggy** [DobyTang/LazyLibrarian#1005]
### LazyLibrarian version number (at the bottom of config page)
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 3e2dbd1174b2572da2319f0336ac2f60a9fde17a : Latest Version: e9452bfaf003b24c30d4a7c747b3522031ad5b00

### Relevant debug log with api keys and any passwords redacted

Is there a way to add authors with the same name (same spelling) but who are different people?

**Comment by philborman** [comment]
Should be able to, we use the goodreads "authorid" for storage rather than the name.
eg If you have one "John Smith" in your database, try searching for a book title by the other "John Smith", or even just search for "John Smith".
The results should show "Have Author" by the one you've got in the database, and "Add Author" for the one you haven't got. 

If it's not working as described, post another message with the name of the author that's giving trouble and I'll take a look. Sometimes goodreads doesn't have the right info and merges authors or puts books under the wrong author, but the couple of examples I tried both worked ok.

**Comment by jsteggy** [comment]
Ian Douglas. One is a scifi writer one is a science writer. 
I have a bunch of the scifi writer's books, When I search "Ian Douglas" both sets of books show and LL says HAVE for both sets of books in the Add column for author.

**Comment by jsteggy** [comment]
alos, it does look like LL is identifying the authors separately. The ids for authors is different. After more checking, I am wrong and it looks like authors are working ok. The scifi writers is attached to the books. The search output does show that both authors are in my catalog but I can't find both - only the scifi writer.

**Comment by philborman** [comment]
For some reason the searchresults were using the authorname to tell if the author was in the database, we should really use the authorid instead. Could cause an issue if you switch from googlebooks to goodreads or vice-versa as each uses their own system and we won't realise the author is the same, but at least it would catch situations like this. I will push a fix using authorid in a couple of hours. I don't think there will be many users switching between providers.

**Comment by jsteggy** [comment]
Thanks. I like that solution too as there are some desired books by authors with same name.
