### ISSUE TITLE
author collections not processing

### ISSUE THREAD

**Issue by sumoyoshikai** [DobyTang/LazyLibrarian#1009]
all single book downloads are working fine with post processing. However anything that is in an author collection download, the folder just sits in the completed folder and never gets scanned or touched. Any ideas why this might be?

it simply downloads it and places it in the folder that LL should scan and move from, but the collection folders dont exist as far as LL is concerned....

I've tried moving all individual folders inside the author name such as 

/completed/authorname-collection/book name/ to just /completed/book name/ but it doesn't recognise that either but a single book downloads to /completed/author-bookname/ and it is then post processed and moved to my final ebook library destination no problems

**Comment by philborman** [comment]
Lazylibrarian postprocessor only processes individual books, there is no collection support. We keep track of what books we requested and watch for them arriving, which is why we aren't picking up collections. Would be possible to add code to handle collections, look inside zip/rar files etc but at the moment we don't.

Easiest way round it for now is to import them manually. Couple of options...
1. Move the books into your final lazylibrarian library structure and then libraryscan on the author to create the database entries. Author must already exist in your database for this to work.

2. Leave the books in /completed/authorname-collection/  with each book in it's own subfolder inside that and point "alternate import directory" in config to  /completed/authorname-collection/   then on the "manage" page click "import books".  This will move the books from /completed/authorname-collection/ into your lazylibrarian library structure and create entries in the database for author and books. It may also delete /completed/authorname-collection/  as it tidies up after itself, depending on config settings.

**Comment by sumoyoshikai** [comment]
thanks for the great reply Phil.  you mention  LL doesn't process collections.

If that's the case, why does it queue them up and download them only to not touch them? seems pointless to have the program specifically on it's own queue up an authors book collection which contains x amount of their books on your watch list only for it then to give up and go... 'oh yeah, I don't bother with that'

and if that indeed is how LazyLibrarian is programmed to work, is there any option to turn off LL from automatically snatching complete collector sets of books ? because if that's how it's specifically programmed to work it would be much easier, faster and cleaner to do the entire process start to finish manually.

the second way of importing manually works if i'm doing it each time an author has a set of books downloaded as one file, which could be a mystery because LazyLibrarian does it all on it's own... so even with that method you would have to constantly manually check all the files and folders in the download area to see what has been downloaded and just dumped there to remain forever.

I guess i could try and manually load up as many terms that might be included in a bunch of books to auto-reject such as "set, collection" etc... but even then it seems bizarre for it to pick the file, queue it up, flag the watchlist status snatched, have it sent to the download program, its moved to the folder ready to be post processed and lazylibrarian is made to at that point go "I dont do anything other than process single files"

**Comment by philborman** [comment]
The lazylibrarian search tasks prefer to download single books where available, it will only download collections/omnibus editions when it can't find the book packaged separately.

Separating the one book you might want out of a collection is something lazylibrarian can't easily automate, so at the moment it's best done manually. Lazylibrarian will find the collection and download it for you, saves you some of the work ;-)

As you correctly said above you can eliminate some collections by adding words like set, collection to the reject list.

**Comment by sumoyoshikai** [comment]
Ok thanks for your help, I might revisit the program down the track when downloading books becomes automated I will uninstall and just do things manually as it's easier and faster until then.
