### ISSUE TITLE
Not_Available_From_GitHUB

### ISSUE THREAD

**Issue by xcasex** [DobyTang/LazyLibrarian#1010]
Unable to update to a more recent version from gui, unable to get current version within LL config page (both button and bottom of page)

To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Current Version: 9c4e1b4d71777df4f18734271a6e42a0a8a1e97c 
### Operating system used (windows, mac, linux, NAS type)
dietpi (debian)
### Interface in use (default, bookstrap)
default
### Which api (Goodreads, GoogleBooks, both)
goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git
### Relevant debug log with api keys and any passwords redacted

debug log not needed:

Traceback (most recent call last):
  File "/root/LazyLibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/root/LazyLibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/root/LazyLibrarian/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/LazyLibrarian/lazylibrarian/webServe.py", line 2098, in saveLog
    result = saveLog()
  File "/root/LazyLibrarian/lazylibrarian/common.py", line 484, in saveLog
    logfile.write(header)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 222: ordinal not in range(128)

We have unicode errors ;)

**Comment by philborman** [comment]
The unicode error is from trying to save the debug log, nothing to do with why you can't upgrade.
Depending how old your lazylibrarian is, the unicode error might already be fixed.

There have been random reports of the upgrade mechanism not working from time to time, but I can never reproduce it. I use it all the time, every lazylibrarian change is coded on one machine and added to my main server using the upgrade mechanism. Seems somehow git gets out of step and thinks you are up to date when you are not.

Easiest way to force an upgrade, since you installed from git, is to cd into your lazylibrarian directory and do "git pull"

**Comment by xcasex** [comment]
hi @philborman we might have a slight misunderstanding here, there's unicode errors everywhere, this is a current version as you can see by the hash up there *points up* 

yes, but no, i can reproduce it.

**Comment by philborman** [comment]
Ah, ok. I see what you mean now. 
The puzzle now is why you are seeing
>  there's unicode errors everywhere, 

when other users don't.  What's different between your system and mine that might account for it.
It's either differences in the operating system, the python version, or the data we're trying to read (filenames, book titles etc)

There have been various unicode issues with lazylibrarian in the past, but seem to be pretty much ironed out now. A few issues with scandinavian and russian characters were fixed recently, but nothing in the "latin" characters.

The log line you quoted is odd for a couple of reasons...
> File "/root/LazyLibrarian/lazylibrarian/common.py", line 484, in saveLog
> logfile.write(header)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 222: ordinal not in range(128)

Firstly we shouldn't be encoding to ascii at all as the file we're writing to shouldn't care about encoding. Secondly you are trying to write out headers including a u'\xe5'  which is  
å | Latin Small Letter A With Ring Above

The headers contain basic info about your system, versions of software etc. Can't see why they would contain Latin Small Letter A With Ring Above, or why the logfile would care anyway. My headers are below as an example.  My best guess at the moment, with no real info to go on, is something in your os or python installation causing issues. If we knew what, we might be able to code around it. There were odd issues with Freenas systems a while ago (freebsd based)  giving problems writing out the config file. It turned out to be an issue with the freenas version of python 2.7.9 treating empty string values as boolean instead of string, but we could code around it.

I see you are on dietpi, which is a seriously stripped down version of debian jessie. I'm running my mediacenter on a raspberry pi3 with osmc (also based on debian jessie) and lazylibrarian runs fine on that, so has dietpi stripped out something we need? Maybe it doesn't include unicode support, or doesn't include utf-8 Just guessing really.  Any idea what version of python is included in dietpi ? (it would have been in the headers if we could log them)

Do you know if dietpi can run docker? If so there is a raspberry pi compatible docker for lazylibrarian.  Link is on the lazylibrarian homepage. That has it's own python installation with everything included, so if that runs ok it would point to dietpi python as the likely issue.

```
Startup cmd: ['/usr/bin/python', '/opt/LazyLibrarian/LazyLibrarian.py', '-d', '--nolaunch', '--config=/home/osmc/.lazylibrarian/config.ini', '--datadir=/home/osmc/.lazylibrarian', '--port=8089', '--pidfile=/var/run/lazylibrarian/lazylibrarian.pid']
Interface: bookstrap
Loglevel: 3
git_repo: lazylibrarian
git_user: philborman
git_branch: master
latest_version: df7a41a3c778d60772e336d707ed153d5054f4e6
git_updated: Tue, 29 Aug 2017 19:39:21 GMT
current_version: df7a41a3c778d60772e336d707ed153d5054f4e6
commits_behind: 0
install_type: git
Python version: ['2.7.9 (default, Aug 13 2016, 17:56:53) ', '[GCC 4.9.2]']
Distribution: ('debian', '8.9', '')
System: Linux
Machine: armv7l
Platform: Linux-4.9.29-9-osmc-armv7l-with-debian-8.9
uname: ('Linux', 'osmc', '4.9.29-9-osmc', '#1 SMP PREEMPT Sat Jul 29 01:44:42 UTC 2017', 'armv7l', '')
version: #1 SMP PREEMPT Sat Jul 29 01:44:42 UTC 2017
mac_ver: ('', ('', '', ''), '')
```

**Comment by mccorkled** [comment]
I am running the Docker version and getting "Not_Available_From_GitHUB" as well.

**Comment by philborman** [comment]
Sounds like there could be a communication issue talking to github, Can you try turning debug log on and click Version Check in config screen. Should show what's happening.

**Comment by mccorkled** [comment]
https://pastebin.com/JiNa8hmw

**Comment by philborman** [comment]
Your pastebin shows
2017-09-25 19:13:00 DEBUG   UPDATES versioncheck.py logmsg  40  git error for https://api.github.com/repos/dobytang/lazylibrarian/commits/master: Forbidden

Lazylibrarian sent the request and got "Forbidden" as the reply
Not sure if the message came from github, could be a temporary github problem,
or docker isn't allowing access so raised the error?

**Comment by mccorkled** [comment]
I do not know if you changed anything but it just updated.

**Comment by philborman** [comment]
No, nothing changed for a few days. Looking like a git hub problem, maybe
too many requests? I will add a bit more logging to show exactly what
github replied

**Comment by xcasex** [comment]
> It's either differences in the operating system, the python version, or the data we're trying to read (filenames, book titles etc)

as far as python goes, its current, libraries is also current as far as dependancies go. the data i.e the books, filenames etc contain swedish, norwegian, english and german language books.

There have been various unicode issues with lazylibrarian in the past, but seem to be pretty much ironed out now. A few issues with scandinavian and russian characters were fixed recently, but nothing in the "latin" characters.

> My best guess at the moment, with no real info to go on, is something in your os or python installation causing issues. If we knew what, we might be able to code around it. There were odd issues with Freenas systems a while ago (freebsd based) giving problems writing out the config file. It turned out to be an issue with the freenas version of python 2.7.9 treating empty string values as boolean instead of string, but we could code around it.
> 
> I see you are on dietpi, which is a seriously stripped down version of debian jessie. I'm running my mediacenter on a raspberry pi3 with osmc (also based on debian jessie) and lazylibrarian runs fine on that, so has dietpi stripped out something we need? Maybe it doesn't include unicode support, or doesn't include utf-8 Just guessing really. Any idea what version of python is included in dietpi ? (it would have been in the headers if we could log them)

i purpose-build my "servers" with dietpi as a base, so i can build them up from the bottom, which means i include dependancies etc.
the version of python is 2.7.9


> Do you know if dietpi can run docker? If so there is a raspberry pi compatible docker for lazylibrarian. Link is on the lazylibrarian homepage. That has it's own python installation with everything included, so if that runs ok it would point to dietpi python as the likely issue.

it can, but i wont. there are more than a few security related issues with docker which makes me want to steer clear of it.

i'll be digging into this tonight since i have some moments of leisure.

**Comment by Old-T** [comment]
I might shed some light on this.
I had the same problem and after some debugging found out that on my system I had in my config.ini:
[Git]
git_updated = mån, xx aug ...... (swedish for mon)
LL was able to READ the config file with mån but unable to WRITE the same string.
When I manually changed it from monday to tuesday, the error was gone and I was able to update my LL.
I probably have a Swedish locale set in my Ubuntu system which caused get to return the date string formatted in Swedish)

**Comment by philborman** [comment]
That would make sense. The version of configparser shipped as default with some python 2 systems does not handle unicode properly. The more recent installs default to the backports version which works properly. Maybe we should ship the backports version with lazylibrarian to be safe.

**Comment by philborman** [comment]
Well, it gets more complicated. The specs say that the datestring passed to git should only ever be sent using English day and month names, even though git might send us Swedish in response. I have just added some code to switch locale to English when talking to git, and store the git response as a timestamp instead of the string they send us. Seems ok, but could do with being tested on a non-english system to be sure. If it works we probably don't need to worry about shipping a new configparser with this new code in place.

What version of ubuntu are you running, out of interest. I'm on 17.10 and that ships with the backports version of configparser by default, or at least I don't recall doing anything extra to install it.

**Comment by Old-T** [comment]
I'm on Ubuntu 16.10

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by philborman** [comment]
New version with git communication using English locale has just been posted, hopefully should fix that part of the problem.

**Comment by Old-T** [comment]
HI,
I just updated my LL but it seems as if the date string from git is still
written in the language according to locale:
git_updated = fre, 22 dec 2017 06:50:17 GMT
which probably will make config_write to fail if I make the update on mon,
sat or sun.
Hmm... Unless the *git_updated *was written with previous version of LL
just before the update...
We'll see when the next update comes :-)

// T

tors 21 dec. 2017 kl 22:40 skrev philborman <notifications@github.com>:

**Comment by philborman** [comment]
Might depend on how you updated, was it the lazylibrarian internal update, git or tgz, a fresh git installation or a downloaded zipfile. They take different paths through the update code, a debug log would help.

Also if you have the update interval set to zero we don't monitor changes so don't update the timestamp.
If you run versioncheck from the config page you should not see the
`(getLatestVersion_FromGit) Checking if modified since %s`
 message as we ignore the old-style timestring, should go straight from 
`(getLatestVersion_FromGit) Retrieving latest version information from github command=[%s]`
to 
`(getLatestVersion_FromGit) Branch [%s] Latest Version has been set to [%s]`
or the "Not modified" or "Could not get version" messages

**Comment by philborman** [comment]
Just switched to hard coded English day/month names rather than messing about with locale settings. Also added some code at startup to wipe the old style config setting.

**Comment by Old-T** [comment]
I'd day that is a better approach since it isn't anything that will be presented to the user.

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________
