### ISSUE TITLE
[Bug?] Removing/Deleting Book Adds it to Ignored List. 

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1037]
If you add a book and then add a different version or just want to remove the book, clicking remove or delete just adds it to the ignore list.

**Comment by philborman** [comment]
That's intentional. LazyLibrarian keeps a list of the authors books. They still wrote it, even if you don't want it ;-)

"Remove" removes from the list, "Delete" also deletes your copy of the book.

If we really delete the database entry for the book it would just get replaced next time you refresh the author as lazylibrarian will think it's a new book, ie recently written.

**Comment by philborman** [comment]
Not sure how best to get round this, as I said earlier if we delete the entry in the database, refreshing the author will reload it as it will seem to be a new book. 

The book will still come up in a search using the search bar (the one that says Title/Author/ISBN), but not using the filter (results filter) as it's marked as ignored.

**Comment by philborman** [comment]
Next version will delete the book from the database if the author is not marked as active or wanted.
Should be an ok work-around, I think
