### ISSUE TITLE
Post Processing Strings

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1041]
I looked for a list of strings for renaming and didn't find any other than the two listed as examples in the program. Is there a way to rename books as Book, The - Author instead of The Book - Author?

Thank you! 
Sorry I am asking so many questions lately. I love this program and once I get it running properly I will be writing a tutorial on our blog to help others.

**Comment by philborman** [comment]
The default strings are just examples, the filenames are built up from 3 entries in config
1. eBook Library Folder
2. eBook/AudioBook Foldername Pattern
3. eBook Filename Pattern
it's very flexible, you can do many different naming styles. The words beginning with $ are replaced by the corresponding real value. The default is...
library_folder/authorname/booktitle/booktitle - authorname
so you might get /ebooks/Tom Holt/Grailblazers/Grailblazers - Tom Holt.mobi
1 /ebooks/
2 Tom Holt/Grailblazers  ($Author/$Title)
3 Grailblazers - Tom Holt.mobi  ($Title - $Author)

To rename books as Book, The - Author instead of The Book - Author, change ebook Filename Pattern from $Title - $Author to  $Author, $Title
This would give  /ebooks/Tom Holt/Grailblazers/Tom Holt, Grailblazers.mobi

**Comment by mccorkled** [comment]
I think you are possibly misunderstanding me. 

I am trying to turn:
The Lord of the Rings - J. R. R. Tolkien

to:

Lord of the Rings, The - J. R. R. Tolkien

**Comment by philborman** [comment]
Ah yes, I see.  No there is no way of doing that in lazylibrarian.

**Comment by mccorkled** [comment]
Ok thank you :)
