### ISSUE TITLE
Cannot get books to auto add to Calibre

### ISSUE THREAD

**Issue by osuhickeys** [DobyTang/LazyLibrarian#1122]
Playing around with the Calibre integration and not having much success getting it to work.  My end goal is to have the Calibre books folder be the sole source.  LL downloads a book, processes it. and leaves it in the LL download folder.  It also creates metadata.db in the LL download folder.  I see in the logs it calls Calibre, but it never shows up in the Calibre library.  Not sure what I have missed.  Looks like LL will process and add to Calibre, but will not move to the Calibre library.  I see the option to "Autoadd eBook only", but if I understand the docs correctly, that will place copy in the Calibre folder rather than move it.

I have set Calibredb import program and the test button returns the correct version for Calibredb.  I have the Calibre content server running on the same machine as LL.  I have "Use Calibre Content Server" enabled with the URL (for a particular library), ID, and password.  I can log into the content server with the ID and password I created for this from a browser.

I guess I really have 3 questions:
1.  How do I get LL to add it to the Calibre library successfully using the "Calibredb import program" & "Use Calibre Content Server" options?  DO I have everything configured correctly in LL?

2.  How do I get LL to"move" the book to the Calibre books folder.  Thinking I can use "Autoadd eBook only" and then manually delete the dupe in the LL download folder.  Allow Calibre to import and process the book rather than LL.  I then do not need to have the "Calibredb import program" & "Use Calibre Content Server" options configured correct?

3.  LL renames the downloads and sometimes leaves "LL (#########)" at the end of a folder name.  Other times it leaves "(#)".  It appears to number the books when it downloads more than one at a time during eachg authoer search?  Other times neither which is the preferred behavior.  Is this configurable somewhere?

To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
(3f85bbb95755e9c136f317197865d915e965ef9b)
### Operating system used (windows, mac, linux, NAS type)
Windows 10
### Interface in use (default, bookstrap)
Default
### Which api (Goodreads, GoogleBooks, both)
Both
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Zip
### Relevant debug log with api keys and any passwords redacted
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1484636/debug.zip)

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
`   How do I get LL to add it to the Calibre library successfully using the "Calibredb import program" & "Use Calibre Content Server" options? DO I have everything configured correctly in LL?`

A postprocessor run with debug log on would help, should show what we sent to calibre, and what we got as a reply. The "Only add eBook, not opf or jpg" option means we let calibre create the opf and cover, rather than lazylibrarian doing it. Advantage of lazylibrarian doing this is we tell calibre what the filename should be, rather than calibre choosing and telling us. Also some older versions of calibre ignore opf and jpg files and create their own anyway.

 `   How do I get LL to"move" the book to the Calibre books folder. Thinking I can use "Autoadd eBook only" and then manually delete the dupe in the LL download folder. Allow Calibre to import and process the book rather than LL. I then do not need to have the "Calibredb import program" & "Use Calibre Content Server" options configured correct?`

The option to control copy rather than move is "Keep original files"
If using the autoadd folder you don't need calibredb or calibre content server, as calibre monitors that folder for new books, but it does not tell lazylibrarian when it has imported them. Better to use the content server if you can. If you do not set "Keep original files" there should be no dupes left behind, except maybe torrents if you keep seeding.

`    LL renames the downloads and sometimes leaves "LL (#########)" at the end of a folder name. Other times it leaves "(#)". It appears to number the books when it downloads more than one at a time during eachg authoer search? Other times neither which is the preferred behavior. Is this configurable somewhere?`

LL.(number) is an identifier we use to match the torrent/nzb to the book we asked to download. The number is used to link to the author and title in the lazylibrarian database and is normally removed during postprocessing. There are a few cases where it might be kept, eg torrent/nzb downloader didn't tell us the real file name and either "keep original files" is set, or it's a torrent that we want to keep seeding. 
Folder names ending in (number)  without the LL. part are normally calibre folders. Either your calibre content server created them, or they are downloads from somebody that uploaded the book from their calibre library and left the number in, thats quite common. We don't use that number as it relates to the location of the book in their library, not in yours.

**Comment by osuhickeys** [comment]
Hmmmmm...interface says debug log is on and log level is set to 3.  I stopped LL.  Deleted the log, Restarted.  Stopped debug and restarted it.  I see"Debug log ON, loglevel is 3" in the log.  It should  definitely be running this time.  I do not have keep original files checked.  It appears the communication between LL and Calibre is not telling/having Calibre move/copy the download to the Calibre library folder and then removing the LL copy????
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1484883/debug.zip)

It also appears LL is trying to create a new Calibre library or is not recognizing the library name I specified from Calibre.  If the (#) is the book number in the library, they are starting with 1 and I see a new metadata.db file in the LL download folder.  I do not see the book in either the Calibre app of the Calibre library folder.  Guessing I am not using the correct URL for the Calibre Content Server for the library I want them added to.  I copied the one I see in a browser for the Celibre library I want them in minus the "&panel=book_list"

**Comment by philborman** [comment]
Yep, looks like its not recognising the library name. Sadly calibre just returns "Not found", it doesn't say what couldn't be found, but that looks likely.  I think instead of `http://192.168.1.103:7070/#library_id=Calibre_Library`
you just need to put `http://192.168.1.103:7070/#Calibre_Library`
or as that's normally the default name, maybe don't specify the library at all, `http://192.168.1.103:7070`

**Comment by osuhickeys** [comment]
"http://192.168.1.103:7070/#Calibre_Library" did not work, but http://192.168.1.103:7070 worked.  I had that initially, but was getting an error and switched it at some point  I then added a user ID and password to the Content Server and LL config and got further, but did not go back and change that back as one of my tests.  I guess Calibre adds it to what ever library is active at the time the request is sent to the content server.

I do not see a way to set the book cover size on the Calibre side either in the import or content server settings.  I am not seeing it as a configurable option on the LL side ether.  The books sent to the content server by LL have covers about half the size of the ones Calibre generates when you let is do auto tagging.  Is there something I am missing to set the cover size?  Not a big deal to manually update the cover if there is not.  Works pretty well now that I have the right settings in pace.

**Comment by philborman** [comment]
We don't set the size, we just accept whatever cover we were given. For books not downloaded yet we use goodreads/googlebooks. We replace the cover if we get a cover.jpg in the download, or if we download a book with no cover we try librarything and google image search and take the top result. There might be a better way...

You can override the cover in lazylibrarian using the api, or the "manual" book edit option. Nothing as fancy as the calibre cover selector though.

The "http://192.168.1.103:7070/#Calibre_Library" style of library access should work, maybe in a browser try "http://192.168.1.103:7070/#-"  which should get you a list of valid libraries.

**Comment by osuhickeys** [comment]
"http://192.168.1.103:7070/#-" gives me the same as "http://192.168.1.103:7070/".  It shows the 3 libraries I have setup.  I am on Windows and the folders on disk have spaces in the name.  That may be complicating this.  No bid deal that it adds to the one active in the GUI and you can't specify nor is being able to size or auto select a cover.  I use another app to deliver content to mobile devices besides Calibre and LL and it auto sizes the covers for display in a browser.  It has been very reliable.  Calibre Content Server has just been too unstable for me historically.  I really on use it to auto tag things.

Appreciate the help.  Keep up the excellent work.  This project has come an amazing way the past year.
