### ISSUE TITLE
not pulling the right ebook extensions

### ISSUE THREAD

**Issue by pferreira** [DobyTang/LazyLibrarian#1142]
First of all thank you for working to make Lazy Librarian an awesome thing. I know taking on someone else's project and making it your own can be challenging and some times unrewarding because people can be douche bags ;)

I'm not sure I have the right of this so let me explain what I think this is supposed to do, and then if I'm wrong you can tell me !

So in config >> importing under File Formats there is an ebooks: field.  I have epub, mobi, azw in there.  I'm assuming this is telling LL that I want ONLY these extensions.  It is still downloading .htm and .txt and .pdb files.  

Is there a way to have it black list certain releases (sorta like sonarr does it) if they don't meet the extension criteria? It seems to be downloading the same releases over and over and I'm not sure where I can black list them.

Any help is appreciated, thank you.

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 8f26add0ee82fdd862c1853a66c98bd98618cfe7 : Latest Version: 8f26add0ee82fdd862c1853a66c98bd98618cfe7

**Comment by philborman** [comment]
The ebook field sort of works the way you expect, but it's not perfect. When we search for a book we get the list of search results and match them against the book title/authorname and then give a higher priority to titles that contain one of the preferred formats.  Unfortunately many downloads don't give you the format in the title, and you have to download them to find out. It's also possible that a perfect match on title/author without a format can be preferred over a correct format but less good match on the title because of "noise" words. eg "The Hobbit J.R.R. Tolkien"  will be a closer match than "The Hobbit by J.R.R. Tolkien uploaded by AnonyMous  epub". Difficult to get a method that works the way we would like in all cases.

We also use the preferred formats list when a download completes. We search the downloaded files and if we don't find a preferred format we mark the download as failed and try to find another.  The download is blacklisted by putting it in the History table with a Failed status. The search tasks will ignore anything marked failed next time they run, and the importer will only import formats in the list, plus opf and jpg. The rest are left in your download directory with in a folder with .fail on the end in case you want to manually convert them to a preferred format (eg using calibre)

In an ideal world we would be able to look inside the downloaded files before we grab them, rather than relying on the title. Actually in a more ideal world the uploader would always put the format(s) in the title for us, but they don't. Torrents seem particularly bad in that respect. Some of the downloaders allow us to look inside, but not all.

You could always use the "manual search" option for tricky to match titles, so you choose which one to download, not lazylibrarian.  

I will have another think about if and how we can improve it, haven't taken a look at that section of code for a while.

Hope this helps.
