### ISSUE TITLE
List of Magazines is not showing after update

### ISSUE THREAD

**Issue by moiecoute** [DobyTang/LazyLibrarian#1172]
Hi,

I did an update yesterday and today when I logged back in and go into the Magazines section it shows as empty. Curiously if I go into the Config and Filter section I can see them all there. Is there something I can do to fix that?

Thanks in advance
Joseph

**Comment by crypticedge** [comment]
Same issue here, just flushed and reinstalled scratch, wiped out the database since my install was pretty fresh.

Magazines is basically broken entirely - Tried adding a few mags I didn't previously have on there, and first time it added nothing to the log, and didn't show anything in it at all. Second time it says it already exists. 

```
2018-01-08 03:03:45 | DEBUG | webServe.py | addMagazine | 2666 | Magazine living already exists (living)
-- | -- | -- | -- | -- | --
2018-01-08 03:02:30 | DEBUG | webServe.py | addMagazine | 2666 | Magazine fortune already exists (fortune)
```

**Comment by philborman** [comment]
There was a change to the database command used to select magazines for display. We are now using a more complex search command instead of two simpler ones. Working fine here, but not with your system. I suspect maybe different versions of sqlite3 might be the issue?

I will revert the change, but could one of you please send me a debug log using the built-in lazylibrarian log generator. That would show the versions in use and might help with tracking it down. Thanks

**Comment by Code-Slave** [comment]
@philborman  Ill look at this if they post the logs.  i tested this on a few different environments

**Comment by philborman** [comment]
ok that would be great thanks. I tried the new cross join from the command line, and on debian raspberry pi and on ubuntu, new database, one magazine, several magazines. All worked fine. There was a similar issue a while ago using group_concat for a search, only worked on some systems, but it turned out group_concat needs sqlite3 >= 3.5.4  so there is some conditional code to work around that one. Unfortunately I can't reproduce the problem with cross join, works fine for me, I suspect sqlite3 version issues again but need more info.

**Comment by moiecoute** [comment]
philborman and Code-Slave thank you both.

Attached is debug log.
[debug.log](https://github.com/DobyTang/LazyLibrarian/files/1613444/debug.log)

**Comment by moiecoute** [comment]
@philborman and @Code-Slave. I did another update this morning (AU time) and the magazines appeared again. I have not run any updates on my distro and if it helps I have 3.21.0-1 of sqlite. Happy to continue helping you to troubleshoot if you wish or I can get back in touch if it happens again.

**Comment by crypticedge** [comment]
Latest pull fixed this for me as well

**Comment by Code-Slave** [comment]
Yea the change was reverted. So should be good. Ill look at log file and see whats up. Are you running this in a docker or installed. Windows or linux?

**Comment by Code-Slave** [comment]
Thats odd. Youre running 3.21 the same as i am. Would you be willing to run a few command lines to test. Ive run it on debian. Ubuntu mac and windows. Latest updates of course and cant reporduce. I can rewrite with out cross join which may help

**Comment by moiecoute** [comment]
Sure Code-Slave, post what you need and I will return it as quick as I can. I use Antergos VM.

**Comment by philborman** [comment]
So it's not looking like a sqlite3 version issue as I'm on 3.21.0 as well (on my pi) and 3.19.3 on ubuntu linux and all working properly. Not sure where we go from here.

**Comment by Code-Slave** [comment]
Wondering if they had that one release where it was broken before i updated

**Comment by philborman** [comment]
debug log from @moiecoute shows version  b0f8c374 which is behind current, but after the cross join was added.  (the first optimised version didn't use cross join)

**Comment by Code-Slave** [comment]
I just cant replicate this anywhere with crossjoin on.

**Comment by philborman** [comment]
No, me neither. What do we do, put it back in again?

**Comment by moiecoute** [comment]
As a user I’d like to see your product improve and grow. So if you would like I can run certain changes against my computer so you can narrow down what it is. If you have better methods for working out the problem I’m happy to help. I don’t imagine all users were affected otherwise you would got more people containing you or posting in the thread.

**Comment by philborman** [comment]
I think there weren't many users with the problem because it's specific to the magazine section and most are using lazylibrarian for books, and also we reverted the changed code after a few hours, so unless you upgraded during that time window you wouldn't see it.

If you don't mind we could try some test code outside lazylibrarian just using python and sqlite3. If you are interested PM me or email phil.borman@gmail.com and I can put together some test code. Thanks.

**Comment by philborman** [comment]
I agree, would like to try a standalone python script first on a system it was known to fail on, see if we can get the output from both old and new style to see what's different

**Comment by philborman** [comment]
@Code-Slave 
I sent a small test program to @moiecoute and got some interesting results back, I think the magazine select isn't working properly, the problem seems to be if count(i.title) returns zero. In that case there is no output, instead of outputting the results of SELECT m.*  with '0' as the last field.  Any ideas?

#!/usr/bin/env python2
import sqlite3

db = sqlite3.connect('/home/phil/.lazylibrarian/lazylibrarian.db')

print "Test 1, old style"
cursor = db.cursor()
cursor.execute('SELECT title from magazines ORDER by Title')
db.commit()
for item in cursor:
    title = item[0]
    cursor2 = db.cursor()
    cursor2.execute('SELECT COUNT(Title) as counter FROM issues WHERE Title="%s"' % title)
    db.commit()
    for item in cursor2:
        print item[0], title

print "Test 2, new style"
cursor = db.cursor()
cursor.execute('SELECT m.*, COUNT(i.title) AS issue_cnt FROM magazines m CROSS JOIN issues i WHERE (m.title = i.title) GROUP BY m.Title')
db.commit()
for item in cursor:
    print item[9],item[0]

**Comment by philborman** [comment]
Managed to get this working here using  subquery instead of a cross join, waiting on confirmation from a system known to have problems with the cross join version. New select statement is...
'select magazines.*,(select count(title) as counter from issues where magazines.title = issues.title) from magazines order by Title' 
Seems much faster than the original version, though not quite as fast as the cross join style, but at least we get results back with no magazine issues.
