### ISSUE TITLE
UNIQUE constraint failed: authors.Authorname

### ISSUE THREAD

**Issue by LordJay23** [DobyTang/LazyLibrarian#1178]
I've recently started seeing this:

`8-Jan-2018 12:43:46 - DEBUG   :: AUTHORUPDATE : cache.py:get_cached_request:137 : CacheHandler: Returning CACHED r
esponse for https://www.goodreads.com/author/show/15801001.xml?key=ckvsiSDsuqh7omh74ZZ6Q
08-Jan-2018 12:43:46 - DEBUG   :: AUTHORUPDATE : gr.py:get_author_info:298 : [Cour M.] Processing info for authorID
: 15801001
08-Jan-2018 12:43:46 - ERROR   :: AUTHORUPDATE : database.py:action:79 : Database Integrity error: UNIQUE constrain
t failed: authors.AuthorName
08-Jan-2018 12:43:46 - ERROR   :: AUTHORUPDATE : database.py:action:80 : Failed query: [UPDATE authors SET DateAdde
d = ?, AuthorBorn = ?, AuthorLink = ?, AuthorName = ?, AuthorDeath = ?, AuthorImg = ? WHERE AuthorID = ?]
08-Jan-2018 12:43:46 - ERROR   :: AUTHORUPDATE : database.py:action:81 : Failed args: [['2018-01-08', None, 'https:
//www.goodreads.com/author/show/15801001.Cour_M_', 'Cour M.', None, 'https://s.gr-assets.com/assets/nophoto/user/u_
200x266-e183445fd1a1b5cc7075bb1cf7043306.png', u'15801001']]
08-Jan-2018 12:43:46 - ERROR   :: AUTHORUPDATE : importer.py:addAuthorToDB:305 : Unhandled exception in addAuthorTo
DB: Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/importer.py", line 162, in add
AuthorToDB
    myDB.upsert("authors", newValueDict, controlValueDict)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/database.py", line 124, in ups
ert
    self.action(query, valueDict.values() + keyDict.values())
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/database.py", line 48, in acti
on
    sqlResult = self.connection.execute(query, args)
IntegrityError: UNIQUE constraint failed: authors.AuthorName
`

If I'm not mistaken, wasn't AuthorName a non UNIQUE field?

**Comment by philborman** [comment]
No, I checked back with the itsmeg branch this was forked from, AuthorName always been unique. AuthorID wasn't originally unique, but was made unique at least a year ago. Looks like you might have another Cour M. under a different authorid.  I'm not sure why AuthorName is unique, could conceivably have more than one author with the same name. Makes it difficult to work out who to attribute the books to if the name isn't unique, especially if using googlebooks, maybe that's why. Not sure what's best to do about this situation, the code is failing when it tries to insert a second Cour M. under a different authorid to the first one. Don't really want to merge different authorids into one, any suggestions?

**Comment by philborman** [comment]
One option is to make the table unique on (authorname, authorid) as a pair?  Shouldn't break anything, I think.

**Comment by Code-Slave** [comment]
Name and ID as unique would not break anything. Thats actually a better way as its entirely possible to have duplicate names in authors

**Comment by philborman** [comment]
I think I have found a simple solution for the current problem, will push it in an hour or two. The better fix of making (name and id) unique is not as simple as it first looked. There are parts of the code that currently rely on a one-to-one mapping between name and id.
