### ISSUE TITLE
LazyLibrarian, NZBGet Rockons on Rockstor NAS not working

### ISSUE THREAD

**Issue by kysdaddy** [DobyTang/LazyLibrarian#1179]
Current Version: b0f8c37401c1c88fc21c0e657c8a095346e7764c 
Rockstore Linux: 4.10.6-1.el7.elrepo.x86_64
bookstrap
(Goodreads, GoogleBooks, both)
### Source of your LazyLibrarian installation Rockstor Rockon
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1613152/debug.zip)

Hello,
I am a total rookie at this and seem to be having a similar issue but it could be operator malfunction on my part.
I have been able to get LazyLibrarian Docker/Rockon working on a Rockstor NAS using the Transmission Docker/Rockon on the same machine but I have failed to get LazyLibrarian to use the NZBGet Docker/Rockon on the same machine. Any suggestions on where to start trouble shooting? NZBGet works I can drag and drop and properly catagorize the files download and extract to the correct share.
When I use the test NZBGet button in Lazy Librarian states "NZBget connection successful"

Thanks for any help you might provide.
Chas

**Comment by philborman** [comment]
Debug log was useful. Seems the problem is not nzbget, but your nzb providers.
The log shows...
https://nzbgeek.info/ is BLOCKED
but doesn't say why as it was blocked before this section of log started. A previous call to nzbgeek.info returned an error so we block them for an hour (it's usually too many requests, or over your daily allowance)  nzbgeek changed their api address a while ago, try https://api.nzbgeek.info  instead

The log also shows...
Unable to get capabilities for http://www.nzbindex.nl/api?t=caps&apikey=<redacted> No data returned
Either a bad api key (though usually you get a message saying so) or a communication issue talking to nzbindex.nl  I tried nzbindex.nl from here and got no response either, but I don't have an api key for them so that may be normal. Some sites will give you their caps (capabilities) without an api key, some give you a "missing/invalid api key" message, some just ignore you

**Comment by kysdaddy** [comment]
Perhaps I am just not getting the API key correct. I have added another provider 6box.me
they show under my account that Your credentials should be provided as 
?apikey=c******************************* yet when I search using LL the log shows " https://6box.me - Incorrect user credentials" How can this be, I'm not usually this incompetent.

Grrr.



[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1616549/debug.zip)

**Comment by philborman** [comment]
We fill in the ?apikey= part for you, just put the api key itself in lazylibrarian config (the c*********** part)

**Comment by kysdaddy** [comment]
Philborman, thank you!!

I think that it is working. I am sorry for my lack of understanding.
Thank you again

**Comment by philborman** [comment]
No problem, glad you got it sorted
