### ISSUE TITLE
Cover creation program None setting issue

### ISSUE THREAD

**Issue by phairplay** [DobyTang/LazyLibrarian#1186]
Hi,
I've set Cover creation program to None yet when downloading Magazines I'm still getting opf files. is there any way to resolve this?

also is it possible to have post process run as soon as the file has downloaded?

many thanks

**Comment by philborman** [comment]
The "create cover" switch just stops covers being created, not opf files. I could add that easily enough. Are there any situations where you might want a cover but not an opf or vice-versa, if so we would need a separate switch.

The postprocessor runs as a task every n minutes because we have no way of knowing when a download has completed. We start a postprocessor whenever a book/mag is sent to a downloader, and run every n minutes until there are no more books/mags listed as snatched. The interval is configurable in the processing page, Post-Processing Interval:  default is 15 minutes. Should be safe enough to set it to a lower value, but not zero as that disables the automatic task leaving just manual postprocessing.

**Comment by phairplay** [comment]
hi for magazines on my set up there is no need for the opf files.
i have lazylib send the magazines to a folder i can access via chunky comics, i read then delete. an option to not have the opf would be great.

thank you for this information it‘s very helpful

**Comment by philborman** [comment]
Config option for magazine opf should be in the next version, probably tomorrow. Default is ON (so we don't break existing users) you can turn it off in config, then save config to make it permanent

**Comment by phairplay** [comment]
Amazing many thanks
