### ISSUE TITLE
Unable to get capabilities error

### ISSUE THREAD

**Issue by phairplay** [DobyTang/LazyLibrarian#1246]
hi 
i keep seeing the following error when searching 

Unable to get capabilities for https://mydomain.com/nzbhydra/api?t=caps: No data returned

and it will state No nzb providers are available. Check config and blocklist
yet it still seems to search

is there anything i can do to remove it?

**Comment by philborman** [comment]
Try with debug logging on, should show why nzbhydra didn't return any data.
Either it's not running, or mydomain.com is wrong, or maybe nzbhydra doesn't like https for it's api, though that's unlikely.  Also check you are on current lazylibrarian version as there were some changes to capabilities requests recently.

**Comment by phairplay** [comment]
hi i'm on the latest version from yesterday and here is the debug log

this error started a couple of weeks ago and i was hoping the updates that have been coming through would
[debug.log](https://github.com/DobyTang/LazyLibrarian/files/1772500/debug.log)
 resolve it

**Comment by philborman** [comment]
ok thanks for the log. 
Problem seems to be we expect to get an error back from nzbhydra as we query capabilities without providing an api key first, and then if we get an "unauthorized" error we retry with the api key.

This was a fairly recent change, as you have noticed.
Some providers require an api key even for listing capabilities, but most will provide the capabilities without. The specs say capabilites should not require an api key, which is why we try that first. Some providers throw an error if you supply an apikey.

Seems your version of nzbhydra is not returning an error that we recognise, and we assume it passed but gave us no data back.

Can you try entering  https://mydomain.com/nzbhydra/api?t=caps  in a browser bar and see what you get back. If I try it here I get 401 Unauthorized

**Comment by phairplay** [comment]
hi this is what i get

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" code="100" description="Wrong api key"/>

**Comment by philborman** [comment]
Ok thanks, so nzbhydra is returning xml and no error. I get error and html response
Will take a bit of working round. Wonder why it changed.
What version of nzbhydra are you on?  I'm on 0.2.232 here

**Comment by phairplay** [comment]
I’m on nzbhydra 2 1.4.4

**Comment by philborman** [comment]
Ah ok, haven't tried nzbhydra2 yet.
I have added a quick check for xml with a message about missing or wrong api key, will push an update shortly. Can you check and report back. Thanks.

**Comment by phairplay** [comment]
Awesome thank you for the Quick response 

I’ll report back ASAP

**Comment by phairplay** [comment]
Many thanks again for the quick response and fix.

No errors at all 👍

**Comment by philborman** [comment]
No problem,
I will check with theotherp (nzbhydra developer) and make sure the error message doesn't change
