### ISSUE TITLE
If git call fails, LL shows a "you're running a local version" popup that won't go away

### ISSUE THREAD

**Issue by claym** [DobyTang/LazyLibrarian#1248]
If your machine has run out of calls to github (i've got a bunch of apps that check for updates) it returns a 403 error, and Librarian shows a "You're running a local version" popup.

Would be better if it didn't do that :)

Running latest (1e09a53a0a043dc30a61500d1700228c1d56a457)

Ubuntu in a docker container.

**Comment by philborman** [comment]
We seem to have a lot of problems with the git version checking code, it seems quite complicated and probably doesn't need to be. I will take a look at how others do it. The current code is based on a fork of headphones a few years ago. Might be a better option somewhere else we can copy.

We use the 'If-Modified-Since' header if it's set, so most of our calls to git don't count towards your query limits. Might be worth checking if your config has a valid timestamp for "git_updated"

Having said that, the "local changes" message is generated by git if you don't have a commit hash that it recognises. Maybe your hash is wrong, or your repo/branch are wrong?

**Comment by philborman** [comment]
ok ,think we should catch the 403 error now, and I added an "Ignore" button to the popup that stops it nagging for 24 hours.
