### ISSUE TITLE
Feature Request: Don't search for magazine issues that LL already has

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1284]
Feature Request: Don't search for magazine issues that LL already has.

When I go to back issues for some magazines there may be hundreds of issues, and I don't know which ones I already have or don't.

Either don't search for the issues I have, or 'mark' those that I have in the past issues tab.

**Comment by philborman** [comment]
Past issues table is discarded before each new search, it gets unmanageably large otherwise, so we can't mark ones you have unless we do it on each scan. Also when we search we just search on title, not on issue dates as there are too many different date formats in use for the same magazine, so probably we can't improve on the current setup.

**Comment by MrMxyzptlk** [comment]
Is there a way that LL could check for a mag issue that I have as you add it to the past issues table?
Have an additional column on the the past issue table that shows I have that issue?
That shouldn't be too much data, and maybe make that feature an option in the config, because I'm sure it slow it down just a bit, and some may not want that.

Is all that doable?

**Comment by philborman** [comment]
Had a look and it's not that hard to do. We can set the status in pastissues to "Skipped" or "Have" and then select status in the dropdown.

**Comment by MrMxyzptlk** [comment]
That's a beautiful thing! Thanks again!
