### ISSUE TITLE
Magazine Date Parser Too Strict?

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1286]
Magazine Date Parser Too Strict?

Here is an example searching for "Dezine", but this happens all the time with all of my magazines.
Is there something I can do in my config? Or would this be on your end?
I know magazines having varying ways of 'Dating' an issue such as: 1/1/2020, 1-2020, #5, July, Issue 4, etc...
Maybe have a set of rules per mag, kind of like the filters where we can manually choose in a drop down, which date style the mag uses?

Magazine Date Parser Too Strict?

2018-03-28 14:33:49 | DEBUG | SEARCHMAG | searchmag.py | search_magazines | 256 | Magazine title matched Dezine for Dezine Magazine Issue 02 2017
-- | -- | -- | -- | -- | -- | --
2018-03-28 14:33:49 | DEBUG | SEARCHMAG | searchmag.py | search_magazines | 399 | Added Dezine.Magazine-Issue.03.2017 to pastissues marked Skipped
2018-03-28 14:33:49 | DEBUG | SEARCHMAG | searchmag.py | search_magazines | 338 | Magazine Dezine Magazine Issue 03 2017 failed: Expecting a date
2018-03-28 14:33:49 | DEBUG | SEARCHMAG | searchmag.py | search_magazines | 288 | Issue 0 (regex 4) for Dezine Magazine Issue 03 2017
2018-03-28 14:33:49 | DEBUG | SEARCHMAG | searchmag.py | search_magazines | 277 | Bookid: dezine
2018-03-28 14:33:49 | DEBUG | SEARCHMAG | searchmag.py | search_magazines | 276 | Title: dezine magazine issue 03 2017
2018-03-28 14:33:49 | DEBUG | SEARCHMAG | searchmag.py | search_magazines | 275 | Reject: [u'mp4', u'mkv']

**Comment by philborman** [comment]
We allow all sorts of date formats, and try to work out what issue they refer to, so we should be able to detect that 01-01-2018 and Jan 2018 are referring to the same issue. The problem is where issues have a number rather than a date. In your example, is Dezine Magazine Issue 03 2017  the third issue of 2017 or the March issue.  We assume that if it says "Issue n"  then n is an issue number, not a month (same with Nr, No, Vol, Volume).  This gets even more complicated if we already have issues of that magazine that appear to have a proper date, as we expect all issues of that magazine to be date based, so we then reject Issue 03 as it's not a date. I think this is what you are seeing here, you have earlier issues of Dezine that have a date.  Maybe we should  add an extra check and allow numbers 01 to 12 to be a month if we are expecting a date?  Normally we just reject that issue and look for one that is definitely a date

**Comment by MrMxyzptlk** [comment]
That is a possibility, or much like Sonarr, you can choose whether a series is standard or daily.
If there was an option to manually change and 'lock in' what a issue or magazine used that would also work?

**Comment by philborman** [comment]
It's not so much what an issue uses, but what the people uploading the magazine choose to call it. Some will upload "Issue 03 2018", someone else for the same issue might put "Vol 3 2018" or worst case just "03 2018" where we can't tell if it's a number or a month. Lots of those around, sadly.

**Comment by MrMxyzptlk** [comment]
OK, well back to the threads title...maybe a way to make the parser less picky about dates for an individual search? Yes the number 01 - 12 would probably help as well.

**Comment by philborman** [comment]
Ok, just added some code to allow converting an issue number to a date providing the magazine title has a year in it. Should solve most of the mismatches, and the rest go into pastissues and can be manually corrected.

**Comment by MrMxyzptlk** [comment]
Excellent! Thanks...
