### ISSUE TITLE
WARNING	Error from isbnlib: an HTTP error has ocurred ((503) Service Unavailable

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1292]
WARNING	Error from isbnlib: an HTTP error has ocurred ((503) Service Unavailable

Author refresh is giving this error for ALL authors.

**Comment by philborman** [comment]
Not fatal, isbnlib is only one source of info. It's been removed in the latest version anyway ;-)

**Comment by MrMxyzptlk** [comment]
Awesome!

So as you know, I switched over to the philborman/LazyLibrarian git fork for my DB upgrade...how do I switch back, but keep my upgrade / settings?

**Comment by philborman** [comment]
I just posted the new release on dobytang a few minutes ago.
If you want to avoid the full database rebuild again, don't use the internal upgrade on your dobytang fork. Go into the dobytang folder and use git pull to upgrade the files to current version, then copy your lazylibrarian.db file from my fork to the dobytang one and restart it.  The code will realise the database is upgraded and won't do it again.  Actually there is a very small additional upgrade since the one you have, but takes so little time you probably won't notice it.  Do not copy your config.ini across as that points to my fork so the version numbers don't match. Just copy the database. If you want to save a little more time, copy the cache files across too, though they will eventually re-sync themselves if you don't.
