### ISSUE TITLE
Delay for direct searches?

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1319]
In manually using Library Genesis, I have found that the most items I can have simultaneously downloading is 3.   Any other efforts beyond that will get a 503 Service Unavailable Error.

Download time for each item is variable.   A 10MB file may take a few seconds but it might take a couple of minutes for a 250k.  Or the other way around.

Sometimes I receive a 504 Gateway Timeout Error and the file will not download successfully.  When I see this, I can refresh and it often will download.   Sometimes it will not work successfully for 15 minutes before  I move on to something else.

LL might not be able to manage all the details of the downloading process but it would be nice to have a variable time between searches.   There probably is but I don't see if on the web interface or in the config.ini file.   I would probably set this to 60 seconds between searches to limit the number of simultaneous downloads.

**Comment by philborman** [comment]
If we get a 503 or 504 error from a provider we add the provider to a blocklist for an hour so we don't try to use it in any more searches for a while. You should see lines like this in the log...
Blocking provider %s for %s minutes because %s
The blocklist is in config -> providers there is a button at the end of the page to show and optionally clear the blocklist. Blocklist timer is only in the config file, default is 3600 seconds. Zero to disable blocklist.

This will mean any searches during that time won't use that provider, and if you can't find the book anywhere else the provider will come back on line later and the next scheduled search should use it.

Achieves the same thing, but without having to delay any searches with other providers.
