### ISSUE TITLE
Unhandled exception in libraryScan: Traceback (most recent call last): File "C:\LazyLibrarian\lazylibrarian\librarysync.py", line 673, in LibraryScan while surname[1] in '. ': IndexError: string index out of range

### ISSUE THREAD

**Issue by Gamethrall** [DobyTang/LazyLibrarian#1325]
LazyLibrarian version number: 970158524cf7f0028e075b7374dd86b30c94d23b
Operating system used: Windows 10
Interface in use (default, bookstrap)
Which API: Goodreads
Source of your LazyLibrarian installation: git

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1916342/debug.zip)

I was trying to add audiobooks to my LazyLibrarian library with Library Scan. I had placed the files in the directory specified for my library of audiobooks.

**Comment by philborman** [comment]
Well that's interesting, you seem to have an audiobook with an authorname of [                              ]
Hadn't expected that, should be treated as unknown I guess.
Will push a fix shortly, but it might mean we can't import that audiobook since we don't know the authorname

**Comment by philborman** [comment]
Unfortunately there are lots of "artist" type tags in mp3 files. 
Consensus for audiobooks seemed to be...
"composer" is the author
"performer" is the narrator
or if composer is blank then "performer" is the author as well as narrator
I have no idea which fields the windows columns "contributing artist" and "album artist" map to.
Lazylibrarian uses a library called TinyTag to extract the info, we can query more fields, but since audiobooks don't have dedicated tags we are a bit stuck if files don't follow the same convention.

**Comment by philborman** [comment]
I have added some code in the next version to check the "albumartist" tag and use that if both composer and performer are blank. Should get around the problem. No idea which tag "contributing artist" is

**Comment by Gamethrall** [comment]
Thanks. 
I'l pull later tonight and let you know what happens.
