### ISSUE TITLE
Freenas setup

### ISSUE THREAD

**Issue by resiproxy** [DobyTang/LazyLibrarian#1354]
Hi everyone,

Just wondering if anyone has successfully installed lazy librarian in a jail?

I tried the built in plugin but it does not find anything for me. I then found some forum that showed how to upgrade to this version. I did it and then got errors on starting the service for some upgrade issue (believe an SSL issue). Went into the main py script and commented out the upgrade part. Launched successfully but then I get some database exceptions.

I also tried doing a manual build through a blank jail which led to it saying sqlite3 is not installed even though I know it was.

I clearly suck at this.

**Comment by BongoEADGC6** [comment]
I've had the same problem. Not just you. It'd be nice to have an install guide for this instance.

**Comment by BongoEADGC6** [comment]
It's an issue with python and TLS 1.0. GitHub uses TLS 1.2 now and the version of python installed by the plug-in doesn't provide that and throws an error on startup when running versioncheck.py. This is during the procedure where your checking GitHub for a newer version of the application.

I've also tried to build it from scratch without the plug-in but FreeNAS jails are out of date to begin with and using iocage instead of the regular jail manager it's up to date and the planned feature moving forward in BSD.

**Comment by philborman** [comment]
Ah right, thanks.
In recent versions of lazylibrarian you can disable the update check by setting versioncheck_interval=0 in lazylibrarian config.ini, this might help, but won't get around the TLS 1.2 requirement for github.
I guess the real answer is to use a newer python. Lazylibrarian is now compatible with python2 and python3, maybe python3 might be a way forward?

**Comment by resiproxy** [comment]
Actually got it to work just took a bit of googling. Believe installing it In a iocage vs a jail solved alot of issues. I'll look Into it more once I am home from vacation
