### ISSUE TITLE
Feature Request / Bug Fix??? Mags deletion, stay on particular mag after deletion.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1356]
Feature Request / Bug Fix??? Mags deletion, stay on particular mag after deletion.

The mag deletion fix is working well, but after I delete a few issues, rather than staying on the screen with that mags issues, it goes to the list of all magazines.

Is there a way 'to stay put', after I click delete some of the issues?

**Comment by philborman** [comment]
There isn't a way at present. Could be added though. Would need to add code to check there are still some issues left. At the moment you can delete all issues and the directories get removed if empty, so we jump to main magazines page for safety rather than check if we're still ok to stay on the same page.
