### ISSUE TITLE
New category "extra" or "unmatched"

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1383]
How I understand things work when LL does an ebook scan:

Step 1: books on disk are matched against existing database (and probably GoodReads/Google)

Step 2: if a book is matched, it's switched to "Open" regardless of what category (Wanted, Skipped, Ignored, etc.) it had before (which I think is right behavior)

OR: if a book is not matched, LL does not show it (as far as I know)

So I would take the disk title of each file or directory one level below the author that isn't matched and add it as category "Extra" or "Unmatched" or something similar.   

Because I'm still using Calibre, duplicate formats has not shown as an issue for me.   Maybe LL handles that if you're just using it for library organization but it seems like people might manually move things into directories.

For the same format, it would be nice if that could be indicated as the problem but probably not necessary.   The preferred format would be taken from the ebooks Formats on the Importing tab, then the second preferred, etc.  For me, .mobi is first, followed by .epub, .pdf, etc.

**Comment by philborman** [comment]
Step 1, yes as you guessed. If author isn't in the database, add them. If author is there but book isn't, try to get details from goodreads/googlebooks

Step 2, yes that's correct

If  book isn't matched we didn't find a database entry for it, so we currently just ignore it. This might be because of a difference in the book title that fails the fuzzy logic, or might be that goodreads/googlebooks don't know about the book, or have it under a different author.

Not too keen on the idea of creating fake database entries for these books, probably best to just report it in the logs and leave for manual intervention.

Default format choice for the "Open" button is to open the left-most book type in the preferred formats list.  If you have user accounts enabled then each user can set their own preferred format to override that, eg if a user has a kindle they can prefer mobi even if epub is the leftmost default.

**Comment by dkids** [comment]
That seems to be working fine.   Thank you.
