### ISSUE TITLE
Do ebook scan when author added 

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1389]
If I add an author manually (go to home screen, search for author, add them) or do it via importing a csv file LL is not checking for existing books by the author.  I have to do a manual ebook scan.

**Comment by philborman** [comment]
This is intentional, but only a default setting. csv files are "booklists" rather than "authorlists" eg the New York Times Best Fiction of 2017 you probably only want the books in the list, not every book by every author in the list. Same if you add an author manually, you can choose which books you want to download, not necessarily their whole back-catalog. You can override the default setting in lazylibrarian config processing tab by setting `New Authors Book Status` and `Include other books by new authors `
