### ISSUE TITLE
Handling Incorrect Search Results

### ISSUE THREAD

**Issue by LeeThompson** [DobyTang/LazyLibrarian#1451]
Unfortunately the "scene" is overall completely incompetent when it comes to labeling releases, they are especially bad with books.

So with ebooks and AudioBooks sometimes what LL finds isn't the right book (or is in the wrong language, etc).  

Unfortunately there doesn't seem to be a way (unlike SickRage, Watcher3, Sonarr, etc) to tell LL not to try that download again (someone mentioned the 'manual' button but that just brings up a metadata editor?) so I end up in a loop where it just keeps grabbing the same bad copy over and over.

(Also if nzbget has a problem, LL seems to keep it at 0% in history - I'm not sure if that's a nzbget issue or a LL issue.     I usually click 'Clear Snatched" when that happens although sometimes it ends up trying that download again as well.)

(I also wish LL wouldn't rename the downloads, it makes it hard to manually locate what it actually found on the indexer to diagnose issues.   I know it needs to add the ID to it, maybe append instead of re-write?)

**Comment by philborman** [comment]
If you leave a download in the history list, lazylibrarian can be told not to try the same one again using settings in config->importing tab, blacklist downloads in history table.  Default is not to retry failed ones, but you can tell it not to retry others. Flexible in case the failure was temporary and a retry might work.

The manual button pops up the metadata editor as you saw, but also at the top of the editor page are manual search options so you can select the download you want, which will be applied to the book you were manually editing at the time. 

For any downloaders with problems the progress is kept at 0% until the timeout set in config->processing  Remove failed task after x hours. On timeout we tell nzbget to remove the task and we search for another source.  It's feasible to trap the nzbget failure before the timeout, but I think sab (and others) will retry if it's a temporary failure. Not sure if nzbget does. Also sometimes an unpack error can be fixed within sab instead of cancelling.

LL renames downloads from torrents as the torrent provider often gives a different name to the search result. For usenet we could append the id instead of rename, but I think from memory the rename only happens if the download succeeds as part of the import process. I would have to check.

**Comment by LeeThompson** [comment]
Thanks, that's a bit more clear.   I don't use bittorrent on at all so I'm not sure why the renaming is so important.    The NZBs passed tot he downloader are definitely being renamed.

**Comment by philborman** [comment]
I had a quick look at that section, the rename happens much earlier in the process than it needs to, it's getting renamed when the list of results from providers is collated, before we choose which download to grab. I will change this so we append the bookid rather than a full rename, and only rename the one we want rather than renaming every search result. The rename is so we can identify the file arriving in the download directory and associate it with the book we asked for, just appending the bookid should be enough.

**Comment by philborman** [comment]
Changed the rename code so we keep the original name until postprocessing. Also added a popup in the history table that gives info on the download, and allows you to delete or mark as failed. Similar to the popup info on sonarr etc. Should be in the next release, probably tomorrow.
