### ISSUE TITLE
Items stuck in "snatched" status, and never processed

### ISSUE THREAD

**Issue by kevinpawsey** [DobyTang/LazyLibrarian#1484]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Current Version: ed55f7e6304bd746db35d478ba9d813111bbdac1 : Latest Version: ed55f7e6304bd746db35d478ba9d813111bbdac1
### Operating system used (windows, mac, linux, NAS type)
Ubuntu 17.10, fully updated
### Interface in use (default, bookstrap)
bookstrap
### Which api (Goodreads, GoogleBooks, both)
both
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git
### Relevant debug log with api keys and any passwords redacted
[attached debug.zip to this ticket]

I think that the issue is with downloads that have sub-folders.

In the debug there are a few snatched that are not working... I have narrowed these down to be because of the fact that they are ebooks, and the 'download' was over the threshold set in the config, however, it turns out that there is just multiple versions of the same ebook (is there a way of filtering files with extensions before downloading?).

The one that has definitely got audiobooks in it is Lemony Snicket... This is all of the audiobooks in subfolders in the download.  I have checked and they are definitely there, and in MP3 format.

I am not sure how you can deal with 'bundle' downloads... I guess that is going to cause issues with knowing which books are which inside the download?

Let me know if you need anything else.
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2137034/debug.zip)

update: just thought I would check out the item that it matched it agains, and it looks like it matched the multiple-download bundle to the name of a single book:
**A Series of Unfortunate Events. Lemony Snicket
The Unauthorized Autobiography
GoogleBooks  Manual**
matched to
**Lemony Snicket - A Series of Unfortunate Events** torrent download
Darn... and it was such a good download too... all the books in one download :/

**Comment by philborman** [comment]
There are a few "no ebook found" entries in the postprocessor, 
Skipping /SABnzbd/complete/SABnzbd/magazines/Riordan, Rick - The Sword of Summer- Magnus Chase and the Gods of Asgard, Book One (Unabridged), folder is empty
Skipping /SABnzbd/complete/SABnzbd/magazines/Johanna Lindsey El Camino Del Amor rtf, no ebook found  ( you don't have rtf as a valid file type )
Skipping /SABnzbd/complete/SABnzbd/magazines/Johanna Lindsey Corazones En Llamas doc, no ebook found ( you don't have doc either )
ebook_type = mobi, azw, prc, txt, pdf, epub, azw3

You can set rtf and doc as reject words in lazylibrarian config to stop downloading these, but the danger is you will reject archives that contain mobi, epub, rtf in the same download. Not an issue with libgen, as there is only one book per download, but torrents and usenet could contain several versions in the same archive (and often do). Maybe need to rewrite the code so we still accept the archive if it contains something we want, rather than reject because it contains something we don't want.  It's tricky. If the download contains ebook and audiobook but we only want the ebook, should we reject the whole thing and try another download - saves a lot of bandwidth if we do. 

Bundles are a problem, we think there isn't an audiobook found for Lemony Snickett, there clearly is, but it's in a subdirectory. We don't want to match the bundle to a single book, so rejecting is probably ok, leave for manual processing. Maybe we could make the code smarter to extract and match a single subdirectory from the bundle, but if we reject and retry we might be able to get a single book download.

**Comment by kevinpawsey** [comment]
Sorry to dig this one up... but what about items in history that seem to be stuck at 100%?  I have a few of those, and they don't seem to want to get to the processing stage... is there a way of seeing what is up with these?

**Comment by philborman** [comment]
Any update on this, or is it resolved now?

**Comment by philborman** [comment]
Closed due to inactivity

**Comment by kevinpawsey** [comment]
So sorry Phil,  I don’t think I have seen this issue any more… I meant to come back and close the issue.  Thanks again for your help 😊
