### ISSUE TITLE
CBZ files?

### ISSUE THREAD

**Issue by barbequesauce** [DobyTang/LazyLibrarian#1485]
Using LL commit ed55f7e6304bd746db35d478ba9d813111bbdac1 on Raspbian Jessie with Bookstrap and Goodreads. Installed from git.

My son asked me for "Mighty Jack and the Goblin King" by Ben Hatke. No problem, found it via MaM/Jackett and downloaded it.

The file is delivered as cbz. When pp'ing, it gets unzipped and then there's an odd message saying that the file was not a file or directory? I'm very confused...

```
26-Jun-2018 16:53:11 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:556 : Skipping unhandled file Mighty Jack and the Goblin King - Ben Hatke (Mighty Jack 02) (2017) (Digital) (FingerScans).cbz
26-Jun-2018 16:53:11 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:594 : /mnt/sda/completed/books/Mighty Jack and the Goblin King - Ben Hatke (Mighty Jack 02) (2017) (Digital) (FingerScans).cbz is not a file or a directory?
```

Debug attached. 
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2139057/debug.zip)

**Comment by philborman** [comment]
Yes, the message is wrong. It basically means we tried to unpack the archive and failed, (cbz are zip archives) and what we were left with was not a file or a directory (because we failed to unpack it). Will fix it in next release, but unfortunately I'm out of action for a few days waiting for a new raspberry pi as mine has overheated and died.

**Comment by philborman** [comment]
Should be fixed in latest release, probably later today, just a bit more testing
