### ISSUE TITLE
DelugeVPN & Post Processing Troubles (Audiobooks)

### ISSUE THREAD

**Issue by bmilcs** [DobyTang/LazyLibrarian#1505]
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2196043/debug.zip)
Repo: https://github.com/dobytang/lazylibrarian : Branch: master : Updated: Sat Jul 14 16:35:00 2018
Current Version: d5728f1c49c1151c7aacda65416d2460be528088 : Latest Version: d5728f1c49c1151c7aacda65416d2460be528088

Unraid OS
Docker, linuxserver/lazylibrarian
BookStrap
Goodreads,  default

1) Anytime I change a setting, add an author, title, etc., I am redirected to: Unable to connect... can’t establish a connection to the server at 127.0.0.1:5299". This is a different URL than the one I use to connect to it. Not sure why this occurs.

2) I finally was able to get DelugeVPN to somewhat communicate with LL. I also enabled Black Hole Dir. as a fail safe. Magnet links were giving me trouble, so I checked Convert into Torrent files. For whatever reason, this always fails and unchecks it on it's own.

At this point, LL is successfully searching my Indexer API's via Dockers that handle all the searching. They return results and downloading is then passed to them. However, LL is unable to detect anything from Deluge once the dl is passed. Status of each Audiobook remains "Matched". Forcing Post Processing results in... 

2018-07-15 15:02:31 | INFO | 0 books/mags processed.
-- | -- | --
INFO | Nothing marked as snatched. Stopping postprocessor.
-- | --

Not sure what's going on. 

I'm now clearly having issues with DelugeUI, and receiving the magnet links. Sorry if my description is horrible. I've been struggling with this for a few weeks now and spent many hours trying to get it working right.

;----------------------------------------------------------------------------------------------------------------------------;

Also, Black Hole is successfully snatching the magnet links and placing them in the correct folder. My last installation was picking them up in Deluge but marking them as .invalid.

Edit: They are being downloaded via Black Hole and sitting in Deluge. No post processing or anything aftward... not being recognized as snatched.

**Comment by philborman** [comment]
1. url change, I have seen something similar with using nginx as a transparent proxy, if the lazylibrarian cherrypy server and the proxy don't talk to each other properly the url gets reset to 127.0.0.1
Try unticking your setting for http_proxy, if you are using nginx as a transparent proxy it is not needed and makes cherrypy think the requests come from localhost. Only seen the issue with nginx, but could happen with other transparent proxies I guess.

2. Magnet links - to convert magnet to torrent we need a library called libtorrent, if this is not available the button gets un-ticked, see the lazylibarian wiki Config_Downloaders page

3. Not getting recognised as "Snatched" - you have lines in the log saying  Deluge: Response was None
so we are not talking to deluge correctly. You can enable more verbose debug logging of deluge communication by setting debug level to 16
Might give more info on why LL and Deluge are not communicating.
Have you tried using the deluge daemon directly, bypassing the webui? Might give different results?
The postprocessor only processes "Snatched" files, ie ones correctly sent to downloaders. "Matched" means we found a result we wanted, but the downloader hasn't told us it's downloading. This is because of the failed communication between LL and deluge. Blackhole isn't really much use unfortunately, as we can't talk to it, and we don't know which downloader is monitoring the blackhole so we can query it. The blackhole is likely to get removed from LL at some point.
