### ISSUE TITLE
OPDS error in moon+ reader

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#1595]
All current release.

when i hit the opds server from moon+ reader (android) it says
"there appears to be no syle information associated" and dumps raw xml.

**Comment by philborman** [comment]
Yes, not all opds readers are compatible. Can't find out why, they don't give enough info to know what the problem is. LazyLibrarian opds works fine with aldiko on android if that helps!

**Comment by philborman** [comment]
Ok, there are two competing standards for opds feeds,  rss2.0 and atom1.0
Our opds is rss2 but moon reader needs atom1, aldiko can do both. 
Looks fairly easy to make ours atom1, maybe make it configable?
It looks like just a html page edit, might try tomorrow.

**Comment by barbequesauce** [comment]
Out of curiosity where did you find this bit of information?

**Comment by philborman** [comment]
http://www.intertwingly.net/wiki/pie/Rss20AndAtom10Compared#major

**Comment by philborman** [comment]
It was relative links that were causing the issue. Fixed in latest release.
Do you have the PRO version of moon+ reader? The free one doesn't support images so I wasn't able to test that part, no book or magazine covers.

**Comment by Code-Slave** [comment]
yea i have the pro. thats why i didnt use alk as i didnt want to pay for another reader :) will test today

**Comment by Code-Slave** [comment]
Same issue and result.

**Comment by Code-Slave** [comment]
I deleted old entry and readded and works fine. Looks like it was caching. Thanks

**Comment by Code-Slave** [comment]
Spoke too soon. No images are displaying for covers

**Comment by philborman** [comment]
Working ok here apart from covers, which I assumed was because I'm not running the pro version. Can you try turning off opds authentication and see if that makes covers work, there are reports that some opds readers only send auth for the feeds, not covers or searches. The screenshot you posted looks correct, the details are as expected so need to figure out what's different between your setup and mine. Maybe if you could post the results from http://192.168.1.200:8301/opds?cmd=RecentBooks  which should show if we're generating the right links to books and images, and can you post a debug log of the opds trying a download, as it's working here. The error message might narrow down where to look.

**Comment by Code-Slave** [comment]
Ok, I rushed testing a little. The book i was trying to dl was marked as there in LL but wasnt really. I tried other books and they came down fine. Auth is definitely off 

in ios Marvin, images show fine. In moonreader+pro images sow in calibre fine. Im looking at the xml in calibre vs ll opds

**Comment by philborman** [comment]
Looks like moon+ doesn't use the "image" link, it needs the "thumbnail" link instead.

**Comment by Code-Slave** [comment]
all good now. thanks
