### ISSUE TITLE
LazyLibrarian update remains at 84 commits behind

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#1633]
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2495517/debug.zip)

Hi

So I did a recent update to LL which was about 24 commits behind. That seemed to work okay then I saw an update that was 84 commits behind which threw me slightly.

So I've updated LL 4 times now and each time I can see the mismatch between current and latest version and I continue to get the update prompt.

Debug log attached.

**Comment by philborman** [comment]
Your debug log shows you haven't successfully updated since Oct 5th, which matches the version code you are on. 84 commits behind sounds a lot, but it's probably correct, there have been a lot of changes in the last 2 weeks. 

Not sure why the update isn't happening, the log shows a "Performing update" message then nothing afterwards. Looks like you're running in a NAS, can you log into it, cd to the lazylibrarian directory `/volume1/@appstore/lazylibrarian/var/LazyLibrarian/` and try `git pull` from there.
If that doesn't do the upgrade it should tell us why not.

**Comment by sukhysall** [comment]
Hi

So did the Git Pull and it worked!!

Didn't see any messages that indicated any errors though. Thanks @philborman .

Closing issue.
