### ISSUE TITLE
Error in update and search

### ISSUE THREAD

**Issue by hrxfab** [DobyTang/LazyLibrarian#1668]
Hi, 

I have the following error on my LazyLibrarian version : 45d4f24da214507c6913bde47efe063688d6bb84
it's running on a Syno DS918+ with the latest version of  DSM 6.2.1-23824 Update 6

Here the error message:
Unhandled exception in libraryScan: Traceback (most recent call last): File "/volume1/@appstore/lazylibrarian/var/LazyLibrarian/lazylibrarian/librarysync.py", line 775, in LibraryScan GR_ID.find_book(gr_id) File "/volume1/@appstore/lazylibrarian/var/LazyLibrarian/lazylibrarian/gr.py", line 1160, in find_book bookdesc = get_book_desc(isbn=bookisbn, author=authorname, title=bookname) File "/volume1/@appstore/lazylibrarian/var/LazyLibrarian/lazylibrarian/bookwork.py", line 820, in get_book_desc if lazylibrarian.CONFIG['GB_COUNTRY'] and len(lazylibrarian.CONFIG['GB_COUNTRY'] == 2): TypeError: object of type 'bool' has no len() 

What I don't get, the config is looking for GB, while I configured it for FR

Regards
Fabien

**Comment by philborman** [comment]
GB in this case is GoogleBooks
The bug was fixed a while ago but the synology package is not upgrading properly, it needs to move over to the new code on gitlab. We are aware of the problem but have not had time to investigate how to create a new synology package. If you are OK using the command line you can force the update manually,  the necessary commands are in https://gitlab.com/LazyLibrarian/LazyLibrarian/issues/1685
