### ISSUE TITLE
Import externally downloaded e-books

### ISSUE THREAD

**Issue by arogl** [DobyTang/LazyLibrarian#190]
Currently the only way to import books is if LL has downloaded them, or I can add them manually to my library and then force a rescan of my library.

is there a possibility of adding the parsing library code to the post processing code if books are names in a certain pattern?

Or am I doing something wrong?

**Comment by philborman** [comment]
Looking at the postprocessing code it seems you can, but it's not straightforward. 
There is a naming pattern, as you guessed...

If you download a book manually, put it in a folder in the lazylibrarian download directory.
The folder name should contain   LL.(12345)  where 12345 is the lazylibrarian bookID for the book.
eg   ebook_downloads/some_book_title_LL.(283948)/some_book.mobi

If LL tries to download the book itself, it keeps track of the bookID and looks for it arriving. 
If you do it yourself you need to know the bookID or LL doesn't know where to put it.

**Comment by arogl** [comment]
@philborman thanks for the feedback, I was hoping to avoid the book id, but will give it a go.

**Comment by philborman** [comment]
If you are adding this into LL there are some built-in  functions that might help...

In librarysync.py, get_book_info will get author and title from an epub or mobi
then find_book_in_db will give you the bookID
In postprocess.py, import_book will handle the moving the files and putting into the library structure based on the bookID

**Comment by philborman** [comment]
ok, I have added import from alternate folder. Current restrictions: 
only one title is looked for in the folder
no subdirectory scanning
source folder is deleted (actually the folder and its contents are moved into the library and renamed) 
if you dont want the source folder deleting, set  DESTINATION_COPY = 1 and it will copy rather than move.

wasn't too hard to do, should be in the next release after a bit more testing

**Comment by philborman** [comment]
oh, and the author/book already need to be in the library, or it will generate a warning
