### ISSUE TITLE
Show all logs, misses one line

### ISSUE THREAD

**Issue by nigelhooper** [DobyTang/LazyLibrarian#196]
I have spotted a trivial error on the logs page:

I am looking at the log page and have "Show All lines per page" set.  If I scroll to the bottom of the page it say "Showing 1 to 88 of 89 lines".

Based on the numbers and what I can see, I think I have:
1 Error
6 Warnings
82 Info

If I click on the "Level" column header the error entry disappears.

If I click "Level" again, the entries are sorted as:
Error
Info
Warning

Presumably this is sorting alphanumerically.  In my mind it makes sense to sort them by priority i.e. High to Low: Error -> Warning -> Info
Low to High: Info -> Warning -> Error

Apologies if I am being too pedantic, but I have been staring at the log page a lot recently.

**Comment by philborman** [comment]
The "Showing 1 to 88 of 89 lines" is a miss-count, I think. If you switch to 100 lines per page it will say
"Showing 1 to 89 of 89 lines", not that it helps much, but might narrow down where the error is.

I guess its in the js files somewhere but they look very frightening to me as i have never worked with js
Hopefully someone else can step in and fix it.

**Comment by philborman** [comment]
Just had a quick look at "Headphones", which a lot of LL code is based on, not that it helps.
They have the same issue with log priority being alphabetic, and they get around the "All" miscount by disabling "All" and only allowing 10,25,50,100  ;-))

We need a js programmer. Also for the log filtering you suggested. Personally I just use grep on the debug logfiles, but it would be nice to include it in the program.

**Comment by theguardian** [comment]
Both Headphones and LL use DataTables plugin to display logs - https://www.datatables.net/

The version for datatables has been updated since either app originally included this functionality. I recently made very similar changes to update to the latest in another app.

Check here for how I coded logs.html:
https://github.com/theguardian/CherryStrap/blob/master/static/interfaces/bootstrap/logs.html

And here for how I coded the python api endpoint starting around line 197 (similar code currently exists in WebServe.py in LL:
https://github.com/theguardian/CherryStrap/blob/master/cherrystrap/apiServe.py

I'd copy and paste all of this over myself, but am on travel for a while.

**Comment by philborman** [comment]
Thanks for that,  I will have a look and see if I can get my head around
it.  Struggling with porting LL to python 3 at the moment as I run on
ubuntu which is dropping python2 support in april.

Nearly there,  just can't get SimpleCache to work,  most of the rest was
easy enough.  Might just drop it and roll my own as it looks like overkill
anyway .

At least I'm enjoying the challenge

**Comment by philborman** [comment]
ok, fixed the mis-count. It was in webServe.py where it does the string slicing.
To display "All" it passed length of -1, so rows = filtered[start:(start+length)]
missed the last line by slicing [0:-1]

**Comment by philborman** [comment]
Can this be closed now?
