### ISSUE TITLE
[Question] How to add books I have?

### ISSUE THREAD

**Issue by tymanthius** [DobyTang/LazyLibrarian#234]
I'm probably blind, but every time I try to import books I already have (all in subdirs under /media/books, but can be sorted oddly), it errors out saying 'search_dir' not configred.

But I can't find where to configure that.

**Comment by philborman** [comment]
Is this on a library scan, or are you importing the books one by one?

**Comment by tymanthius** [comment]
The err I get on import.  But it's not finding any of my books.

**Comment by philborman** [comment]
Libraryscan should automatically import as long as the authors/books are in goodreads database (or googlebooks if you've configured that)
a debug log might be useful.

**Comment by tymanthius** [comment]
Ah . . . didn't know I had to configure goodroods/google.  I thought it would just pull from meta.

**Comment by philborman** [comment]
It needs to get author details,  and a list of all books the author has
written,  so you can easily grab other books by them

**Comment by tymanthius** [comment]
That helped some.  It picked up ONE book.  ;)  I'm also getting this error in the webUI logs:

2016-01-14 14:40:40	ERROR	Unable to complete the scan: 'ascii' codec can't decode byte 0xe2 in position 11: ordinal not in range(128)

**Comment by philborman** [comment]
The message "'ascii' codec can't decode byte 0xe2"  could be a problem. 
Are you on a current version, as a lot of these have been trapped recently.
The most likely reason is an  author or book with accented characters in the name, 0xe2 is a letter a with circumflex accent.  These should all be trapped and converted to a plain 'a' in places where necessary, seems there's more work needed. In order to track it down, could you post a few log lines just before the error so I can (hopefully) work out where it is coming from. Thanks

**Comment by tymanthius** [comment]
After restart, it's no longer doing it. So I think it's trapped properly, but my config wasn't ready.

**Comment by philborman** [comment]
Thanks for confirming it's fixed. Can you close the issue now (I can't as you opened it)

**Comment by tymanthius** [comment]
Sure thing!
