### ISSUE TITLE
QUESTION: How exactly do you import books?

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#271]
So I know you declare the folder name in the "Alternate Import/Export Folder" of where you want LL to look for books you want to import. so question is:

1. Does each book need to be in a seperate folder within the import folder?

2. Is there a naming convention for the book? (e.g. "author - title", "title - author" etc.) so LL understands what it is? Or does LL go away and do a Goodreads/Googlebooks  search or something?
 
Thanks :)

**Comment by philborman** [comment]
The idea is to let you import a book that you already have,  rather than get LL to download another copy. 
Can also be useful for merging authors together where LL and/or goodreads/Googlebooks disagree on author names.  (eg James Lovelock and James E. Lovelock are the same author, and you want to list all the books under one name ) 

We really need to get some documentation done,  or a wiki. 

You need to put one book at a time into the folder to import it. The folder is treated like the result of a torrent or nzb download,  only has one book in it,  maybe a metadata file, maybe a cover image,  can be deleted after import 

LL reads metadata embedded in the book and uses that for author and title. No naming convention except file extension.  Metadata needs to end in opf, book can end with anything you have set in ebook filetypes in config (if you provide an opf) . If there's no opf the book must be epub or mobi as we can't extract metadata from anything else 

LL then looks the author up in goodreads and adds them to the database (if not already there) 
and imports the book. 

At the end of all this,  if the import succeeded  LL will delete the folder unless "keep original file" is set in config.

**Comment by ayefly** [comment]
Thats what I have found by trial and error.  i have /lazy/import, putting my whole calibre library in there (each author in its own folder) doesnt work.  I have to put an individual file in, import it, recreate the import folder after its deleted, copy another book into it, and repeat.

**Comment by philborman** [comment]
To import a whole calibre library in one go, just put your calibre library path as base destination folder,
eg /media/Phil/Books/Calibre Library/
and do a library scan from the "Authors" page. Pulls them all in at once. Can take a while first time, as it loads all your authors, and a list of all their books (whether you have the book or not).

**Comment by ayefly** [comment]
lol, I did that, and made the mistake of having "add new books as wanted" selected in settings.  I then had over 20000 books in the wanted section!  What I do now when adding a new author is disable add new as wanted, add new author, re-enable add new as wanted, then go back and add which books I want.  

That way it automatically add doesnt add EVERY book, but new ones since I added them.  

Does anyone know if Goodreads lists the authors publications more detailed?  for example, right now LL shows everything with their name.  It would be nice to be able to select just first edition new book vs paperback vs compilation/readers digest version.  in Headphones you can sort out official album releases vs compilations and such.(actually made finding Alice in Chains Unplugged hard, since it didnt consider it an official album) I was wondering if goodreads provides enough sorting to do the same.

**Comment by philborman** [comment]
No, goodreads isn't that helpful in that respect, just gives the title, not whether paperback/hardback etc.
Google books gives a bit more info, but still not enough. 

I normally run with "add new books as skipped", so haven't come across the massive wanted list problem. If we get around to documentation that definitely needs mentioning!
I suppose you could easily delete the whole "wanted" list en-mass from the "manage" page.

**Comment by philborman** [comment]
Maybe we could have a "preferred words" list, an opposite of the "reject words" list
where you prefer to download a version with one of those words in the title (if there is one) and fall back to just matching the title if there isn't

**Comment by ayefly** [comment]
I thought about that, but most releases I have seen just have name and author, plus extra info like audiobook or ARC or something.  Having a preferred word list would just affect searches, not what's added to the author's book list on their page in LL.

**Comment by philborman** [comment]
Yes, true. I haven't looked at the feasibility, just wondering aloud really.
If the releases don't include the info we can't really do anything.

**Comment by philborman** [comment]
Can you mark this thread closed now?
