### ISSUE TITLE
Slow default interface with a large number of Authors and Books

### ISSUE THREAD

**Issue by arogl** [DobyTang/LazyLibrarian#287]
Is there a way to improve the speed of the interface?

By default it loads all authors and books by default and then hides the non-visible authors/books, wouldn't it be quicker to load the number of books/authors as per the drop down (and remember that number)?

This has the draw back of not being able to use the filter but with 6,000+ books in the library it takes about 44 seconds to load and then shows 10 books. It only loads 12 Mb locally so something else needs to be slowing this down.

For 2,675 Authors it loads 39Kb in 6 seconds.

**Comment by philborman** [comment]
The main slug is downloading the book cover images from google. Could probably cache them now we have a better-working cache. Might speed it up enough. Otherwise would need a fairly major rewrite of the display code to only show 10 (or whatever) at a time as we pass a whole array to the display code and let that sort out what to show.

**Comment by philborman** [comment]
Well, caching the book images helps a little, but still slow. On my library local cache reduces the page display time from 45 seconds to 30.
Turning covers off makes a dramatic improvement, down to 5 seconds. Maybe that's the way forward, offer a "with covers" switch in the config.
