### ISSUE TITLE
Magazines with multiple words in title can't download international versions

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#371]
Magazines with multiple words in title can't download international versions.
LL will download the international versions and put them in the 'main' version.
If I have magazine with a title (2 words), "My Magazine" and then create another "My Magazine India", it will find magazines from the US and India but it will download and post process them all to "My Magazine", instead of putting the Indian version in the correct 'folder'. Single word magazine titles work perfectly. I.E. "Magazine" and "Magazine India".

**Comment by philborman** [comment]
Yes, thought we might hit this sort of problem at some point. The problem is the way we match magazine titles against torrent/nzb names, so it only happens if the name of one magazine you want is a subset of another magazine you want, ie "my magazine" is a subset of "my magazine india". 

We just look at the torrent/nzb name to see if it contains something that looks like a valid date, and the magazine name is in there somewhere. Additional "noise" words are ignored because you get additional information in the torrent-nzb names like "hqpdf" or "emag" or "India" 
You see the problem, which words are "noise" and which should cause a "reject"
Ideally each magazine would have an individual "reject words" list, and there is sort-of provision in the database structure for it, but nothing has ever been added to LL code to make it work.
 
In your example you would need a "reject list" for "My Magazine" containing  "India"
and no reject list for "My Magazine India" which would then work as you expect it to, each magazine into the correct folder.

I am unavailable for a few more days, but will have a think about it and try to implement something when I get back.
