### ISSUE TITLE
More 500 Error

### ISSUE THREAD

**Issue by perezbalen** [DobyTang/LazyLibrarian#402]
Hi

Sorry, more 500 errors:

When I uncheck Launch browser, and save, I get a:
```

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Applications/LazyLibrarian/cherrypy/_cprequest.py", line 638, in respond
    self.body.process()
  File "/Applications/LazyLibrarian/cherrypy/_cpreqbody.py", line 934, in process
    key = key.encode('ISO-8859-1')
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2019' in position 41: ordinal not in range(256)

Powered by CherryPy 3.2.0 
```

Branch: master Current Version: c57a034ca10d4de3bcbca1c1a41db85cf28d5fc2 :
 Latest Version: c57a034ca10d4de3bcbca1c1a41db85cf28d5fc2

**Comment by philborman** [comment]
This could be hard to trace, would need a bit more info please. Unchecking launch browser is a red herring, I think.

It looks like we are failing to write out config.ini because there is a rogue character in one of the variables. The character is \u2019 (curly left single quote) '
We have code in there to strip them out before saving, but it seems not to be working for you. The rogue character is either in a variable we don't expect (so don't check) or is not being stripped out from one we do check. Can you have a look at your config.ini and see which variable might contain curly left single quote?

**Comment by philborman** [comment]
Just had another look, the other place the curly quote could be is in a magazine title or a magazine reject list as these are also checked in the same "save config" routine

**Comment by perezbalen** [comment]
It was a magazine title. I deleted the magazine and it's solved. It was using \u2019 as an apostrophe in the word Collector's

**Comment by philborman** [comment]
Ah fine.  I will put extra code in to trap that.
Thanks for your help.
