### ISSUE TITLE
Issue: "Remove" option does not work (assuming it works the way I think)

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#437]
Version: 8af16232e032af9b3857e5da299ad1bed9d9a5c7 

First off @philborman thanks for the quick fix to the ignored issue. 

So I've seen the "Remove" and "Delete" options and read the wiki to confirm. If I understand it correctly, remove will remove a book from an authors list of books so it's no longer visible on LL.

If my understanding is correct, then "Remove" does not work.

I had an author Aziz Ansari (Comedian I know but he wrote a book) and Aziz has 1 actual book and 3 audiobooks. I set the audiobooks to skipped when I checked the goodreads link; and when I saw the "remove" option tonight, I decided to try it on all 3 audiobook entries. 

Unfortunately, nothing happened and all 3 audiobook entries are still listed as 'skipped'. 

I ran debug prior to doing this and I got the following logfile:

Timestamp	Level	Message
2016-08-23 22:24:19	INFO	Status set to Skipped for "Intimate Moments for a Sensual Evening"
2016-08-23 22:24:19	INFO	Status set to Skipped for "Dangerously Delicious"
2016-08-23 22:24:19	INFO	Status set to Skipped for "Buried Alive"

Thanks

**Comment by philborman** [comment]
Yes, it doesn't seem to work the way I think it should either ;-)
The code looks like it checks whether the author still exists in the database, and if so it marks the books as "skipped" instead of deleting them. The only reason I can think of  is if you rescan the library later, or refresh the author, it would put a new entry in for the books you deleted.
That would cause them to be downloaded again if you have "new book status" set to "wanted".

It makes more sense to mark them as "Ignored" so they don't appear in the lists, but a new entry doesn't get created either. What do you think?  We could hit the same issue with deleting books from the disc, we should probably not remove the database entries then either, just hide them.
