### ISSUE TITLE
Magazine label

### ISSUE THREAD

**Issue by perezbalen** [DobyTang/LazyLibrarian#462]
I don't think this is an Issue, but could not figure out where to ask. Is there a way to label magazines differently than books so that NZBget can process them differently? 
(also I can't seem to get the Magazine Destination Folder to work. Magazines are treated as books. Is there any documentation?)

**Comment by philborman** [comment]
It's documented in the wiki config page.
There is currently no way to separate out magazines for nzbget or the other downloaders, the 'book' label is used for both. This is because the same postprocessor handles both books and magazines, ie anything with the 'book' label is processed by LazyLibrarian. Magazines are treated as books, you can think of the magazine title being like an authorname, and the issues are different books by that "author". You can either keep the downloaded magazine structure inside the book library by using a folder name starting with underscore (eg _Magazines) , or entirely separate by giving a full path (eg /home/phil/Documents/Magazines). The reason for the underscore is so the book libraryscan routine knows to skip that directory.

**Comment by perezbalen** [comment]
Thanks. I checked the documentation, and followed as best I could. Yet when I download a Magazine, it's placing it on the Base Destination Folder instead of the Magazine Destination Folder. What am I doing wrong?

These are my processing settings (on OS X):
```
Base Destination Folder: /Users/me/_Media/_AutoDownloads/_BooksDone/
Alternate Import/Export Folder: (empty)
eBook Destination Folder: $Author/$Title
eBook Destination File: $Title - $Author
Keep original files (unchecked)
Calibredb import program: /Applications/calibre.app/Contents/MacOS/calibredb (which is not importing for some reason, but that's an issue for another day)
Calibre Auto Add: (empty -though tried it with the BaseDestinationFolder and there is no difference)
Magazine Destination Folder: /Users/me/_Media/_AutoDownloads/_Magazines/
Magazine Destination File: $Title - $IssueDate
Magazines inside book folder Current limitation: (unchecked)
```

Thanks.

**Comment by philborman** [comment]
Can you try it changing Magazine Destination Folder to
Magazine Destination Folder: /Users/me/_Media/_AutoDownloads/_Magazines/$Title/$IssueDate
I think it might be breaking the "unique folder" limitation, though another possibility is that lazylibrarian thinks this magazine is a book??  . Anything in the debug log that might help?
I will add some more debug messages to identify what LL is doing

**Comment by perezbalen** [comment]
NZBget has the DestDir for the books category as:
`/Users/me/_Media/_AutoDownloads/_BooksDone/`

I changed LazyLibrarian to this:
```
Base Destination Folder: /Users/me/_Media/_AutoDownloads/_BooksDone/_AutoAdd/
Magazine Destination Folder: /Users/me/_Media/_AutoDownloads/_Magazines/$Title/$IssueDate
```

Yet I still get all magazines on `/Users/me/_Media/_AutoDownloads/_BooksDone/` (The NZBget DestDir)

The only strange warning on the log is: 
`Download dir not found, books will be downloaded to /Applications/LazyLibrarian`
But I don't get why wouldn't it find the Download Dir.

**Comment by philborman** [comment]
Ah - that's the problem. You have told NZBGet to put books into
/Users/me/_Media/_AutoDownloads/_BooksDone/   but  lazylibrarian is looking
for them in /Applications/LazyLibrarian because of the "Download dir not
found" error

You need to also put /Users/me/_Media/_AutoDownloads/_BooksDone/  into
Download Directory (at the end of config "Downloaders" page)

The lazylibrarian postprocessor looks in this directory for new downloads,
and processes any it finds, moving them into the book or magazine folders
as appropriate

**Comment by perezbalen** [comment]
Thanks. Think that did it.
