### ISSUE TITLE
Provider Error on Search

### ISSUE THREAD

**Issue by Meridiian** [DobyTang/LazyLibrarian#475]
I am getting the following error with this provider "https://api.dognzb.cr - Incorrect parameter". the address is correct as is my API. I only get the error with this provider and not with the other two I use.

Also I can connect to that provider through NZBGet and Sonarr which are on the same machine.

**Comment by Meridiian** [comment]
Tried this again just now with debugging on and it has now started parsing OK, I still have no idea why it wasn't connecting before as I know the server was online.

**Comment by philborman** [comment]
That error usually means you are trying a "book" search on a provider 
that doesn't understand "book" as a valid search type. Some providers 
use "books" instead, and some don't understand books at all so we have 
to do a "general" search. The "book" search passes author and book_title 
as parameters.

The error goes away because when we detect the "incorrect parameter" 
message, we disable "book" search on that provider in future searches.

It's not disabled permanently, only for the duration of your "cache 
expiry" setting, so you may get it appearing again from time to time. 
You can disable permanently on the config screen under "categories" if 
you wish.

We don't permanently disable by default just in case the provider 
updates their capabilities.
