### ISSUE TITLE
LazyLibrarian not popping up update window

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#483]
LazyLibrarian not popping up update window, even though a version check shows it is 21 changes behind.
It was working on updates a week or so ago.

I run this as a windows service, and normally stop the service, and start it via the .py when I know there is an update. This no longer works either?

**Comment by philborman** [comment]
There have been some changes to the update system recently, not sure which version you are running. The update pop-up was disabled in a couple of releases because of packaging issues, but it is back now.
To force an update without using the popup, run the .py file with --update   eg...
python LazyLibrarian.py --update
or if your version is earlier and does not have the --update option, 
if you are running a git install you can use git pull to update

**Comment by MrMxyzptlk** [comment]
Thank you!

I couldn't get the update to work or .git as I didn't install this as a git repository.
I had to download the files and manually put them in the directory.

**Comment by philborman** [comment]
ok, may be your version was too early and didn't have the --update option.
It does now. We are moving towards having ready-built packages available,
and the idea is we won't offer the update popup on the ready-built
packages, just a different popup telling you there is an update available.
You should then use your package manager to upgrade to the new version.
Some package managers don't like you messing about replacing files that
they manage.
