### ISSUE TITLE
Docker and image cache folder

### ISSUE THREAD

**Issue by sparklyballs** [DobyTang/LazyLibrarian#498]
Hi, i'm a member of linuxserver.io 
https://www.linuxserver.io/
http://tools.linuxserver.io/dockers

and we've recently made a docker of your version of lazylibrarian.

We've hit a snag, part of our ethos is easy user mapping of volumes for data persistence and the image cache being in data/images/cache is bit of a problem.
we're preloading the config.ini file to put the rest of the data and config files in /config and was wondering if you could see your way to either making the image cache folder configurable or in the same tree as the rest of the data , ie somewhere in /config.

thanks.

**Comment by philborman** [comment]
Sorry,  I don't know how to do that. I would prefer the cached images in
user config with the database and config.ini, but cherrypy will only load
the images if they are in the data/images tree.

I'm not sure if I tried symlinks from user config, probably did, but would
they only work for linux anyway?

If you have an answer I'm more than happy to change it,  always keen to
learn!

Kind regards Phil

**Comment by sparklyballs** [comment]
i'm not sure tbh, something to do with pillow perhaps ?

**Comment by philborman** [comment]
I think it's more than likely to be the cherrypy config.  I will have a
play over the next day or two and let you know.

**Comment by sparklyballs** [comment]
excellent, thank you.

If you're not averse to the idea, would you consider adding our docker as an install option.
we are the docker install option for quite a few apps at present, from couchpotato, sickrage and hellowlol's fork of htpcmanager to plexpy.

**Comment by sparklyballs** [comment]
related as well, a command line switch to select the config folder location could be a boon as well, if that's not swamping you with requests...

**Comment by philborman** [comment]
There is already a command line switch for that, well two options...
--datadir  for a folder to put config.ini, lazylibrarian.db and cache (if I can get it working)
--config  for a full path to a config file if you want it somewhere else, or a different name, eg /home/me/lazylibrarian.config

What do I need to do for a docker install?

**Comment by sparklyballs** [comment]
my bad, lol. so there is and we're using it.

as for docker install, depends what OS, linux of some flavour is preferable.

best source of information for that is here, https://docs.docker.com/engine/installation/

once you have a working setup, follow the readme here https://github.com/linuxserver/docker-lazylibrarian/blob/master/README.md to create a container, and then issue docker start <container-name>

**Comment by philborman** [comment]
ok I'll have a play once I've looked at the cache issue.
I'm running on ubuntu 16.04 (at least until Thursday) on my laptop, and my
media server is a raspberry pi running osmc

**Comment by maxcore** [comment]
i love docker! great news

**Comment by philborman** [comment]
Image cache now moved into datadir with the database and config.ini
Added code to migrate existing image caches across. Can take a while if there are a lot of images to move, so added a "database is updating" monitor page too.

Might get a chance to look at docker over the next few days.

**Comment by CHBMB** [comment]
Thanks for this... Awesome news.

**Comment by sparklyballs** [comment]
@philborman , CHBMB is another linuxserver.io team member and the maintainer on our docker for this.

and thanks from me too.

**Comment by philborman** [comment]
ok, it's probably me doing something stupid, but I don't seem to be able to
get this to work.
I've set up the docker engine, and followed the instructions on
https://github.com/linuxserver/docker-lazylibrarian/blob/master/README.md
to create the container, giving it my existing datadir which contains the
config, database, cache and a log directory.  This is what I get as
output...

IOError: [Errno 2] No such file or directory:
u'/home/phil/.lazylibrarian/Logs/lazylibrarian.log'
Traceback (most recent call last):
  File "/app/lazylibrarian/LazyLibrarian.py", line 207, in <module>
/home/phil/.lazylibrarian/Logs : Unable to create folder for logs. Only
logging to console.

Lazylibrarian data directory is /home/phil/.lazylibrarian/  passed to
docker as -v /home/phil/.lazylibrarian:/config
Permissions are rw-rw-rw on all the files/directories in
/home/phil/.lazylibrarian/
Docker can read the config file in that directory, can read/write the
database in that directory, but doesn't think the Logs subdirectory exists
(os.path.exists returns False) so tries to create it and fails.

What am I missing?



On Fri, 14 Oct 2016 at 19:40 sparklyballs <notifications@github.com> wrote:

@philborman <https://github.com/philborman> , CHBMB is another
linuxserver.io team member and the maintainer on our docker for this.

and thanks from me too.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/498#issuecomment-253870344>,
or mute the thread

**Comment by philborman** [comment]
@sparklyballs 
Another lazylibrarian user has lazylibrarian in one docker, and calibre in another docker. Is there any way the lazylibrarian docker can use the calibre program in the other docker? They are sharing the same library folder.  If this is not possible, would it be possible to create a single docker containing both lazylibrarian and calibre? Or install calibre in the running lazylibrarian docker?
Thanks.

**Comment by CHBMB** [comment]
@philborman I don't think we'd recommend making "combined" containers, also Calibre is a GUI app so it would massively increase the size of the LL container.
