### ISSUE TITLE
error 500 "not an absolute path"

### ISSUE THREAD

**Issue by WzL** [DobyTang/LazyLibrarian#518]
When books are downloaded they're placed in $DATADIR (/opt/lazylibrarian) which is the lazylibrarian root. When using the LazyLibrarian webpage, selecting an author, then choosing an available title I select under "Status" the green "OPEN" button.

The following message appears:

`500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/lazylibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/lazylibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/lazylibrarian/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/lazylibrarian/lazylibrarian/webServe.py", line 931, in openBook
    return serve_file(bookfile, "application/x-download", "attachment")
  File "/opt/lazylibrarian/cherrypy/lib/static.py", line 48, in serve_file
    raise ValueError(msg)
ValueError: 'Jaap Bilaap/Lief Hondje/Lief hondje- Jaap Bilaap.epub' is not an absolute path.

Where can i define the static path where the ebooks are stored?
`

**Comment by philborman** [comment]
The books are downloaded to the directory set in the Config Downloaders tab.
Postprocessing moves them into the library "Base Destination Folder" set in
the Config Processing tab.

I think if these are not defined they default to lazylibrarian datadir
(probably generating a warning at startup?)
but it seems the database entry doesn't include the base directory, which
it should.
I will look into this and push a fix in a day or two.
It's recommended to put the books/magazines/config.ini/database into a user
directory rather than lazylibrarian root for ease of upgrades. For now, I
suggest you create a library folder, fill in the directories in config,
save config, move the books into the library folder, then run LibraryScan
from the authors page. This will recreate the links so the "open" buttons
work and future downloads will be ok.

Example (assuming linux)

mkdir /home/me/eBook_Library
mkdir /home/me/Downloads
in config downloaders tab, set Directory: /home/me/Downloads
in config processing tab, set Base Destination Folder:
/home/me/eBook_Library
in config processing tab, tick "Full Scan" so we remove the database
entries for "missing" books
save config

mv "Jaap Bilaap" /home/me/eBook_Library
(same for any other authors)

in LazyLibrarian, Authors page, click "LibraryScan" and wait....

**Comment by philborman** [comment]
Should be fixed in latest release. Does not move existing books though, use LibraryScan to repair database links
