### ISSUE TITLE
Manually adding magazines

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#575]
Is there a good method for manually adding issues of a magazine?

**Comment by philborman** [comment]
Not sure exactly what you're wanting.

When you add a magazine to the database it will grab "recent" issues.

You can select older issues to download from the "past issues" tab after
the magazine search completes, but the past issues table gets removed every
time you search for magazines or it gets too large and slow.

The concept of what's recent is a bit variable. If the magazines have a
month in the title it will reject any earlier than the previous month (ie
at the moment it will reject November 2016 and before). Because magazines
are sometimes forward-dated you might end up downloading
December,January,February. If the magazines only have an issue number,
rather than a date, lazylibrarian will download any that it can find as we
can't (easily) tell the age. Sometimes magazines have an issue number and a
year, in which case we can stop at issues more than 1 year old (eg now we
would reject 2015 and before)

If you want to add magazine issues that you've already downloaded, just put
them in the right magazine directory named as if lazylibrarian downloaded
them, and run "library scan" from the magazine page. It will pick them up
and add covers where needed.

**Comment by DarkSir23** [comment]
Yeah, that's exactly what I wanted.  Does the naming of the magazine file matter, or does it just need to be in a properly named directory?

**Comment by philborman** [comment]
I think it just needs the directory names to be right. it looks for any
.pdf file in each subdirectory if I remember correctly, but wouldn't harm
to do both.
