### ISSUE TITLE
Bug with Torznab URL parsing (I think!)

### ISSUE THREAD

**Issue by georgeurbane** [DobyTang/LazyLibrarian#593]
The URLs being returned from Torznab (via Jackett) have an ampersand in them that I think isn't being handled properly as encoded in the URL.

I see the URLs being returned in the log - which are correct(ish).  In the URL returned in XML there's a `&amp;file=` in the middle that is just &file= in jackett's UI (and works).  

Let me know if you need more info.

The error from the log is:
`Unhandled exception in search_nzb_book: Traceback (most recent call last): File "/opt/LazyLibrarian/lazylibrarian/searchnzb.py", line 89, in search_nzb_book found = processResultList(resultlist, book, "book") File "/opt/LazyLibrarian/lazylibrarian/searchnzb.py", line 213, in processResultList snatch = TORDownloadMethod(newValueDict["BookID"], newValueDict["NZBtitle"], controlValueDict["NZBurl"]) File "/opt/LazyLibrarian/lazylibrarian/searchtorrents.py", line 324, in TORDownloadMethod response = urllib2.urlopen(request, timeout=90) File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) File "/usr/lib64/python2.7/urllib2.py", line 423, in open protocol = req.get_type() File "/usr/lib64/python2.7/urllib2.py", line 285, in get_type raise ValueError, "unknown url type: %s" % self.__original ValueError: unknown url type: 148`

**Comment by philborman** [comment]
Haven't tried Jackett for a long while, had a lot of problems with it as different versions produced different results, then they dropped most of their free providers. I'm using Cardigann for torznab which seems to work fine and is stable.

Looks like the problem here is the url encoding. There is code in lazylibrarian to try and separate out the bit of the result we need, and it's expecting &file=  but the xml from jackett is giving us &amp;file=
Shouldn't be too hard to fix ;-)

**Comment by philborman** [comment]
Just pushed an upgrade that should hopefully fix it. Could you try it and report back as I can't get torznab to  work at all here. No usable providers. Thanks.

**Comment by georgeurbane** [comment]
Thanks for looking at it, still unhappy - though on (some) different lines now.  With regard to Jackett, I can certainly try Cardigann instead (and I actually think that Jackett is now loading modules from Cardigann anyway...) - is the XML output from Cardigann different?

`Unhandled exception in search_nzb_book: Traceback (most recent call last): File "/opt/LazyLibrarian/lazylibrarian/searchnzb.py", line 89, in search_nzb_book found = processResultList(resultlist, book, "book") File "/opt/LazyLibrarian/lazylibrarian/searchnzb.py", line 213, in processResultList snatch = TORDownloadMethod(newValueDict["BookID"], newValueDict["NZBtitle"], controlValueDict["NZBurl"]) File "/opt/LazyLibrarian/lazylibrarian/searchtorrents.py", line 328, in TORDownloadMethod response = urllib2.urlopen(request, timeout=90) File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) File "/usr/lib64/python2.7/urllib2.py", line 423, in open protocol = req.get_type() File "/usr/lib64/python2.7/urllib2.py", line 285, in get_type raise ValueError, "unknown url type: %s" % self.__original ValueError: unknown url type: 148`

**Comment by philborman** [comment]
Well, cardigann works for me, your experience might be different. Depends
on the sources as much as the converter.
The error above is exactly the same as before, so probably it's not the
&amp; conversion at all.

I think we might need a bit more info. Are you able to do a bit of light
editing of searchtorrents.py, or I can send you a version with extra
debugging code in?

**Comment by georgeurbane** [comment]
Yes to either/both.  Certainly happy to make edits - am borderline capable.  I turned debug logging back on and took another look, finding something interesting:

> 10-Jan-2017 19:59:28 - DEBUG :: SEARCHNZB : [NewzNabPlus] - result fields from NZB are {'bookid': u'AWi4DAEACAAJ', 'nzbmode': 'torznab', 'nzbdate': 'Sun, 30 Oct 2016 05:55:39 -0400', 'nzbtitle': 'Livia Lone by Barry Eisler', 'nzbsize': '495820', 'nzburl': '148', 'nzbprov': u'http://127.0.0.1:9117/jackett/

that nzburl result is the same thing I assumed was the error number in the previous logs - but now I think it's actually what is being returned for the URL.  I went and looked at the XML being returned by Jackett, and there is a field called "grabs" being returned, which, wait for it, is 148.  

The correct link is being returned in <link></link> tags though.

**Comment by philborman** [comment]
Right,  that looks like the problem. Seems we are getting a non standard
response from the provider. Which provider is it,  do they have a free
account i can try? Or can you send me the full xml output?

It seems they send an extra "grabs"  field in the response which is
throwing the decoder. I  could strip that out but can't test it,  and they
may send other extra fields too.

On Wed, 11 Jan 2017, 02:14 georgeurbane, <notifications@github.com> wrote:

Yes to either/both. Certainly happy to make edits - am borderline capable.
I turned debug logging back on and took another look, finding something
interesting:

10-Jan-2017 19:59:28 - DEBUG :: SEARCHNZB : [NewzNabPlus] - result fields
from NZB are {'bookid': u'AWi4DAEACAAJ', 'nzbmode': 'torznab', 'nzbdate':
'Sun, 30 Oct 2016 05:55:39 -0400', 'nzbtitle': 'Livia Lone by Barry
Eisler', 'nzbsize': '495820', 'nzburl': '148', 'nzbprov': u'
http://127.0.0.1:9117/jackett/

that nzburl result is the same thing I assumed was the error number in the
previous logs - but now I think it's actually what is being returned for
the URL. I went and looked at the XML being returned by Jackett, and there
is a field called "grabs" being returned, which, wait for it, is 148.

The correct link is being returned in tags though.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/593#issuecomment-271749335>,
or mute the thread

**Comment by georgeurbane** [comment]
It's MyAnonamouse - even with the additional fields, shouldn't searchnzb.py just return the value in <link> for the link?  

I can send the full XML your way - but I'd rather it not be fully public I think.

**Comment by philborman** [comment]
The parser in providers.py looks quite bad to me. It uses positional 
parameters, so it expects the items it needs to be in a particular order 
and on particular lines in the xml. At least I think that's what the 
problem is. I suppose it should really be rewritten to grab the info 
using a proper xml parser, but it seems the other sources are all using 
the same format as a loose "standard", and myanonamouse isn't? Rewriting 
the parser properly is probably beyond my programming skills, but maybe 
we can just look for keywords at the start of each line instead of just 
using the line number.

The section of xml should look like this (taken from lazylibrarian 
sources), and we read lines

1 = title, 4 = pubdate, 5 = size, 7 = link, 10 = magneturl

  If you can confirm your details are on different lines that should be 
enough, and are your xml labels the same as below, ie <title> <pubDate> 
<size> <link> <torznab:attr name="magneturl"

(and including the same capitalisation on pubDate)

Thanks

     # <item>
     #  <title>Tom Holt - Blonde Bombshell (Dystop; SFX; Humour) 
ePUB+MOBI</title>
     # 
<guid>https://getstrike.net/torrents/1FDBE6466738EED3C7FD915E1376BA0A63088D4D</guid>
     # 
<comments>https://getstrike.net/torrents/1FDBE6466738EED3C7FD915E1376BA0A63088D4D</comments>
     #  <pubDate>Sun, 27 Sep 2015 23:10:56 +0200</pubDate>
     #  <size>24628</size>
     #  <description>Tom Holt - Blonde Bombshell (Dystop; SFX; Humour) 
ePUB+MOBI</description>
     # 
<link>http://192.168.2.2:9117/dl/strike/pkl4u83iz41up73m4zsigqsd4zyie50r/aHR0cHM6Ly9nZXRzdHJpa2UubmV0L3RvcnJlbnRzL2FwaS9kb3dubG9hZC8xRkRCRTY0NjY3MzhFRUQzQzdGRDkxNUUxMzc2QkEwQTYzMDg4RDRELnRvcnJlbnQ1/t.torrent</link>
     #  <category>8000</category>
     #  <enclosure 
url="http://192.168.2.2:9117/dl/strike/pkl4u83iz41up73m4zsigqsd4zyie50r/aHR0cHM6Ly9nZXRzdHJpa2UubmV0L3RvcnJlbnRzL2FwaS9kb3dubG9hZC8xRkRCRTY0NjY3MzhFRUQzQzdGRDkxNUUxMzc2QkEwQTYzMDg4RDRELnRvcnJlbnQ1/t.torrent" 
length="24628" type="application/x-bittorrent" />
     #  <torznab:attr name="magneturl" 
value="magnet:?xt=urn:btih:1FDBE6466738EED3C7FD915E1376BA0A63088D4D&amp;dn=Tom+Holt+-+Blonde+Bombshell+(Dystop%3B+SFX%3B+Humour)+ePUB%2BMOBI&amp;tr=udp://open.demonii.com:1337&amp;tr=udp://tracker.coppersurfer.tk:6969&amp;tr=udp://tracker.leechers-paradise.org:6969&amp;tr=udp://exodus.desync.com:6969" 
/>
     #  <torznab:attr name="seeders" value="1" />
     #  <torznab:attr name="peers" value="2" />
     #  <torznab:attr name="infohash" 
value="1FDBE6466738EED3C7FD915E1376BA0A63088D4D" />
     #  <torznab:attr name="minimumratio" value="1" />
     #  <torznab:attr name="minimumseedtime" value="172800" />
     # </item>

**Comment by philborman** [comment]
Parser rewritten to not use positional parameters now.
