### ISSUE TITLE
Feature request: Way to differentiate audio books?

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#622]
I didn't see anyway to see if a book was an audio book or not without looking through all the book names. Could there be an icon of some other way to quickly see audio vs book?

**Comment by philborman** [comment]
LazyLibrarian isn't really geared up to do audiobooks. There are filters to
try and ignore them in searches by extension or keyword blocking, or by
size limit. Ideally we could use python-magic to get the file type ignoring
the extension, but I don't think it works on windows?

On Sat, 21 Jan 2017, 14:55 MrMxyzptlk, <notifications@github.com> wrote:

I didn't see anyway to see if a book was an audio book or not without
looking through all the book names. Could there be an icon of some other
way to quickly see audio vs book?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/622>, or mute the thread

**Comment by MrMxyzptlk** [comment]
OK, it keeps downloading audio / video on authors even though I have .wav, .mp3, DVD, etc in the block list.

**Comment by philborman** [comment]
Try blocking on size, not all nzb or torrents tell you the file extension
in the title, but books are​ generally only a few mb and magazine pdfs
under 200mb.
