### ISSUE TITLE
LazyLibrarian is unknown version - Fresh Install

### ISSUE THREAD

**Issue by rutskiuk** [DobyTang/LazyLibrarian#632]
I have had a few problems running an update

If I run check version it says I am 50 releases behind and prompts to update, which I do and leaves me with version number unchecked. I check the version number and am told I am 50 releases behind.
I tried manually updating - shutting down and copying over the contents from the zip of the master release. When I ran that I go the same issue, checking the version number I see I am 50 releases behind.
On the off-chance I tried a fresh install from the master and I still get the same problem - version number unknown:

LazyLibrarian is unknown version
No Version File is not recognised at
https://github.com/dobytang/lazylibrarian Branch: master

There is a prompt in the bottom right corner where I normally see an update prompt:

Running Unknown version via source install. Update from central area now Update or Close

Clicking that reloads LazyLibrarian and in settings I still see:

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: No Version File : Latest Version: not checked

I even tried copying over the version number from my previous install but that puts me back into the 50 releases behind loop. Any ideas?

**Comment by philborman** [comment]
"Latest version: not checked" is ok, expected behaviour, we don't check at every boot-up, only if the version file is older than a day, I think.  Looks like you are missing a version.txt file though, should be in the zipfile, not currently sure why it's not, I will have to check.

As a work-around for now, create a file called version.txt in the lazylibrarian root directory (the one with README.md in it) and in that file put cb32714916e02f97bf6a551e8ea8c26c7fa1f906
which is the current version number. Should get you going.

**Comment by philborman** [comment]
Ok, found the problem, and it's a bit more complicated than I thought.
We don't include the version.txt file in the zip as the version number (hash) is only created on upload to github.  What I think we need to do is assume any source zipfile is old (as we don't know otherwise) and immediately force an upgrade. The upgrade process will create the version.txt file containing the right value on completion. The next version will do this automatically if there is no version.txt file found.
