### ISSUE TITLE
No Post Processing

### ISSUE THREAD

**Issue by wantle** [DobyTang/LazyLibrarian#635]
Working mostly on Windows 10 using NZBGET, but I see no post processing. NZBGET is configured correctly and works fine with other apps. Could this be my folder formatting?
I often have issues with "/"

![image](https://cloud.githubusercontent.com/assets/25565940/22626794/5f8c1996-eb90-11e6-9f89-e7af5dceb61f.png)

**Comment by philborman** [comment]
Your eBook destination folder probably wants changing to $Author\$Title
but it looks like there is code in the postprocessor to handle it and warn you in the log. 
Anything useful in debug log?
You can enable debug log from the Logs page, and run postprocessing from either the Books or Magazines page rather than waiting for the timer to go off.

**Comment by wantle** [comment]
Thanks for your reply.

I had already tested $Author\\$Title. That is set currently.

I ran the debug and Forced post-processing as you suggested:
![image](https://cloud.githubusercontent.com/assets/25565940/22628693/5552cace-ebb3-11e6-846b-50630e694cab.png)

It appears the file is not found in the download directory.

However, the folder appears to be there. 
![image](https://cloud.githubusercontent.com/assets/25565940/22628727/ae999072-ebb3-11e6-8512-595fe3dad655.png)

And the file:
![image](https://cloud.githubusercontent.com/assets/25565940/22628748/22526d5e-ebb4-11e6-8683-e9de3db6d0f6.png)

**Comment by philborman** [comment]
Interesting.
No quite enough info to go on yet. The debug log should start with
something like...
Checking <number> files in <folder>
There are <number> files marked "Snatched"
... then for each book ...
<book> was sent to <downloader>
Looking for <book> in <folder>
... then maybe some extra lines about errors...

Also there is an extra verbose debugging mode that might help, set
lazylibrarian loglevel to 3 in config and it should report every file it
comes across and percentage match, rather than just the closest match. Very
verbose, not recommended for normal use, but might help track down the
problem.

**Comment by wantle** [comment]
Log level = 3
I also set the log directory. I have attached the log file. It appears LL is searching my python directory for snatched files (c:\python27) and ignoring my Base directory.???


[ll.txt](https://github.com/DobyTang/LazyLibrarian/files/753228/ll.txt)

**Comment by wantle** [comment]
Here is the relevant line:

05-Feb-2017 16:01:21 - WARNING :: POSTPROCESS : Download dir not usable, using C:\Python27

**Comment by philborman** [comment]
05-Feb-2017 16:01:21 - WARNING :: POSTPROCESS : Download dir not usable,
using C:\Python27

Ok,  seems to be a problem accessing your download directory,  so
lazylibrarian is defaulting to the "current working directory"

There are 4 tests on the  download directory, must be failing one of them,
but don't know which one.

Does the filename exist
Is it a directory
Is it writeable
Is it executable

Maybe the permissions need to be different for Windows. We need to be able
to write new files into the directory,  create folders,  and delete files.
I will need to look into this.

**Comment by wantle** [comment]
Thanks again. I think this may be a user confusion error:

I assumed this was the directory for the file to be moved to after post processing
![image](https://cloud.githubusercontent.com/assets/25565940/22629600/6918fe4c-ebc3-11e6-91aa-517ddcaf518c.png)

I though this folder only applied to Torrents:

![image](https://cloud.githubusercontent.com/assets/25565940/22629615/c1205464-ebc3-11e6-803e-24a4df6c6691.png)

I was expecting LL to move the file from the NZBGET download directory to the Base Folder.

Can you explain the folder differences?

**Comment by philborman** [comment]
Ok,  seems we are checking for write and execute permissions. Not sure
why.  I think we should check for read and write permissions. Are you up to
a bit of light editing to try it out?

In lazylibrarian\__init__.py  line 1337
Change X_OK to  R_OK

If this works I will push the fix in the next release,  or if you're unable
to test i might push it anyway as it makes more sense




On Sun, 5 Feb 2017, 21:05 Phil Borman, <phil.borman@gmail.com> wrote:

05-Feb-2017 16:01:21 - WARNING :: POSTPROCESS : Download dir not usable,
using C:\Python27

Ok,  seems to be a problem accessing your download directory,  so
lazylibrarian is defaulting to the "current working directory"

There are 4 tests on the  download directory, must be failing one of them,
but don't know which one.

Does the filename exist
Is it a directory
Is it writeable
Is it executable

Maybe the permissions need to be different for Windows. We need to be able
to write new files into the directory,  create folders,  and delete files.
I will need to look into this.

On Sun, 5 Feb 2017, 20:42 wantle, <notifications@github.com> wrote:

Log level = 3
I also set the log directory. I have attached the log file. It appears LL
is searching my python directory for snatched files (c:\python27) and
ignoring my Base directory.???

ll.txt <https://github.com/DobyTang/LazyLibrarian/files/753228/ll.txt>

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/635#issuecomment-277543500>,
or mute the thread

**Comment by wantle** [comment]
I appreciate your patience.
Looks like confusion on my part:

Here is where NZBGET saves my ebooks:
C:\filez\complete\ebooks

Here is where I would like to save my ebooks when processed:
c:\ebooks\

Here are my settings in LL: Note the Download Settings directory
![image](https://cloud.githubusercontent.com/assets/25565940/22629791/787288d2-ebc7-11e6-826a-be361a404d76.png)
![image](https://cloud.githubusercontent.com/assets/25565940/22629801/b0ce4036-ebc7-11e6-8277-7f651dd6026f.png)

LL is now processing perfectly in my NZBGET download directory:
C:\filez\complete\ebooks

But not in my Base Directory: c:\ebooks\

It's confusing. Could it still be a permissions issue?

**Comment by philborman** [comment]
Base Destination Folder is where you keep your library, in your case 
c:\ebooks\

In that library, each author has a folder. In each authors folders are 
sub-folders each containing one of the authors books, this is controlled 
by  eBook Destination Folder set to $Author\$Title

The Download Directory is where your downloaders (nzbget, transmission 
etc) put the books they grab. The postprocessor looks here for books to 
process. In your case this is c:\filez\complete\ebooks

There is a description of almost all config options in the wiki. I 
really must get around to adding descriptions for the missing ones.

 From your screenshots it looks like the config options are set 
correctly so the problem is likely to be permissions accessing 
c:\filez\complete\ebooks ???

I had a quick look on google and there are reports of problems with 
python getting correct results for windows file permissions. There is a 
more complicated way of doing it that is more reliable and works across 
all python implementations, I will add that to the next version, 
probably in a couple of days.

If you want a quick fix before then, remove the permission checks 
completely from line 1337
so it just reads...
if not usedir or not os.path.isdir(usedir):

(note the colon on the end, delete everything from "or not" to the end, 
EXCEPT the colon)

**Comment by wantle** [comment]
Even with your modification:
![image](https://cloud.githubusercontent.com/assets/25565940/22630402/257b337e-ebd4-11e6-96dd-9ec4c6e8b96b.png)

LL still prefers to write to my download directory. And has no issues moving files or creating subdirs in that directory.

I've attached the log.

Cheers
W
[LL2.txt](https://github.com/DobyTang/LazyLibrarian/files/753349/LL2.txt)

**Comment by philborman** [comment]
Right, the permissions problem was masking another bug. Found and fixed now. Will run a few more tests and push a new version in a couple of hours.

**Comment by wantle** [comment]
Excellent. much appreciated.

**Comment by wantle** [comment]
Hi philborman,

Have you released a new version? When I run check version from LL now I get the following:

![image](https://cloud.githubusercontent.com/assets/25565940/22671723/624951d8-ecaa-11e6-865a-3a3e97cd94ac.png)

**Comment by philborman** [comment]
The little yellow box at the bottom right is why.  We modified the code to
get rid of the permissions check, so lazylibrarian won't update as that
would overwrite your local changes, which you might not want.
Are you running a git install or  did you download the zip file?
If you're running the git version just do "git checkout
lazylibrarian/postprocess.py
If you are running the zip version just download the new zip,  or run
lazylibrarian with the
--update command line parameter.

**Comment by wantle** [comment]
I tried overwriting the files with the zip, but I still got the same update
message.

So I just deleted the directory and started from scratch with the newly
downloaded zip.

I am a little concerned: When I started LL I got an update message
indicating I was running an unknown version of LL. So I opted to install
the update. Did I download the newest version?

I see there is a versions.txt file. How can I ensure I have your latest
version?

**Comment by philborman** [comment]
The zip file is created by GitHub and it does not contain any version
information, so when you first install from zip lazylibrarian assumes it
could be out of date and immediately updates to latest version. When the
update is complete lazylibrarian creates a version.txt file with the
current version number in it.

Easiest way to check if you are up to date is hit the version check button
on the config page,  or you can compare the number in version.txt with the
one shown on the github page. GitHub only shows the first few characters of
the number,  but it's enough.

**Comment by wantle** [comment]
Thanks. I verified the version; first few numbers were sufficient on GitHub. Sorry for all these questions. I am just getting my feet wet in this world. But I do enjoy testing. Let me know if I can help in any way.

**Comment by philborman** [comment]
No probs.  

Is the postprocessing working properly on Windows now, if so I will close this ticket. Thanks.

**Comment by wantle** [comment]
Working perfectly! All files processed to desired directory: c:\ebooks. Thanks again.
I'll continue testing.....

**Comment by pyrostic** [comment]
Philborman.  I'm having this issue and am on your latest release... not sure what is going on here.
