### ISSUE TITLE
Still having an issue getting LL to create all magazine covers...

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#645]
The example I will use is a new magazine addition to LL.

Interestingly enough both Ubooquity and Calibre create all the covers correctly?

Glamour USA; LL has found and downloaded 37 issues.
It created 6 covers and totally ignores the rest...no errors.

I have attached screenshots for the appropriate parts of the debug log for the 6 issues, and Windows Explorer, showing the directory.

The are no other mentions of Glamour USA in the logs after running the create mag cover API command.

Thanks.
<img width="296" alt="screen shot 2017-02-12 at 7 56 34 am" src="https://cloud.githubusercontent.com/assets/1753001/22862284/cb630a3a-f0f9-11e6-960e-7878adba2b29.png">
<img width="767" alt="screen shot 2017-02-12 at 7 56 55 am" src="https://cloud.githubusercontent.com/assets/1753001/22862285/cb652d4c-f0f9-11e6-8ebf-94b403dfba42.png">

**Comment by philborman** [comment]
The code for "create covers" api call is quite simple. 
For each magazine issue listed in the database, try to create a cover
Doesn't look like it can avoid printing a debug message showing success or fail for each issue, so I'm wondering if not all issues are in the database correctly?
1. createMagCovers starts by saying "Creating covers for xx issues" does the number look correct?
2. On a magazine where lazylibrarian missed cover creation, can you download the magazine from within lazylibrarian (ie does the "open" button work), that will tell us if the database entry is correct.

**Comment by MrMxyzptlk** [comment]
So based on what you just told me, I did a magazine library scan, at which point LL created all the additional covers. Why wouldn't it have done that in the first place when manually post processed them yesterday? They all showed up in LL just without cover creation, and when I tried to download all of the ones that had no cover, it downloaded the same 1 issue for all of them?

**Comment by MrMxyzptlk** [comment]
Additional note: If I goes to the Windows folder it has created all cover correctly.
If I look in LL there are still a lot the same covers for different issues. I have tried running the clear cache API command and exiting Chrome, but no luck to get the new covers to show?

**Comment by philborman** [comment]
Couple of suggestions.
1. The directory listing you sent shows all the issues in one folder.
Lazylibrarian default is to have each issue in it's own subfolder. The
folder names are defined in config, default folder name
is Magazines/$Title/$IssueDate so you end up with...

Magazines\
Magazines\GQ\
Magazines\GQ\2017-01-01\
Magazines\GQ\2017-01-01\2017-01-01 - GQ.pdf

Not sure how lazylibrarian behaves if this structure isn't followed, but I
think on import it probably spots there is already a cover in the folder
and doesn't create another, I would have to check. createMagCovers scans
the database rather than the folder structure, so will notice "no cover
matching issuename_date.pdf" rather than "no cover in this folder".

2. Chrome (and others) try to be helpful by caching images to save
bandwidth, and often don't realise the cover has changed if the name is the
same.  You can tell Chrome to ignore it's cache if you refresh the page by
clicking the mouse on the refresh icon while holding either shift or ctrl

**Comment by MrMxyzptlk** [comment]
I have used this format for quite a while now: $Title - $IssueDate

Clearing Chrome cache the way you mentioned doesn't do anything. I'm going to try within Chrome settings.

**Comment by philborman** [comment]
I have removed the "one issue per folder" restriction, I think it was only
there to match the book layout (author folder, one book per sub-folder)

**Comment by MrMxyzptlk** [comment]
Thanks, I will close this one until next time...
