### ISSUE TITLE
Calibre import does not clean up jpg or opf afterwards

### ISSUE THREAD

**Issue by ethanopp** [DobyTang/LazyLibrarian#691]
Hi,

I have LL setup to download E-Books directly to a folder watched by calibre.

The issue I am having is that all of the files downloaded by LL are automatically set to rw-r--r--

This prevents calibre from automatically importing, as it needs rw-rw-rw-

Is there anyway to update the default permissions LL sets to newly downloaded files?

Thanks!

**Comment by philborman** [comment]
At the moment it's hard coded in the common.py file, setperm() function if you want to tweak it.
Change the 0o644  to  0o666
I will move it into config.ini at some point.

**Comment by philborman** [comment]
These can now be changed in config.ini. You will have to change them by hand though, no option in the webinterface to change them. After you install the new version, go to config page and save your existing settings. This will write the default values into the config.ini file. You can then hand edit config.ini and restart lazylibrarian to load your new settings.

**Comment by ethanopp** [comment]
Thanks for the update, I realized it was not the actual files that LL was writing, but the permissions that were on the dir itself when creating the container...

The autoadd is working now, but how do you set it up so calibre looks at the same file where lazylibrarian is saving? 

Right now I have LL saving to /books/$Author/$Title and the calibre db in /books as well. Once calibre sees LL copy a file to /books, it then looks to save in /Author/Title but often times will create the Title file dir with a random number at the end of it i.e. "Steve Jobs (5)" ...Resulting in 2 copys of every file.

Base dir folder: /books
eBook destination Folder: $Author/$Title
eBook destination File: $Title - $Author

calibre autoadd:/books

Right now I also have the calibredb import program empty, not sure if its required...

Thanks!

**Comment by philborman** [comment]
I guess we could make it configurable. Not sure how LL handles the book location if you don't use calibredb. The problem is that as you noticed calibre adds a number to the directory name, that's calibres "book id". Several other developers over the years have asked the author not to do this, it's really not needed, but he won't change it. When calibre imports the book it changes the directory name and the book title to match it's internal database entries. LazyLibrarian downloaded a file with a known name to a known directory, but calibre will almost certainly move it, and probably change the filename too. To work around this we try scanning the author directory to look for the book but don't always succeed. At least with calibredb we can ask for the "book id" and can work out the directory name, and we can tell calibre what name to give the book rather than the other way round.  If you use calibredb as the importer, keep your download directory and calibre book directory separate. Calibredb will move the book into it's directory structure, tell us where it is, and we can update both our databases to match.

**Comment by ethanopp** [comment]
Right now I have the following and it seems to be working:

Base Destination Folder: /books

eBook Destination Folder: /books
eBook Destination File: $Title - $Author

Calibredb import program: /books
Calibre Auto Add: <blank>

Then within Calibre, I set up the Auto add to watch the /books dir.

So LL downloads **everything** to /books, calibre finds the book file and then creates its oddly named directories with /books as the base (which I can live with) because LL seems to still be able to detect the book even through calibres directories, and there is now only 1 copy of the actual book file. (I am assuming this is because of the Calibredb import program: /books)

Only annoyance is calibre redownloads the metadata into the directories it creates rather then autodetecting and moving along with the book file, so the initial metadatafiles that LL downloads get leftover in my /books dir and pile up...

**Comment by philborman** [comment]
According to the calibre docs it uses the metadata and jpeg files provided during import. Whether it really does I'm not sure. The docs also say it reads metadata from the book files, but it never seemed to work that way here. Whatever happens it doesn't delete the metadata or jpeg afterwards, but it does move the book(s). Not sure what it does with multiple formats of a book either. Using calibredb we have to explicitly set a flag to say "all books in the directory are the _same_ book in different formats". Hopefully autoadd works this out for itself, or defaults to flag set?  If calibre really doesn't use the metadata and jpeg there's no point in copying them over, I just don't know :-)

**Comment by ethanopp** [comment]
Hmm... Okay. Is there a way to run a script after download? Maybe I can just write a quick one to delete all .jpg and .opf files in the /books dir

**Comment by philborman** [comment]
Not at present. Would be feasible  to add a new notifier that runs a custom
script whenever a book is snatched or downloaded. Another user wanted
something similar tying into the notifiers to do his own processing,
running a format converter, sending to kindle etc.

On Wed, 15 Mar 2017, 20:33 ethanopp, <notifications@github.com> wrote:

Hmm... Okay. Is there a way to run a script after download? Maybe I can
just write a quick one to delete all .jpg and .opf files in the /books dir

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/691#issuecomment-286854360>,
or mute the thread

**Comment by philborman** [comment]
The new notifier is in the next version, probably tomorrow unless problems
show up in testing.

In your  use case you can probably ignore all the data sent to the script
and just delete any.opf and .jpg in your download directory.
Just the fact that the script has been called is enough.
If you want to get clever you can check if it is a download or a snatched
notification, check the file location, book details etc.

There will be a couple of examples in the package.

On Wed, 15 Mar 2017, 20:57 Phil Borman, <phil.borman@gmail.com> wrote:

Not at present. Would be feasible  to add a new notifier that runs a custom
script whenever a book is snatched or downloaded. Another user wanted
something similar tying into the notifiers to do his own processing,
running a format converter, sending to kindle etc.

On Wed, 15 Mar 2017, 20:33 ethanopp, <notifications@github.com> wrote:

Hmm... Okay. Is there a way to run a script after download? Maybe I can
just write a quick one to delete all .jpg and .opf files in the /books dir

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/691#issuecomment-286854360>,
or mute the thread

**Comment by ethanopp** [comment]
philborman,

Since updating, the setup described above no longer works...

Post-processing gives the following error:
Postprocessing for Room - Emma Donoghue has failed: **calibredb failed, Permission denied**

This then results in the folder getting updated to .fail

I've checked the permissions on my the calibre metadata.db and they are set to rw-rw-rw-

Any ideas how to fix this?

**Comment by philborman** [comment]
Good news that it's working. I think the calibredb option still gets run even if the autoadd folder option is in use. Not sure why anyone might need both options, might look at disabling one if the other is set.
