### ISSUE TITLE
Series sort not working on author page

### ISSUE THREAD

**Issue by wizzy99** [DobyTang/LazyLibrarian#694]
Current Version: 48b2ab64ae5d8ca658ede11bbb58ea55a3c9d13f

Sorting by clicking on the Series column on an author's page results in a title sort, not series sort. The other columns still appear to support sorting.

**Comment by philborman** [comment]
Yes, you are correct. No idea why though. I would have thought the buttons should just sort on the column they are attached to. Needs looking in to.

**Comment by wizzy99** [comment]
This worked previously, but I can't remember how long ago I last tried.

**Comment by philborman** [comment]
It's probably something stupid I'm doing. Can't quite see what yet.

I played around with a "natural sort" algorithm to try and get series 
orders looking right, but couldn't make it work. I wanted series1, 
series2, series3... series11  instead of what we were getting, series1, 
series11, series2, series3

**Comment by philborman** [comment]
ok, found it. Also managed to get natural sort working too. Grabbed a different example from stackoverflow, seems to work well. Probably in the next release.
