### ISSUE TITLE
Can not set status to "Snatched"

### ISSUE THREAD

**Issue by ATor69** [DobyTang/LazyLibrarian#695]
Current Version: 48b2ab64ae5d8ca658ede11bbb58ea55a3c9d13f
OS: Debian Jessie
Interface: Bootstrap
Source: GIT

No applicable debug log

From the Manage screen when selecting a book with any status (Wanted, Have, Open) and selecting "Change selected books to: Snatched" nothing happens.  In some situations I can not get the torrent to search and download on its own though there is a matching book.  By manually downloading the book and forcing post processing I should be able to add the book to the library, but setting the book to snatched doesn't actually change the books status, thus post-processing refuses to Identify and process the book.

**Comment by philborman** [comment]
Yes, shouldn't really have snatched as an option. Snatched is a special
status that means we sent the request to a downloader, and we're waiting on
a book to arrive. Only works if we sent it ourselves, not for manual use.
This is because we keep track of which downloader we sent it to and when,
we can monitor for arrival and cancel if it fails etc.

To get a manual download to be recognised and imported you can use the
"alternate import directory".
There is a more complicated way to get the postprocessor to do it
automatically using the bookid, but the alternate import directory is the
simplest.

On Tue, 14 Mar 2017 at 02:03 A69Tor <notifications@github.com> wrote:

Current Version: 48b2ab6
<https://github.com/DobyTang/LazyLibrarian/commit/48b2ab64ae5d8ca658ede11bbb58ea55a3c9d13f>
OS: Debian Jessie
Interface: Bootstrap
Source: GIT

No applicable debug log

From the Manage screen when selecting a book with any status (Wanted, Have,
Open) and selecting "Change selected books to: Snatched" nothing happens.
In some situations I can not get the torrent to search and download on its
own though there is a matching book. By manually downloading the book and
forcing post processing I should be able to add the book to the library,
but setting the book to snatched doesn't actually change the books status,
thus post-processing refuses to Identify and process the book.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/695>, or mute the thread
