### ISSUE TITLE
No post processing

### ISSUE THREAD

**Issue by dorel14** [DobyTang/LazyLibrarian#701]
Hello 
### Source of your LazyLibrarian installation   git 

When i force processing lazylibrarian is really lazy cause it find a 100% matching and does nothing.

Logs : `2017-03-17 20:00:28	DEBUG	Nothing in database matching "MbkMDgAAQBAJ"
2017-03-17 20:00:28	DEBUG	Found match (100%): /home/ebooks/Bernard Minier Nuit -.epub for Bernard Minier Nuit -.epub
2017-03-17 20:00:28	DEBUG	Found folder (100%) /home/ebooks/Bernard Minier Nuit -.epub for Bernard Minier Nuit -.epub
2017-03-17 20:00:28	INFO	Looking for Bernard Minier Nuit -.epub in /home/ebooks`

also it doesn't find any snatched magazines even if they are in dowload folder.

**Comment by philborman** [comment]
"MbkMDgAAQBAJ" is the "bookid" that it's looking for. This is a googlebooks bookid, matches book Bernard Minier Nuit so that part is ok.  but it says that bookid is not in it's database so it doesn't know what to do with it. Something is out of synchronisation, the "wanted" table seems to have the bookid in it, but the books table doesn't. I am not sure how this situation might arise. Possibly a change from googlebooks to goodreads, or deleting a book after sending it to the downloaders?

**Comment by djdmd** [comment]
Hello
perhaps i've  tryied d differents service  to find the best one , is it possible not to sync and post process on id but on title and author.

**Comment by philborman** [comment]
Not easy. The problem is that torrent file names are not standardised. We often get files back with a different name to the one we asked for, so we use the bookid to connect the database entries to the right files. It's fine to change provider once downloads have completed, but not while they are waiting processing.

**Comment by philborman** [comment]
You could move the books into the "alternate import directory" and import
by name from there. Run librarysync on each author afterwards so
lazylibrarian notices the new books.
