### ISSUE TITLE
Cannot Update

### ISSUE THREAD

**Issue by exodius99** [DobyTang/LazyLibrarian#711]
I've been using LazyLibrarian and for a while with no problems but lately every time I try to update it just restarts.

Current Version: cb32714916e02f97bf6a551e8ea8c26c7fa1f906
OS: Windows 8.1
[log.txt](https://github.com/DobyTang/LazyLibrarian/files/866029/log.txt)

**Comment by philborman** [comment]
Your log says you are 215 commits behind, I think the upgrade code has changed a couple of times since then. I would suggest you download the zip from https://github.com/DobyTang/LazyLibrarian.git and reinstall. Not sure what the default is in windows, hopefully the database, cache, config.ini  are in your user directory, not the lazylibrarian directory. If in the lazylibrarian directory, move them elsewhere first.

**Comment by exodius99** [comment]
When it first popped up the commits we much less but apparently I didn't catch on to what was happening for a little while. With windows everything is stored in the lazylibrarian directory. I renamed my install folder, setup the new zip, and copied the items you mentioned back in. It had to do a database upgrade and move the cache files around (nice to see those organized now) and it started right up. It did give me a message that it was an unknown version at first being installed from source but once I allowed it to run a update there it went away and is now showing the most recent version. Thank you for your help.

**Comment by philborman** [comment]
I think it would be a good idea to move the cache/database/config into a separate directory and start lazylibrarian with the --datadir=/my/lazylibrarian/directory parameter so you keep your data separate from the program. Makes updating easier if something goes wrong!  I don't know if it's possible to do this automatically on windows, guess it should be. Maybe a folder in the users home directory?

The zip and tar.gz files that you download from the git page are not created by lazylibrarian, they are created by github, and do not contain any version information which is why we do an automatic upgrade on first run. We can't tell if the downloaded zip is a new one. Maybe there is a timestamp in the zip we can check?
