### ISSUE TITLE
Downloading wrong filetypes

### ISSUE THREAD

**Issue by leram84** [DobyTang/LazyLibrarian#752]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page) 
current
### Operating system used (windows, mac, linux, NAS type)
win10
### Interface in use (default, bookstrap)
default (whats bookstrap??)
### Which api (Goodreads, GoogleBooks, both)
goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git
### Relevant debug log with api keys and any passwords redacted
https://pastebin.com/h5kdHg30
Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

I just installed LL on a dev machine for the first time to test it out, so logs are from the beginning of time. I'm getting a bunch of errors, but the main problem so far is that LL doesn't seem to be respecting the filetype. I would like to ONLY grab epubs and nothing else. I have `epub` as the only thing in config/importing/file formats/ebooks. Is that not the correct settings if i want to limit downloads to epub only?

Bonus question: is there a way to import authors from any kind of automated list? (goodreads, rss, etc) Or must all additions to LL be done manually?

And thanks for the great app! It's already looking to be wayyy better than i expected!

**Comment by philborman** [comment]
LazyLibrarian will only import the file types you ask for, but many nzb and torrent files do not tell you the file type in the title. Some nzb downloads include multiple file types etc. The way lazylibrarian works is it downloads the best match by name, if that download doesn't contain a book in the right file type it gets blacklisted and lazylibrarian tries a different download next time the scheduled downloaders run. 

Importing authors/books can be done using a csv wishlist or a goodreads rss feed. Wishlists are imported from the folder defined in the config->processing tab and the import button on the "manage" tab. 
Goodreads rss feeds (reading lists) go in the rss providers section in config->providers

Bookstrap is a more modern interface to lazylibrarian. Themeable, reactive so it's also better on smaller screens (tablets/phones) and comes with 17 ready made themes. You can enable it on the config->interface tab. 

Your errors are all due to you having a low limit on requests per day to your nzb provider. Usually you can subscribe for a fee to get a higher limit. Lazylibrarian does not monitor how many requests are made as it's probably not the only app requesting, you might have sonarr, headphones, nzbhydra etc. all making requests as well. 

Documentation needs quite a bit more work :-)

**Comment by leram84** [comment]
Holy cow!! This thing is so damn cool man! But yeah, definitely needs some more documentation. I plan on diving pretty deep into this over the next couple of weeks, so i wouldn't mind helping out with the wiki grunt work if you would like, though i feel like it would be better to use hover overlays.  I'm not a programmer, but relatively competent with this stuff (well everything except torrents lol) so i might be able to save u some time w the non-essentials.... Let me know.

But for the time being, i have one last question (that's a lie) :) Have you ever heard ombi? I would LOVE to see ombi support LL the same way it does w sonarr/radarr. I'll use goodreads/rss for my users for now, but ombi would be the ultimate integration. I'm not even sure jamie would accept a PR for this, but would be pretty awesome if you guys could collaborate in some way. 

cheers!

**Comment by leram84** [comment]
ahh crap... told u i was lying. ok this is my last question for... for today lol. whats the deal with these multi part books?? why would anyone split up a 1mb file??? Is there a toggle somewhere to filter those out? Or is there something i don't know about that will join them in PP so that calibre never even sees them like that? So many are like this, that im thinking i must be missing something obvious.

**Comment by philborman** [comment]
You can filter out titles with keywords or by file size (reject if larger than, smaller than, contains "part") it's in config - >filters 

Any help with documentation, or anything else, is always welcome

And ombi integration should be possible, there is api access to everything ombi needs, I think, and if anything is missing from the api it can be added.
