### ISSUE TITLE
https timeout on goodreads

### ISSUE THREAD

**Issue by famewolf** [DobyTang/LazyLibrarian#764]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Most Recent
### Operating system used (windows, mac, linux, NAS type)
Freenas 9.10
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Freenas/self updating
### Relevant debug log with api keys and any passwords redacted

The following book does not show up under the author list for Rebecca Hall although she's clearly the author.   I'm showing it on goodreads and lazylibrarian is also supposed to be reading it from goodreads.

https://www.goodreads.com/book/show/30970881-instrument-of-peace?from_search=true

**Comment by philborman** [comment]
In the xml page for Rebecca Hall
http://www.goodreads.com/author/list/1019532.xml?key=ckvsiSDsuqh7omh74ZZ6Q
the book is listed, but no language and no isbn given (we can look up language from isbn)
Same in the xml page for the book, no isbn and no language given
http://www.goodreads.com/book/show?id=30970881&key=ckvsiSDsuqh7omh74ZZ6Q
so lazylibarian doesn't know the language and puts it as "Unknown". Debug log would show this.
You can either add "Unknown" to your list of accepted languages, or (better) search for the book using the search box on the top right and "Add Book" which will bypass the various filters. You specifically say you want this book, so we don't care if it's language doesn't match. I think lazylibrarian might print a warning in the log, but that's all. Still adds the book.

**Comment by famewolf** [comment]
I tried adding the book which is why I thought there was a problem.  See the following: https://imgur.com/a/YVB1I

Screenshot 1: Shows me click on the add book button.
Screenshot 2: Shows where lazylibrarian took me after clicking the button
Screenshot 3: Shows me scrolling down to the R's and Rebecca Hall nor the book being in the list.

**Comment by famewolf** [comment]
Every time I attempt to load the book the log shows:  Got error response for https://www.goodreads.com/book/show/30970881?key=xxxxxxxxxxxxxxx: timed out

however that url loads just fine for me on my pc.

**Comment by philborman** [comment]
Your screenshots show expected behaviour, the timeout is the problem but at the moment I'm not sure why. Screenshot 2 shows you going to the "books" page, which is correct, and shows all the books you have and all the books awaiting download. I guess you don't have any other books by Rebecca Hall so she's not in the list. The book you wanted (instrument of peace) would normally be there marked "Wanted" but as there was an earlier error (timeout) it hasn't been added. It's odd that you can get the url on your pc but not in lazylibrarian. It seems to be working fine here on both.

One possibility is a goodreads api limit? You are limited to one call per second (which is handled in lazylibrarian) and 1000 calls per day (which isn't monitored in lazylibrarian). Maybe you hit that limit, although when I deliberately tried that here I got an error response rather than a timeout. Your browser will send different identification, so may have a separate 1000 limit. Other than that I'm out of ideas on why it works in the browser and not lazylibrarian.

Maybe you could retry the book after 24hrs and see if it's working then.

**Comment by famewolf** [comment]
I've enabled debug and tried various things including adding different books.  From what I can tell the issue seems to be lazylibrarian isn't handling https calls correctly.  I've double checked that a proxy is not in use and I also ran wget in the actual jail that runs lazylibrarian to verify that the jail can access the urls "timing out".

# wget -c https://www.goodreads.com/book/show/14346750?key=xxxx
--2017-05-01 15:35:36--  https://www.goodreads.com/book/show/14346750?key=xxxx
Resolving www.goodreads.com (www.goodreads.com)... 52.94.226.87
Connecting to www.goodreads.com (www.goodreads.com)|52.94.226.87|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/xml]
Saving to: '14346750?key=xxxx'

14346750?key=xxxx        [ <=>                                                                       ]   6.70K  --.-KB/s    in 0s      

2017-05-01 15:35:38 (432 MB/s) - '14346750?key=xxxx' saved [6859]

All I ever see when trying to add a book is this:
2017-05-01 15:32:43	WARNING	Got error response for https://www.goodreads.com/book/show/30970881?key=xxxx: timed out

http calls work as expected:
2017-05-01 15:32:02	DEBUG	Found 20 results with keyword: instrument of peace
2017-05-01 15:32:02	DEBUG	CacheHandler: Returning CACHED response for http://www.goodreads.com/search.xml?q=instrument+of+peace&key=xxxx
2017-05-01 15:32:02	DEBUG	Now searching GoodReads API with searchterm: instrument of peace

Adding authors works fine.  Suggestions greatly appreciated.

**Comment by philborman** [comment]
Ah right, I missed the https part.
I think https support  was added a while ago by another user, don't know if
they are still around. No idea about https, is it really needed talking to
goodreads?

**Comment by famewolf** [comment]
Ok..here's an update.  I had a proxy url in the proxy section  but had both http and https unchecked meaning the proxy should not be used yes?  Well apparently https was still using it.   I cleared the field totally and the https section added a book just fine so  https is still using proxy even if unchecked.

**Comment by philborman** [comment]
Right, that needs looking into. I've no idea about proxies either, don't 
use one, but I might be able to find he relevant bit of code in 
lazylibrarian.

I had a quick look at gr.py (the goodreads interface) and there is one 
reference to https on line 672

I don't think it needs to be https so I will change it to http and run 
some tests.

**Comment by famewolf** [comment]
I thought on this a bit..could they be using https to ensure someone can't intercept their personal api key?

**Comment by philborman** [comment]
Don't think so. The api key isn't really personal, it's a "lazylibrarian" key, same for all uses. The googlebooks one is personal though.

I had a look at the lazylibrarian code for googlebooks and goodreads. 
Googlebooks uses https for everything
Goodreads uses http for everything EXCEPT one call to book/show which is https
Googlebooks needs https, goodreads is happy with either. I think maybe the one https call is a typo as none of the other goodreads calls use https. Doesn't get around your issue though.   

There are a couple of possibilities that might narrow it down...
1. Have you tried the googlebooks interface instead of goodreads. It only uses https so if it's https that's the problem I suspect that will cause lots more errors.
2. What is the freenas package you use, can you try downloading source direct from git in case it's a packaging problem? There are issues (for example) with Docker packages that don't show up on source installations. I think freenas uses linux as a base so the git source or zip download should run.

Simplest workaround for you might be to patch gr.py to remove the "s" from https, but it would be good to know why...

**Comment by famewolf** [comment]
Are you sure the goodreads api key isn't personal?  As I recall I signed into my goodreads account then was able to get my personal key and that's what I pasted into the goodreads key section..same with googlebooks.

I initially tried the googlebooks interface and was getting 0 books back.  In hindsight this would be consistent with it trying to make https calls that failed because it tried to use a proxy I had "down".  If so, that would indicate the problem is wherever it checks whether the https is checkmarked (or it's lack of doing so) which I would think is by the check if http is checkmarked.

Just tried it and googlebooks is still a no go for me although goodreads is performing 100% since I cleared the proxy field.

Log showed:
2017-05-02 11:48:52	WARNING	Found no results for inauthor: with value: allen steele
2017-05-02 11:48:52	WARNING	Got error response for https://www.googleapis.com/books/v1/volumes?q=inauthor%3A%22allen%20steele%22&startIndex=0&printType=books&key=xxxx&maxResults=40: Forbidden

I thought maybe I needed to generate a new "valid" key so I went to the google developer site and did so then repeated the search after entering the new api key.  This also failed the same way. Meanwhile goodreads is reading fine since I cleared the proxy field.

2017-05-02 11:58:08	WARNING	Found no results for intitle: with value: Allen Steele
2017-05-02 11:58:08	WARNING	Got error response for https://www.googleapis.com/books/v1/volumes?q=intitle%3A%22Allen%20Steele%22&startIndex=0&printType=books&key=yyyy&maxResults=40: Forbidden
2017-05-02 11:58:05	WARNING	Found no results for inauthor: with value: Allen Steele
2017-05-02 11:58:05	WARNING	Got error response for https://www.googleapis.com/books/v1/volumes?q=inauthor%3A%22Allen%20Steele%22&startIndex=0&printType=books&key=yyyy&maxResults=40: Forbidden

The freenas "package" or jail is basically a virtual machine running on freebsd (which is the core of freenas so less has to be emulated).  The package was initially setup by a developer with the auto update functionality still usable so as commits come out we upgrade to the latest version.  The jail mainly just has the skeleton that handles startup scripts and where to store the log & database files to keep the location consistent with all the other "plugins". The rest is "vanilla".

**Comment by philborman** [comment]
Lazylibrarian ships with a default goodreads key, ckvsiSDsuqh7omh74ZZ6Q,  but not a googlebooks one as that's against their terms of use.
You can replace the goodreads key if you want, but no real need to. If you want to access your own goodreads booklists, your personal api key goes into the rss feed.  

I have changed the one goodreads https call to use plain http instead, seems to work just the same, but then https works here too. Will push the new version later today.

I wonder whether your "jail" includes access to https,  ie does it open the necessary port(s) does it include the necessary libraries.
Docker, for example, has issues with python exceptions that don't appear on a vanilla install. 
Depends what the jail is blocking access to I guess.

**Comment by famewolf** [comment]
The jail works fine with https hence me showing you wget's of the https url working fine.  The https call on goodreads is now working fine since I cleared the proxy field completely rather than assuming unchecking the http and https boxes would make it not use it.  It has it's own ip address on my lan so gets treated as "just another machine" as far as everything is concerned.  I don't know why googlebooks says "forbidden" but I've got goodreads working so it's not a critical issue.  At some point I must have accidentally wiped out the goodreads key and so put my own in there. For google  books is there something I'm supposed to do beyond logging into the developer site and clicking the "generate api key" button?

**Comment by philborman** [comment]
I don't really understand how the proxies are supposed to work, but it 
looks like there is only one proxy entry available in lazylibrarian and 
it's used for all traffic. We send a "set proxy" request with the proxy 
host and proxy type. It looks like the code assumes the request library 
filters if the proxy type doesn't match, but maybe it doesn't?  Do all 
proxies only handle one type, so we need multiple proxies? Or should we 
check the proxy type and only "set proxy" if the start of the url matches?

The https bit in config is nothing to do with proxies, it controls 
whether you can access lazylibrarians webserver using https. This needs 
to be made clearer I think.

I had a quick look at he googlebooks interface, and it needs an 
application api key I think rather than a developer key, so I guess we 
can ship the same one for all users?

**Comment by famewolf** [comment]
Some but not all http proxies will also do https.  The best solution would be to either allow separate entries for http and https or allow the use to select what protocols to use the proxy on (which is what I assumed the checkboxes meant so yes clarification is needed).  Normally a http proxy just "tunnels" https traffic because it's encrypted so it just does a pass through.    When I needed a key I just did a google on "google books api" and that's how I got to the key I generated but perhaps I am using the wrong one.  Since it's just pulling general book information and not user account specific information I don't see why a generic key would not work.  You have the ability to generate the key for a specific application (at least in the area I was in).

**Comment by philborman** [comment]
I think I will need to leave this for now. No idea what the "enable http proxy" button is supposed to do. Something to do with running lazylibrarian behind a reverse proxy, I think. It just seems to set a flag in the cherrypy webserver "tools.proxy.on" but looking at the cherrypy docs we also need a "tools.proxy.base" for that to work and there isn't one. Had a quick look at headphones which was a base for lazylibrarian code way back, and headphones doesn't have anything similar so no idea what it should do.

The options further down (proxy host, proxy type) are about lazylibrarian redirecting requests through a proxy, leave proxy host empty to disable, but as I said earlier there is no code to check the proxy type against the request unless the request library does it itself, and there is no proxy option in headphones code to compare to. Sonarr by comparison only has one slot for a proxy which can be one of  [ http(s)  socks4  socks5 ]
so it routes http and https to the same proxy. Confused!  I guess lazylibrarian as it's currently set up does the same, maybe even handles socks4/5  as socks is in the requests library contrib section.

**Comment by Code-Slave** [comment]
I think proxy base is how to get to this server through the reverse proxy. Say your proxy path to ll is http://www.somedomain.com/lazyl
then thats what your base would be. Note there is no trailing slash for the base
