### ISSUE TITLE
Request: Audiobook support

### ISSUE THREAD

**Issue by crogers2287** [DobyTang/LazyLibrarian#788]
Is there any chance of adding audiobook support as an option?

**Comment by philborman** [comment]
You can sort-of do it already with a few tweaks to your config.ini file. Difficult if you want both ebook and audiobook though. It might get integrated better at some point if somebody wants to take it on as it's quite a bit of work.

To set config.ini up for audiobooks you can either edit the config file directly, or use the lazylibrarian web interface.
Change your ebook type  to the audiobook filetypes you want "mp3, wav" 
Change reject words to block ebooks instead of audiobook "epub, mobi, pdf"
Change reject minsize to block small files which are most likely not audio, maybe try 20 Mb
Change reject maxsize to zero for no limit, or set a high value
For each nzb provider change the book categories removing 7020 (ebook) and adding 3030 (audiobook)

**Comment by crogers2287** [comment]
Wow, thanks for the tips. I'll give it a shot. I'm fine with running two separate containers for ebooks/audiobooks. 

    On Monday, May 15, 2017 5:19 AM, philborman <notifications@github.com> wrote:
 

 You can sort-of do it already with a few tweaks to your config.ini file. Difficult if you want both ebook and audiobook though. It might get integrated better at some point if somebody wants to take it on as it's quite a bit of work.To set config.ini up for audiobooks you can either edit the config file directly, or use the lazylibrarian web interface.
Change your ebook type to the audiobook filetypes you want "mp3, wav"
Change reject words to block ebooks instead of audiobook "epub, mobi, pdf"
Change reject minsize to block small files which are most likely not audio, maybe try 20 Mb
Change reject maxsize to zero for no limit, or set a high value
For each nzb provider change the book categories removing 7020 (ebook) and adding 3030 (audiobook)—

**Comment by philborman** [comment]
I have added audiobook support alongside ebooks now. Only available on the bookstrap interface as the default interface is becoming obsolete. I don't use audiobooks myself, so feedback on how it works and how the interface can be improved would be appreciated.

**Comment by MrMxyzptlk** [comment]
Sooooo, love the new features. I'm a little dense just how does one search for and download an audio book? Do I just search like normal from the main screen?

Also how does the new eBook feature work? Is that for 'connecting' to Calibre?

**Comment by philborman** [comment]
eBooks is a list of all the books in your library, plus any marked as wanted
AudioBooks is the same (ones you have and ones you want)
On each author page you get a list of all the books they have written (that we know about)
and on the top right of each author page is a box marked "Library"  where you can choose to display  AudioBook or eBook.  When you mark a book on this page as "wanted" it will try to find AudioBook or eBook depending on the Library setting.
For example the screenshot below will mark Nomad AudioBook as Wanted
![screenshot from 2017-06-13 19-21-30](https://user-images.githubusercontent.com/12158777/27095385-be6bf246-506d-11e7-8526-1ea2fa594f94.png)

**Comment by MrMxyzptlk** [comment]
Thanks for the instructional, that really helped.

I have now tried to search for an audio book from an author, and it keeps downloading the EPUB rather than searching and downloading the audio book. I am going to 'Author' then 'Audio Book', then I select the book and click on 'Wanted.

Here is what is shown in the log when it thinks it finds the audio book.

Requesting AudioBook download: 91% https://legendapi.oznzb.com: Millard Candice Destiny of the Republic a Tale of Madness Medicine and the Murder of a President epub

**Comment by philborman** [comment]
I would try setting some size limits, audiobooks are larger than ebooks, maybe a minimum size of 3mb
You could also put epub in your audiobook reject list so titles containing that word get rejected.

**Comment by MrMxyzptlk** [comment]
I just checked, and epub is already on the audio book reject list.
The 3MB limit is already in place as well.

What do think?

**Comment by MrMxyzptlk** [comment]
All of the audio books that have downloaded are in separate mp3 files for each chapter.
Will the post processor now what to do with these?

**Comment by philborman** [comment]
Yes it will put all the mp3 files into a new folder following the
foldername pattern in config, and ignore any other files.

**Comment by philborman** [comment]
NOTE - the information in this thread is now obsolete, audiobooks are not supported on the default interface which may be retired soon. LazyLibrarian has a dedicated audiobook mode in the bookstrap interface.
