### ISSUE TITLE
Request: OPDS library server/generation

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#789]
Not everyone i assume wants/needs to run calibre especially if we have most of the needed fields already in LL. What this would do is if you hit /opds (or whatever) it would init the opds server and show the calalog of books. Usually it presents multiple lists sorted by say author,pubdate,title,publisher,series

opds is a variant of RSS from what i have seen so far its not overly complicated. You could even as one of the jobs generate static files.

odps presents a catalog view for web and ebook readers to browse and download ebooks from a simple html interface. think calibre light.

I will help and test this as much as i am able (skill wise)

specs
http://opds-spec.org

some examples and other software that does it
https://codegists.com/snippet/python/opds-serverpy_gierwialo_python
https://github.com/rvolz/BicBucStriim
https://github.com/seblucas/cops
https://github.com/yinlei212/cockybook

**Comment by MrMxyzptlk** [comment]
Have you tried running Ubooquity?

https://vaemendis.net/ubooquity/

**Comment by philborman** [comment]
Yes, I run a cops server on my raspberry pi, but it just accesses the calibre database so no need to add any code into lazylibrarian for that. Idon't have a full calibre installation running on the pi, just a calibre database and calibredb to keep it updated with new additions.

**Comment by Code-Slave** [comment]
Yes I have used cops, calibre, ubooqity. I guess my point was to add ods browser to LL as we have the books and metadata anyway already pulled and in a db

**Comment by PidgeyL** [comment]
I was actually looking for this same feature. I run Ubooquity and LL, and would like to use Ubooquity as the OPDS server, instead of COPS

**Comment by barbequesauce** [comment]
Mylar recently added an OPDS server - might be worth a look for implementation ideas directly in LL?

**Comment by philborman** [comment]
Doesn't look too hard to bolt the mylar opds server into lazylibrarian, the codebase for both of us was quite similar a few years ago. I used to use calibre/cops but now just use lazylibrarian on it's own, I don't have anything that uses opds, so would be unable to test it so it's probably not going to happen unless anyone else wants to have a go.

**Comment by barbequesauce** [comment]
I'm happy to test... I have a few OPDS apps on iOS devices to work with...

**Comment by philborman** [comment]
What features would be useful in the opds server?
At the moment I have top level as... 
Authors
Magazines
Recent Books
Recent Audiobooks
Recent Magazines
Authors drops down to books by the author, Magazines drops down to issues. 

There is no search available, not sure if that's a feature in opds? 
The details shown are just titles, no descriptions, no covers. Are these useful or necessary?
There is no download available either, I guess we will need to allow the opds user to select the file format (epub/mobi) and for audiobooks zip up the mp3 files?

**Comment by barbequesauce** [comment]
That top level sounds good to me.

I've never seen a search engine plugged into an OPDS server - usually a dedicated search engine stands alongside and has spidered the OPDS catalog, serving up results.

In Mylar's implementation it serves cover images as well, but I wouldn't say it's a must have if the images are not already available. Descriptions are part of the official spec, but Mylar isn't serving them as there is no canonical source of data.

For download links - I think that's a good approach?

**Comment by philborman** [comment]
ok, first attempt is in my git if you want to try it, https://github.com/philborman/LazyLibrarian.git
Navigation is working fine, not sure what other types might be useful. I added Series as that seems a fairly obvious one.  No downloads yet, so it's just an opds browser at the moment. Some pages might show a download link, but they are not working, at least not for me.

**Comment by barbequesauce** [comment]
Great thanks. Tonight I'm dead in the water - same tomorrow - but I'll kick the tires Sunday. Should I update this issue with comments or do it in that repo?

**Comment by barbequesauce** [comment]
OK so I have it running now... works beautifully with Marvin3 (ePub & PDF). TotalReaderApp handles PDF no problem, but ePub blows up ("Invalid mime-type", as you mentioned might be a problem). I know there's no problem with the file because Ubooq has no problem serving it over opds.

**Comment by philborman** [comment]
Yes, opds doesn't seem as "standardized" as you expect, I've had the same problem. Some opds browsers work fine, others don't. The mimetype we send for epub is 'application/epub+zip' as per the spec so don't know why TotalReaderApp doesn't like it.  I tried the online opds validator on lazylibrarian output and after a bit of tweaking we now pass 100% . Not sure where we go from here.

**Comment by barbequesauce** [comment]
I pulled the pages using curl - looks like a small difference in that LL is serving a programmatic link while Ubooq is serving the actual file (if that makes sense?)

LazyLibrarian:
`<link href="/lazylibrarian/opds?cmd=Serve&amp;bookid=17705511" rel="http://opds-spec.org/acquisition" type="application/epub+zip"/>`

Ubooquity:
`<link type="application/epub+zip" rel="http://opds-spec.org/acquisition" href="/ubooquity/opds-books/books/579754/Eragon%20-%20Christopher%20Paolini.epub"/>`

I've downloaded about sixty epubs from Ubooq with TotalReader, no issue - I tried ten of them with LL and all failed, so it seems to be a LL issue.

I tried changing the epub mimetype to x-download in opds.py, no joy either. Renaming the file didnt change anything either.

Since LL passes validation I would chalk this up to a faulty implementation by TotalReader...

**Comment by barbequesauce** [comment]
Worked like a charm. The same ten files that failed earlier work in TotalReader now. PDFs and MOBIs work in all three tools (TotalReader, Marvin3, and MegaReader) as well... but I dont have any audiobooks or azw3 to test with. Any recommendations?

**Comment by philborman** [comment]
Excellent!  That'll teach me not to rely on other peoples code too much...
Mylar does some other odd things I'd spotted and altered, didn't know about the two "serve" functions though. Seems serve_download is shorthand for serve_file type=application/x-download
so it overrides the mimetype we send.

If mobi works then azw3 should, it's a fairly close variant.
For audiobooks I tried a general opds browser from the android app store and it worked, and it works from a browser if you click the link, so fairly sure that's ok. Thanks for the testing.

Still a couple more things to sort out, but it's close enough to push as a release I think for wider testing.
Still need to offer multiple links for epub/mobi/etc if there is more than one book type available, not sure if the opds spec allows this, it looks like each "entry" in a feed can only have one link in it.
Also have the bare bones of a "search" included, more of a filter really. Works from the browser, but the opensearch spec doesn't seem to make sense to me yet. Need to re-read it a few more times. opensearch should allow the opds browser to do things like filter the books on words in a title, or series by an author. Useful if I can get it working.

**Comment by barbequesauce** [comment]
Great. I'm here to test when you need it...

**Comment by Code-Slave** [comment]
i go on vacation and you do some cool stuff :). catching up and will look at this in a big way.

**Comment by philborman** [comment]
Main branch, just go to /opds

**Comment by alagave** [comment]
Thanks for this.

**Comment by yabdali** [comment]
> Recent Books
> Recent Audiobooks

First of all, thanks alot.  I am using LL extensively for ebooks and audiobooks. 

Would it be possible to add to OPDS an option for Books or Audio Books?  Currently I can only find non-recent books by going through authors which is cumbersome. Also, not sure if its part of OPDS standards but it would be good to include rating if exists for each book.  

My situation is that I use LL to download books, I use my tablet to connect to OPDS server and import the ones that I need to read.  I used calibre before but it requires to go back to PC and rebuild the DB.  I tried Calibre-Web and BBS/OPDS but they require to get the database refreshed using Calibre.  I am currently using Ubooquity as my OPDS source but its very limited and an additional service in my NAS setup. I believe LL can make it easier in situation if there's a list of all the books in one go instead of going by author.

**Comment by yabdali** [comment]
> There is supposed to be a ratings element in the latest opds spec, but I can't find any examples, nobody seems to use it. I tried adding a "Rating" element, also tried "Rate" and "Ratings" but none appear on screen in the opds readers I used. Tried Moon+ and Aldiko. Might be because they only follow an older spec though. If we can find a working example it might be worth another try.
> 
> As for lists, the "Recent" lists actually show all books, just most recent first. Your opds browser probably paginates them for speed. You could always use the search filter if your browser has one?
> 
> I could maybe add alphabetical ordering as an option, but not sure it would be any easier?

Thanks, for your timely response. I can confirm using Moon Reader, Aldiko, FBReader and PocketBook show identical results, the last three apps don't have pagination but update the list as I scroll. However, I get about 107 books through recent books whereas checking the authors yields 172 authors with some some having more than 1 title. I know that I have more than 100 books in my Library.

Another approach for solving the rating issue could be by implementing OPDS 1.1 standard (7.4.1. Sorting Relations),  http://opds-spec.org/sort/popular by sorting books based on their release date & rating desc order.

**Comment by philborman** [comment]
Popular is easy to add, will take a look at that tomorrow. Not sure why we are missing books in the "recent" list though. We get a list of every book with an "open" status, sort them on date added to library, and feed them back paginated bt the browsers (they say things like send me books 31 to 40). I realise it could be a bit of work, but any way of working out which books in your library do not appear in the list? It won't be the authors or titles, but maybe we miss books of a particular type (eg pdf) or maybe the books are status "have" or "ignore" rather than status "open"? Something non-obvious is going on.

**Comment by yabdali** [comment]
> Popular is easy to add, will take a look at that tomorrow. Not sure why we are missing books in the "recent" list though. We get a list of every book with an "open" status, sort them on date added to library, and feed them back paginated bt the browsers (they say things like send me books 31 to 40). I realise it could be a bit of work, but any way of working out which books in your library do not appear in the list? It won't be the authors or titles, but maybe we miss books of a particular type (eg pdf) or maybe the books are status "have" or "ignore" rather than status "open"? Something non-obvious is going on.

You're right, accept my apology. By cecking Manage eBooks, filtering status 'Open', I get 108 books. My ebooks overall Library is about 168 books which some of them were downloaded but LL hasn't yet updated due to Deluge issue.
