### ISSUE TITLE
Difficulty with checkboxes

### ISSUE THREAD

**Issue by barbequesauce** [DobyTang/LazyLibrarian#797]
Hi there - 

Looking at a weird interface issue - not sure if it's a bug or a conflict with other stuff on the box.

When I check a box and scroll on the page, the checkbox clears itself...

At first I thought I was just confused, but it's pretty consistent in the Authors and Books pages for me.

The same box also has CP, Mylar, and Headphones if that matters (and Sick Gear, although that is pyenv'd to another Python installation).

Any ideas?

To help with identifying and fixing issues, please include as much information as possible, including:
### Source of your LazyLibrarian installation git

**Comment by philborman** [comment]
The boxes clear if the screen refreshes, can be a bit tricky on a tablet
but I've no idea how to reduce the sensitivity, maybe the refresh can be
disabled, I will have a look.

**Comment by philborman** [comment]
Seems the problem is that a scroll on a tablet/phone can trigger a data-reload whereas a scroll on a laptop browser doesn't. Something to do with trying to resize I think, as if I disable resize, the data-reload doesn't happen and the checkboxes stay selected. The resize code calls "draw" which reloads the data from the database and redraws the table. 
Ideally we would save the checkbox states before calling resize, and reload the states when the table is redrawn. Several threads from users with the same issue, but can't see a simple solution to it. I think I will disable the resize code completely for now.

**Comment by philborman** [comment]
I have disabled the resize code, and the checkboxes seem ok now.

**Comment by barbequesauce** [comment]
Looks better - thank you!
