### ISSUE TITLE
LL will not start following update

### ISSUE THREAD

**Issue by wantle** [DobyTang/LazyLibrarian#825]
LL fails to start on Windows 10 following last LL update

Error output as follows:

03-Jun-2017 21:37:43 - INFO :: MAIN : Log level set to [2]- Log Directory is [C:\LazyLibrarian\Logs] - Config level is [2]
03-Jun-2017 21:37:43 - INFO :: MAIN : Screen Log set to INFO/WARN/ERROR
03-Jun-2017 21:37:43 - DEBUG :: MAIN : General : destination_dir -> C:\ebooks\
03-Jun-2017 21:37:43 - DEBUG :: MAIN : Newznab0 : enabled -> False
03-Jun-2017 21:37:43 - DEBUG :: MAIN : Newznab0 : generalsearch -> search
03-Jun-2017 21:37:43 - DEBUG :: MAIN : Newznab0 : booksearch -> book
03-Jun-2017 21:37:43 - DEBUG :: MAIN : Newznab0 : magsearch ->
Traceback (most recent call last):
  File "C:\LazyLibrarian\LazyLibrarian.py", line 225, in <module>
    main()
  File "C:\LazyLibrarian\LazyLibrarian.py", line 139, in main
    lazylibrarian.initialize()
  File "C:\LazyLibrarian\lazylibrarian\__init__.py", line 437, in initialize
    config_read()
  File "C:\LazyLibrarian\lazylibrarian\__init__.py", line 530, in config_read
    "AUDIOSEARCH": check_setting('str', newz_name, 'audiosearch', ''),
  File "C:\LazyLibrarian\lazylibrarian\__init__.py", line 378, in check_setting
    except ConfigParser.Error:
NameError: global name 'ConfigParser' is not defined

**Comment by rv10guy** [comment]
I have an identical issue on Ubuntu 16.04. I attempted to update through the GUI. It indicated there were 21 commits to apply. The update waited 30 seconds and then during the refresh the gui timed out. I manually stopped and started LazyLibrarian and can't get a gui interface. I stopped the service and tried update from the command line and get the same message as above. (Closing duplicate issue #826)

**Comment by rv10guy** [comment]
@wantle Recommend removing your API key from your posting

**Comment by rv10guy** [comment]
@wantle Recommend removing your API key from your post.

**Comment by wantle** [comment]
Hey Thanks.
It was a fake key but I edited the post to avoid any more confusion.

**Comment by philborman** [comment]
Sorry about that, tried to tidy up some of the Exception clauses to be more specific instead of a catchall.
I've reverted the relevant changes, so should be fixed now. I need to learn more about exception handling ;-)

If you're using git, just do a "git pull" to get the upgrade.
Otherwise run  LazyLibrarian.py --update

**Comment by wantle** [comment]
Hi philborman

I'm still stuck.

_GIT PULL_ fails "not a git repository"
& 
_LazyLibrarian --update_ fails due the previously reported error

_NameError: global name 'ConfigParser' is not defined_

**Comment by philborman** [comment]
from a terminal, change directory into your lazylibrarian folder (the one
containing LazyLibrarian.py)
and git pull from there.

Otherwise if your user data (database, config.ini, caches) are _not_ in the
same folder as LazyLibrarian.py you could just reinstall. Or move them out,
reinstall, put them back. There are only three things you need to keep,
lazylibrarian.db  config.ini  and the cache directory, although the cache
is just for speed, it would eventually rebuild itself anyway.

**Comment by wantle** [comment]
The 2nd option worked. Backup and running thanks.

**Comment by rv10guy** [comment]
Thanks @philborman I really appreciate the fast response on this one. I am back up as well the git pull worked for me.
 Thanks!
