### ISSUE TITLE
Automatic post processing not working

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#860]
Automatic post processing not working.

I tried setting and saving first 5 minutes, then 1 minute, just to test the auto post processing.
It never triggered.

Manually post processing works fine, other than the other issue I just posted about SABnzbd.

**Comment by philborman** [comment]
In "config->processing" page, at the end, is a "Show Jobs" button which will give you the runtimes of all the scheduled jobs. The postprocessor is in this list as "Process Downloads". Example below.
The postprocessor runs once at startup, and after that will only run if there are items marked as "snatched", otherwise it switches itself off. Snatching a book/mag starts a new postprocessor. 
Not much point in running the postprocessor ever x minutes if we're not expecting any downloads to arrive.

Cache 0 hits, 0 miss
2 items marked as Snatched
0 items marked as Wanted
Oldest author info (Stieg Larsson) is 20 days old
Process downloads: Next run in 8 minutes
Book search: Next run in 6 hours
Magazine search: Next run in 6 hours
Check LazyLibrarian version: Next run in 24 hours
Update authors: Next run in 4 hours
