### ISSUE TITLE
Qnap build

### ISSUE THREAD

**Issue by perezbalen** [DobyTang/LazyLibrarian#887]
This more than an issue is a request.

I'm migrating to a Qnap Nas, and moving my LazyLibratian to there. But the only build I could find for qnap is LazyLibrarian 2.0b, which I can't install in QTS 4.3.3

The log tells me: 
> The following QPKG must be installed and enabled: Optware | opkg. The following Optware package must be installed: python26. 	

But Optware is no longer a thing, so I can't get pass this error. (also, I have no clue how to make a QPKG).

Thanks

**Comment by philborman** [comment]
Hmm, I've no idea either, but perhaps there are other qnap users on here?
It's linux based, so if you can ssh in you might be able to install the packages you need. You seem to be missing python (lazylibrarian needs 2.6.x or 2.7.x) but pretty much everything else lazylibrarian needs is included in the lazylibrarian zip file. You might not need a "build", just unpack the zip and run from there.

**Comment by philborman** [comment]
Another option might be to use docker?
There are instructions for installing similar apps on qnap here https://github.com/jakbutler/docker-calibredb
and lazylibrarian docker is here https://hub.docker.com/r/linuxserver/lazylibrarian/
LinuxServer.io keep the docker image up to date, and I think the lazylibrarian internal update still works too.

**Comment by gilly65** [comment]
there is a LazyLibrarian_150124.qpkg that used to work, it won't any longer.
I have had this running on my Qnap NAS for a while now, but since I upgraded it to 4.3.3 it has not updated and when I open the web page, it says:
Unable to get latest version from GITHub

and when in the config, at the bottom of the page it says:
Repo: https://github.com/dobytang/lazylibrarian : Branch: /bin/sh: /Apps/bin/git: No such file or directory
Current Version: GIT invalid hash return : Latest Version: Not_Available_From_GitHUB

I am considering installing it through docker but would prefer the original one to work, does anyone have any thought to get this running and updating again?

Mylar was the same but now there's an updated .qpkg for it that works once more, I was hopeful someone would do the same for LL, but so far, nothing.

Thanks.

**Comment by philborman** [comment]
Couple of thoughts,
1. the message would seem to indicate you haven't got git installed, or at least it's not /Apps/bin/git
2. Maybe you can install from the lazylibrarian zip file if you can log in over ssh

**Comment by gilly65** [comment]
/Apps/bin/git is just a symlink pointing to /share/CACHEDEV1_DATA/.qpkg/git/repository/bin/git
There does seem to be another git installation at /share/CACHEDEV1_DATA/.qpkg/QGit but I honestly have no idea how to tell which one is valid, or maybe both are, and I don't want to create a symlink for this and break something else.

**Comment by philborman** [comment]
We can maybe bypass git.
Can you  log into your qnap over ssh?  If so, in the lazylibrarian folder (the one containing LazyLibrarian.py) there is a hidden folder called .git (dot as first character)   if you rename this, or delete it, then restart lazylibrarian, it will think it was installed from the zip file  instead of git.  You might then be able to use the internal upgrade as it will upgrade by downloading the latest zip

**Comment by gilly65** [comment]
Now I get this message:
Running a local updated version. Push changes to GITHub or rollback to Master release

and when I manually check for an update, this:
LazyLibrarian is unknown version
Your version is not recognised at
https://github.com/dobytang/lazylibrarian Branch: master

I'm not sure if that helps or not, but it is still working.

**Comment by philborman** [comment]
Ah, seems the update from zip didn't overwrite the version.txt file in the lazylibrarian folder. Maybe it's permissions?
I'm not sure what happens if you delete it, might not recreate which could be a problem. If you can edit it, the version.txt file should just contain the hash...
0fb5e2cf6656a196aeb221b94acb9f8cc423248e

**Comment by gilly65** [comment]
BINGO!

Thanks again for all your help, this is not the first time you've gone above and beyond for me!

**Comment by gilly65** [comment]
perezbalen - I ca send you the install I have, if you'd like.

It won't work, but I could also zip my installation for you to overwrite what is there, it may just work for you too.

**Comment by philborman** [comment]
No problem. ;-)

**Comment by perezbalen** [comment]
gilly65 - Thanks. That would be super nice. I'll give it a shot.

**Comment by gilly65** [comment]
I hope the links to mediafire are allowed, and will work for you.

This is the app I used to install, it will3 install and create a shortcut, that seems to be all it does for me now, maybe it will work better for you.
http://www.mediafire.com/file/5c9hg1ytrp3lmnr/LazyLibrarian_150124.qpkg

I would try it and see if it works for you, if it doesn't work, just go to the "App Center" and find the Lazy Librarian icon, click the drop down arrow and select "stop". It will kill whatever part of it is running. (wait about 30 seconds before trying to connect to it, just in case it is doing something)

Then you will have to find where it is installed, for me, it is located at: /share/CACHEDEV1_DATA/.qpkg/LazyLibrarian - finding the install location should be the most difficult part of this, hopefully.

Once you find where it is, just unzip this archive (to your computer) and upload the contents to the LazyLibrarian folder.
http://www.mediafire.com/file/b9j27e5ug77cq6q/LL.7z

Agree to let it overwrite everything, let it upload and finish. Then go back to the App Center and start Lazy Librarian again, after a few seconds you should be able to access it and configure it, I hope!

Good luck and I will keep watch on this and try to help if there are any problems.
FireFTP works in Firefox based browsers, however WinSCP is a lot faster.

**Comment by OneCDOnly** [comment]
Just a quick note that **LazyLibrarian** is now available for the QNAP NAS via [**sherpa**](https://forum.qnap.com/viewtopic.php?f=320&t=132373).  ;)

**Comment by alagave** [comment]
The current qpkg on the EU QNAP Club is working for me. I have not upgraded recently because the scan has been running for 4 days! Over 9400 entries of the known 15,000 processed already.

LazyLibrarian is behind by 30 commits
Merge pull request #1521 from philborman/master

**Comment by philborman** [comment]
Unfortunately there is a major database upgrade since that qnap version, which is why it's taking so long.
If you have nothing too unusual in your setup (lots of wanted books not snatched yet, lots of hand edited ones) it might be easier and faster to scrap your existing database and start again.
The problem is that we used to get a lot of info from librarything, but they have disabled the api we were using and now we have to re-fetch all the info from another source.

**Comment by alagave** [comment]
No complaint - in fact, I am impressed it continues to chug along. I do suspect the Calibre database is inaccessible due to Calibre running on a Windows machine but it seems to be populating LL using the content server. If I understand, it cannot write to calibre without db access? I guess I have to move everything to a container so Calibre and LL can see each other?

And, if I upgrade now, will the scan resume where left off or start over again?

Thanks for this software!

**Comment by philborman** [comment]
There is a docker linked to on lazylibrarian git page (Thraxis docker) that includes enough calibre components to talk to calibre on a different machine, and yes you will have to restart the scan if you stop it part way.
