### ISSUE TITLE
torznab categories

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#900]
Title/Author search with Torznab seems to use regular newznab parameters, which just seems to give the last X results from the indexer.   During automatic searching, it appears to do both generic searches (q=search&extended=1) and the newznab search (author=Author+Name&cat=8000%2C8010&title=Book+Title&etc).  Torznab only seems to be matching on the generic search, which doesn't include categories, so it's downloading audioooks as ebooks and vice versa, as well.  

I can give logs, but I need to scrub them, and I'm growing lazier as the day goes by :)

**Comment by philborman** [comment]
Depends on the torznab provider parameters and the underlying search provider. Many torrent providers don't have categories available.  Where possible lazylibrarian will do a "book" search first using categories. If there are no results it then retries as a "general" search. Manual searches do the same. The "book' search is skipped if the provider doesnt say they can do it, or if it failed before, or if the zearch doesn't have both author and title (book search needs both)

**Comment by DarkSir23** [comment]
In this case, it's Jackett, which I've just set up to let me interface an indexer that doesn't have a good api of its own.  Jackett uses Sonarr's torznab api format, so it will do categories with a general search.  Think there'd be any way we could bring those together?  I'd be happy to help.

**Comment by DarkSir23** [comment]
(I switched to Jackett, as  I originally had 8 categorized RSS feeds for the same site, to try to catch everything)

**Comment by philborman** [comment]
Not sure how jackett does it. There are defined torznab categories, I guess jackett translates them on providers that can handle category specific searches, and does generic searches on those that can't. We do something similar on torrents. Worldwidetorrents has categories, as does piratebay, but the others don't.

**Comment by DarkSir23** [comment]
Yeah, it appears so.  I guess what I'm wondering is, is there a way to force category searching on a torznab provider, even if it has to take a general search?

**Comment by philborman** [comment]
No. You need...
1. Underlying torrent provider understands categories and has a category specific search
2. Jackett knows how to translate torznab category search into something underlying provider understands
3. Jackett reports booksearch capabilities to lazylibrarian so we know we can use it

example:  Actually mine is cardigann rather than jackett, but it's the same procedure...
1. WorldWideTorrents booksearch looks like this...
https://worldwidetorrents.eu/torrents-search.php?search=Tom+Holt+Grailblazers&cat=36&page=1
2. Jackett query looks like this...
http://192.168.0.1:9117/torznab/worldwidetorrentst/api?q=Tom+Holt+Grailblazers&apikey=xxxxxxxxxxxxxxxxxxxxxxxx&t=search&cat=8000%2C8010
3. Jacket tells LazyLibrarian Categories: Books 8000,8010 : Mags 8030 : Audio

Lazylibrian knows booksearch is available, jackett said so, so we send a booksearch, category 8000,8010 which jackett translates into a format wwt understands using search= and cat=36
Piratebay uses category=601, kat and zooqle use category=books, limetorrents doesn't use categories
If the underlying provider ( eg lime) doesn't have category search, or jackett doesn't know how to use it, jackett reports Categories: Books  : Mags  : Audio  so we don't try book search and go straight to general search. Hope that makes sense.

**Comment by DarkSir23** [comment]
I think I follow, except that's not what the jackett query ends up looking like.  If it's passing t=search&q=<terms> it's not passing cat at all.  If it passes author=yadda&title=yadda then it passes cat.

**Comment by DarkSir23** [comment]
I mean, theoretically, if the provider doesn't support categories, it should ignore the cat parameter.  So would it hurt anything to pass the (ebook|magazine|audiobook) categories when doing a general search?

**Comment by philborman** [comment]
If you send parameters that it doesn't understand you will probably get an error message instead of any results.

**Comment by DarkSir23** [comment]
I'm not sure what to do then, to make it not download audiobooks for ebooks and vice versa.

**Comment by philborman** [comment]
You can reject on size and/or keywords, audiobooks are much larger than epub/mobi, and also pdf unless it's lots of pictures :-)

**Comment by DarkSir23** [comment]
Final followup on this :)  Can you tell me how the Priority works among providers?  I'm trying to match on the torznab providers before I match on the newznab, but it seems to grab the newznab result regardless of what priority I use.

**Comment by philborman** [comment]
There have been a lot of changes to lazylibrarian matching routines over the last couple of years. We used to use a "first past the post" system, where you set a "match ratio" and scan each provider in turn until you get a result over the threshold. That often gave false matches, or missed the "best" match because another provider got there with a "just ok" match first. We now scan all active providers, collate all the matches that are over the threshold, and give them a "score".

The scoring system is based on fuzzy matching the author and title, then lose points for each extra word, and gain points for each wanted format named in the title. Can result in >100% match if it's a really good match, no extra words, and also mentions the formats you want.

Provider priority is the last check. If there are equally good scores from more than one provider, download from the provider with highest priority.

**Comment by philborman** [comment]
If it's just for testing/debugging, the easy way to force matches on torznab is to temporarily untick all the other providers :-)

**Comment by DarkSir23** [comment]
Yeah, that's what I ended up doing. Thanks :)
