### ISSUE TITLE
(Solved) Errorno13 

### ISSUE THREAD

**Issue by ausghostdog** [DobyTang/LazyLibrarian#947]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 9e82f5aff2804e6fdb37beff4da1c559c13781e2 : Latest Version: 9e82f5aff2804e6fdb37beff4da1c559c13781e2
### Operating system used (windows, mac, linux, NAS type)
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

### Interface in use (default, bookstrap)
Default I guess
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
https://github.com/linuxserver/docker-lazylibrarian
### Relevant debug log with api keys and any passwords redacted
![image](https://user-images.githubusercontent.com/7588602/28549828-2d718886-7120-11e7-95c5-811af4012787.png)

Some more information
root@lazylibrarian:/app/lazylibrarian/lazylibrarian$ ls -la postprocess.py
-rw-r--r-- 1 abc users 69352 Jul 24 11:54 postprocess.py

root@lazylibrarian:/var/run/s6/services/lazylibrarian$ ls -la
total 20
drwxrwxr-x 4 root root 4096 Jul 23 00:51 .
drwxr-xr-x 5 root root 4096 Jul 23 00:51 ..
drwx-ws--T 2 root root 4096 Jul 23 00:51 event

line 371 is 
                                if not os.listdir(pp_path):

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1171597/debug.zip)

**Comment by philborman** [comment]
drwx-ws--T 2 root root 4096 Jul 23 00:51 event

The postprocessor thinks the downloaded books are in  the "event" folder, but that's not readable.  Either it's the wrong folder set in config, or the permissions need changing to be readable for everyone.
Seems a strange location for the downloads, /var/run ?   Also not eeeryone has write access so your downloaders might not be able to download into it?
To make it read/writeable for all, something like chmod  a+rw /var/run/s6/services/lazylibrarian/event

**Comment by ausghostdog** [comment]
![image](https://user-images.githubusercontent.com/7588602/28562655-78f90a2c-7166-11e7-9fe8-9af55eb8d21f.png)
there is that and in the config as well for the install I have the following set 
docker run -d -h lazylibrarian \
  --name=lazylibrarian \
  --restart=always \
  -v /docker/data/lazylibrarian/config:/config \
  -v /docker/data/lazylibrarian/downloads:/downloads \
  -v /docker/data/lazylibrarian/books:/books \
  -e PGID=1000 -e PUID=1000  \

in the config.ini under /docker/data/lazylibrarian/config:/config under general is
[General]
logdir = /config/log
download_dir = /tvshows/Books
loglimit = 500
logfiles = 10
logsize = 204800
loglevel = 2
ebook_dir = /tvshows/Books

Now it is downloading books and handing them to the download programs it shows them as snatched but is not post processing them does the download dir need to be different to the ebook dir? Also 
do I need to change   -v /docker/data/lazylibrarian/downloads:/downloads \
  -v /docker/data/lazylibrarian/books:/books \ to reflect /tvshows/books ?

**Comment by philborman** [comment]
download_dir is where the downloaders (transmission/sabnzbd/nzbget and the others) should put your downloads. The postprocessor looks in this directory for downloaded books, and moves them into your library folder (ebook_dir). Best to keep them separate, as otherwise the postprocessor will have to scan hundreds (thousands?) of books every time it runs, instead of only scanning the new downloads.

I think docker will only give you access to the directories mapped with -v (and their subdirectories) so the downloaders (transmission/sab/nzbget etc) should be configured to put their books into the folder the docker calls /downloads, in your case /docker/data/lazylibrarian/downloads
and the postprocessor will move them into the folder the docker calls /books, in your case /docker/data/lazylibrarian/books

for example, if you downloaded "Tom Holt, Grailblazers"
transmission would put " Holt, Tom - Grailblazers [mobi].mobi yEnc" into  /docker/data/lazylibrarian/downloads
which inside the docker is called /downloads  so lazylibrarian config download_dir should be /downloads
transmission is outside the docker, so calls it /docker/data/lazylibrarian/downloads

The postprocessor would move it into /books/Tom Holt/Grailblazers/Grailblazers.mobi
which outside the docker would be  /docker/data/lazylibrarian/books/Tom Holt/Grailblazers/Grailblazers.mobi

Hope that makes sense.

**Comment by ausghostdog** [comment]
Ok thanks for all that, this is my stuff now
[General]
logdir = /config/log
download_dir = /tvshows/downloads
loglimit = 500
logfiles = 10
logsize = 204800
loglevel = 2
ebook_dir = /tvshows/Books

 --name=lazylibrarian \
  --restart=always \
  -v /docker/data/lazylibrarian/config:/config \
  -v /tvshows/downloads:/downloads \
  -v /tvshows/Books:/books \
