### ISSUE TITLE
Last couple of columns on History page are 'cut off'

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#951]
Starting with the 'Size' column which is halfway cut off, the 'Status' column is completely missing.
Looks like the table isn't auto resizing?

**Comment by philborman** [comment]
Can you post a screenshot?

**Comment by MrMxyzptlk** [comment]
![image](https://user-images.githubusercontent.com/1753001/28681814-c988320c-72c8-11e7-800d-2a62cee83934.png)

**Comment by MrMxyzptlk** [comment]
Funny that time it cut off the part of the first column and all of the last one.

**Comment by philborman** [comment]
Something wrong with resize code, can't immediately see what. Shrinking the width should drop both size and status at the same time. I think the cutoff is set to 1024 wide, any idea what window size you are using? What happens if you make the window narrower still? Might be the extra long provider names causing the problem as that column maybe can't shrink enough.

Best suggestion for now is to use the column toggles to drop id or provider (or both) so things fit better.

**Comment by MrMxyzptlk** [comment]
1920 x 1080
It cuts off more columns.
I would think a standard expectation of a table would be that it just keeps shrinking the columns, rather than cutting them off or not showing them at all?

**Comment by philborman** [comment]
Seems the way bookstrap columns work is there is a minimum width below which they can't shrink, so we have to drop columns that won't fit. Imagine trying to cram all those columns onto a mobile phone screen. Minumum size must be at least large enough to hold the column titles I guess. Not sure why we're hitting this at 1920x1080 though.

Is it just the History page it's happening on, or other pages too. Particularly the Magazine Past Issues page, which has a provider column.

Does the problem also occur on the default interface?

**Comment by MrMxyzptlk** [comment]
It does not happen on the past issues page, but I could see that it would had there been another column or 2...it only has 4, and the History page has 6.

No issue with the default interface, so it is definitely something with bootstrap.

Damn, I forgot how hideous the default interface is!

**Comment by philborman** [comment]
I'm pretty sure the column resizing code can't cope with large strings with no spaces. In the other columns, as they shrink the text splits into multiple lines, always splitting at a space. There are no spaces in the long provider strings. We probably want shorter provider strings, or split them on '/' instead of spaces.
Looks like a challenge for me...

**Comment by MrMxyzptlk** [comment]
....I'll read that as, sounds like fun ; )

**Comment by philborman** [comment]
Before I get digging too far into css and javascript (ughh)  can you do a quick bit of editing for me, just to see if I'm on the right lines...

data/interfaces/bookstrap/history.html
Line 52 <td class="provider"><a href="${item['NZBurl']}">${item['NZBprov']}</a></td>

copy your existing history.html to history.backup
edit line 52 to say <td class="provider">test several word provider name</td>
save it as history.html

No need to restart lazylibrarian, just refresh the history page in your browser. Hopefully the problem will go away and the provider name will split over several lines.

Then copy your old history.backup back to history.html or you will break future updates.

**Comment by MrMxyzptlk** [comment]
Glad to help...it will be later tonight for me, as my boss is pushing my on a project right now.

**Comment by philborman** [comment]
No problem. I managed to reproduce it by faking the provider name...
![screenshot from 2017-07-27 20-10-00](https://user-images.githubusercontent.com/12158777/28685343-bf3a26cc-7307-11e7-8672-10e870b18d01.png)

and got exactly what you got. Just need to learn enough bout css/javascript to fix it now.
Unless I hack it in the python side, now there's a thought...
Only seems to be torznab that hits this problem, or maybe rss too, but nzb and torrent are automatically shorter. You don't actually need the whole torznab name in the table, just enough to identify which one it was, so instead of http://san-02.myccg.home:9117/torznab/skytorrents  we could just put skytorrents or torznab skytorrents (with a space, not a '/'). That could easily be done in the python code.

**Comment by philborman** [comment]
ok, screenshot was definitely useful, showed the problem clearly. I have added some python code to split the provider name up, keeping the right-most part, and with spaces instead of '/' separators. Just for display purposes, still keeps the full name internally.  I have done the same for magazine titles, as torrents often put.names.with.dot.separators.and.we.get.the.same.issue being unable to split as there are no spaces.

It could probably be done in the bookstrap css, but that's beyond me. css and javascript are not something I want to have to mess with.

**Comment by MrMxyzptlk** [comment]
Just pulled the update working great!
Thanks, I think you nailed it.
