### ISSUE TITLE
Import function

### ISSUE THREAD

**Issue by TheHatter13** [DobyTang/LazyLibrarian#958]
I am running version af1ecb95f3db065983459cff5615b5b8c9926340

How is the import function supposed to work? I looked on the wiki but the search came up with nothing. 

I pointed LL to a folder and put a set of about 10 to 15 books in it and it seemed to grab a couple but then deleted the folder and the files it did not import. This is a big issue and am glad I did not put more into it as I might have lost my whole collection.

Also is there a temp folder to try and get those back?

**Comment by TheHatter13** [comment]
So I found an option for keep original files and that kept it from deleting but it kept all from deleting. I was thinking this was for post processing as its not really defined. There should be a middle ground as it seems to be deleting the whole import folder. If you have one this might be ok but if you put a bunch in LL deletes the folder before processing all of the files.

Please let me know if I have that option correct in my assumption. That option is only for the import function and not the post processing. If its for both that would be horrible to clean up unless it worked as below or there were two options.

In my opinion the way it should work is:

1. If keep is selected LL should leave everything in the folder as is and do a copy
2. If keep is not selected LL should do a move of the successful imports and leave the unmatched ones in the folder

*the import folder should not be deleted at all

**Comment by philborman** [comment]
The import function is described in the wiki under configuration where it talks about the folders and how they work. It does say it's a temporary folder and LazyLibrarian may delete the directory after importing.
The one "keep original" setting applies to all importing, postprocessing, manual import, wishlist, csv.

The idea originally was that you could only import one book from the folder, possibly with cover and metadata, and then the whole folder could be deleted after import, getting rid of any junk files left over. 

The import function was expanded later to handle multiple books, as long as each was in a separate subfolder, and I think the same rules are supposed to apply, the copy/move should work per sub-folder so it deletes each sub folder after importing the book from it, as you describe above.
I'm not sure what happens if there is a failure copying, that might be where you are hitting problems. Also I'm not sure what happens to each top level folder if there is a book imported from that. It could be lazylibrarian deletes the top level folder and any sub-directories it contains thinking the rest of the contents are not needed. That might depend on the order the folders are processed in. Then it gets more complicated if there are sub-sub-folders, with a failed copy in a deeper level folder. You can't delete the parent or grandparent even if the book in the parent/grandparent was processed correctly. Might need to look into that too. All quite complicated. "keep original" is looking quite attractive at the moment, maybe we should _never_ do a move, always copy, and let the user clear up afterwards.

There was yet another expansion to the function later, with the "include books" option. This does pretty much the same thing, but does not copy or move anything, just creates database links to the books in their original locations.  

The import code could probably do with a good clean-up, but the method you describe above is how it's supposed to work.

**Comment by TheHatter13** [comment]
Then I guess this feature is not something I can use as you say it is working as described yet it deleted out a bunch of books that it did not process. With the keep original I will have to constantly be cleaning up the auto downloads as well as the import files. I really would like it to clean up the postprocessing on its own and clean up successful files but not delete the unsuccessful files.

**Comment by philborman** [comment]
I'm not saying that it's working as described,  but the description you gave is how it is supposed to work. There may well be some issue with unprocessed books, or the order folders are processed in. Needs looking into.

**Comment by TheHatter13** [comment]
OK. I misunderstood. This was a set of individual books as I wanted LL to create the structure during import. That means that there were no subfolders. It was just a series of epub files that I had. I figured it would look at the files individually one at a time and go based off of the metadata. 

Are you saying that the function was meant for *import folder*/*folder of single book*/*file(s) for one book only* but in the base import folder you can have multiple other folders as long as those folders have only a single book.

Should the base/root import folder be deleted every time? I know its meant to be a temp location but you have to recreate the folder every time you do an import.

**Comment by philborman** [comment]
"""Are you saying that the function was meant for import folder/folder of single book/file(s) for one book only but in the base import folder you can have multiple other folders as long as those folders have only a single book."""  
Yes, that's the idea, but the book could be multi-format and include a jpg/opf  etc. as long as everything in the folder relates to one book. Anything else gets ignored or deleted.
For example, you download (you, not lazylibrarian) Anne Rice Angel Time.
It's sitting in your Download directory with the following structure...
/Downloads/Anne Rice Angel Time/Angel_Time.epub
/Downloads/Anne Rice Angel Time/cover.jpg
/Downloads/Anne Rice Angel Time/Angel_Time.mobi
/Downloads/Anne Rice Angel Time/metadata.opf
/Downloads/Anne Rice Angel Time/downloaded_from_xyztorrents.info
/Downloads/Anne Rice Angel Time/visit_our_website.txt
...you get the idea

 Lazylibrarian doesn't know you have downloaded it, but put /Downloads/Anne Rice Angel Time as your alternate directory entry in lazylibrarian config, and lazylibrarian will import it correctly.
It will move the epub,mobi,jpg,opf (renaming the cover and metadata to match the book title)
read the metadata from the epub or mobi (depending on config), supplement it with the data in the opf
then delete the remaining junk, and finally delete the Anne Rice Angel Time folder

Next time you have a book to import, it won't be /Downloads/Anne Rice Angel Time 
so you need to reset the temporary folder location

There are a few problems to work around with multiple books in the same folder. 
The metadata can't always be relied on, so an opf file can be used to supplement or override it. In particular pdf files are shockingly bad with missing or incorrect metadata. Also there is the pseudonym issue you hit earlier. opf can override that on import, but...
If you have multiple books in the folder, calibre (very popular book library system, lots of people share books from their calibre libraries) uses metadata.opf as it's metadata filename. If there are several books in the folder, which one does metadata.opf belong to?
If there are multiple books with incomplete metadata, how can we tell if they are the same book in different formats (an epub and a mobi of the same book)

If it's only one book per folder, all these problems go away, so if you create a folder, drop the book/cover/metadata into the folder, set alternate directory to the folder and import it will clean up after itself quite well. If the book was in it's own folder anyway, you just set alternate directory to that folder and import.

I'm still not convinced the multiple books in subfolders is totally safe, haven't looked at it yet
