### ISSUE TITLE
Direct Download Providers

### ISSUE THREAD

**Issue by billbo99** [DobyTang/LazyLibrarian#999]
version : a7136fdf9e16406be213d602a4177e25d0748205
os: linux
Interface : bookstrap
api: Goodreads,
Source: git

Think when downloading from  'libgen.io' it should stick to just the file types in the 'desired ebook file formats'.  They post individual files there in most cases.

**Comment by philborman** [comment]
There is some code that "prefers" titles where the required booktype is in the title,  but the scoring system is quite primitive, it's a fuzzy match on author and title, lose a point for each extra word, gain a point for correct filetype.  Can probably be improved on. The "lose points for extra words" is useful for not matching omnibus editions. Maybe add more points for the matching filetype, or if there is a matching filetype in some filenames we should take the highest scoring one of those (rather than highest score from all files) as a couple of unwanted words will outweigh the point gained for a correct filetype

**Comment by philborman** [comment]
Just trying a new scoring system with more points for matching filetypes, weighted to prefer the filetypes further left in the 'desired ebook file formats' . Should help with libgen and other sources too.
For libgen, if you have "epub, mobi, pdf" as your desired types, we score +3 for epub, +2 for mobi, +1 for pdf. We used to score +1 if any of epub/mobi/pdf so rated them equally. 
If it's a different provider with epub and mobi in the same download we score +5, so prefer that to an epub only download. Will push a new version in a couple of hours if it checks out ok.

**Comment by adamgoldberg** [comment]
IMO, I don’t care if I get epub or mobi (Calibre can convert happily between them), but I’d much rather NOT get pdf.  For me, epub, mobi or epub+mobi can get +5, and pdf +1 (or something like that, you know?)


Adam Goldberg

**Comment by philborman** [comment]
The preferred filetypes list is configurable, just take pdf out if you don't want them, and maybe also add pdf to the reject list in config/filters. The first list is "preferred words", not "must include", with the "most preferred" words on the left. The reject filter is a definite "reject list", if the title includes that word, reject it.

**Comment by billbo99** [comment]
All the links on libgen appear to be re-directing to ads.php which is a dead link.

**Comment by philborman** [comment]
Seems to be working here, or at least it was last night.
We scrape the html pages from libgen. The first results page from libgen has links that look like...
http://libgen.io/foreignfiction/ads.php?md5=xxxxxxxxxxxxxxxxxxx
and this second page has a link to download the book
http://93.174.95.27/foreignfiction/get.php?md5=xxxxxxxxxxxxxxxxxxx&key=xxxxxxxxxxxxxx

**Comment by ghost** [comment]
Hi 

It would be nice to add this download providers? Check the bottom of the site:

https://unblocked.earth/?domain=pirateproxy.cam&&status=504&request=/search/indesign%20cc
